### ISSUE TITLE
Support enabling debug output for KFP node processing

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1055]
Currently only informational | warning | error messages are displayed when notebooks | script nodes are executed in KFP:

```
[I 23:41:23.217] 'metadata':'producer' - Packages installed (29.881 secs)
[I 23:41:23.297] 'metadata':'producer' - processing dependencies 
[I 23:41:23.310] 'metadata':'producer' - downloaded producer-bbf0e65c-8f41-4ebb-8764-632d925c64f9.tar.gz from bucket: pipeline-artifacts, object: metadata/producer-bbf0e65c-8f41-4ebb-8764-632d925c64f9.tar.gz (0.013 secs)
/
producer.py
tar: Removing leading `/' from member names
[I 23:41:23.317] 'metadata':'producer' - dependencies processed (0.020 secs)
[I 23:41:23.317] 'metadata':'producer' - executing python script using 'python3 producer.py' to 'producer.log' 
[I 23:41:23.343] 'metadata':'producer' - python script execution completed (0.026 secs)
[I 23:41:23.372] 'metadata':'producer' - uploaded producer.log to bucket: pipeline-artifacts object: metadata/producer.log (0.028 secs)
[I 23:41:23.372] 'metadata':'producer' - processing outputs 
[I 23:41:23.372] 'metadata':'producer' - outputs processed (0.000 secs)
[I 23:41:23.372] 'metadata':'producer' - processing metrics and metadata 
[I 23:41:23.373] 'metadata':'producer' - metrics and metadata processed (0.001 secs)
[I 23:41:23.373] 'metadata':'producer' - operation completed (30.038 secs)
```

To enable debug output one has to
- [modify the log level setting in the bootstrapper script](https://github.com/elyra-ai/kfp-notebook/blob/master/etc/docker-scripts/bootstrapper.py#L428)
- push the updated script to GH
- set the required environment variables to use the modified REPO/branch
- restart JL

Since this is rather labor intensive we should provide the means to enable DEBUG output without making any code changes and with the least amount of steps.

**Comment by kevin-bates** [comment]
Thanks for opening this issue Patrick.  Yes, clearly more is needed to happen to make this easier configure.  My question to you is at what granularity should debug be enabled.  I see several options...

1. Flow the logging level from the elyra server to the bootstrapper.  If the server is enabled for DEBUG so too are each of the node executions.  This should be fairly doable since I believe we can access the server's log level.  The problem here is that this would apply to all pipeline executions and, if not already enabled for debug, the server would require a restart.
2. Enable DEBUG on a per-pipeline basis, with every executed node also enabled for DEBUG.  This implies a pipeline-specific flag - and probably one that is **not** configured into the runtime metadata due to its variance, but that could be an option for conveyance.  It might be good to introduce a section of the pipeline file where this kind of stuff can be set.
3. Enable DEBUG on a per-node basis.  This could be done rather easily by introducing the notion of "System Envs" where well-known prefixes are used (e.g., `ELYRA_`) to convey actions or behavior.  Something like `ELYRA_LOG_LEVEL=10` set into a node's environment variables would be used for enabling DEBUG on a per-node basis (where the env's value is the numeric log-level value).  Each of the "System Envs" would be documented of course.

FWIW, the per-node option is a possible solution for #1034 since only certain nodes may require some initialization delay (e.g., `ELYRA_DELAY_EXECUTION=25`).

Just some thoughts.

**Comment by ptitzler** [comment]
> at what granularity should debug be enabled

Option 2 and/or 3 would both make debugging life easier, unlike option 1.

**Comment by kevin-bates** [comment]
Thanks @ptitzler.  And just to be clear, neither options 2 or 3 would allow for "enablement" of any debug statements that might occur in the elyra server (including the NotebookOp constructor).  It would only enable debug logging in KFP (or supported runtimes), not the server or local pipeline executions.

**Comment by ptitzler** [comment]
Understood, although it'd be nice if the debug setting would also be applied to local executions in the future.

**Comment by kevin-bates** [comment]
For completeness...
4. Just always have DEBUG enabled in the bootstrapper.  

Originally, the "logging" was `print` statements (i.e., were unconditional).  We'd want to be careful not to spam (i.e., be cognizant of loops), but this is the least intrusive solution to the user and, frankly, is a subset of all other solutions given the debug log statements themselves need to exist in the first place - why not just make them unconditional.

My vote is option 4 actually.

**Comment by kevin-bates** [comment]
In believing that option 4 is the best approach at this time, I took a look at what debug statements would become visible once we _flow_ the enablement of debug logging from the UI, through Elyra, to KFP and found [exactly one statement](https://github.com/elyra-ai/kfp-notebook/blob/master/etc/docker-scripts/bootstrapper.py#L380).

As a result, I move that we close this issue - assuming the [kfp-notebook PR](https://github.com/elyra-ai/kfp-notebook/pull/71) is merged.  We can revisit this once we find a stronger need to do such a thing and when there may be other use-cases relative to other behaviors.

**Comment by ptitzler** [comment]
https://github.com/elyra-ai/kfp-notebook/pull/64 does add some debug output as well, including data dumps (JSON files that contain the metrics/metadata) to aid with potential merge/loss of data issues. I don't think it's going to be a lot of data though - it depends on how many metrics the notebook | script produces for visualization.

**Comment by kevin-bates** [comment]
Ah - good point.  I just took a look and it doesn't appear to be too alarming.  I think we should run with this approach for a while and get an idea of what kinds of things we might want to add in the future, if any.

**Comment by ptitzler** [comment]
works for me!

**Comment by kevin-bates** [comment]
Thanks for the response.  I'm going ahead with closure here.  We can re-open at a later time or create a new one based on what might be required at that time.
