### ISSUE TITLE
Metadata validation for runtimes throws unexpected length error

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1110]
2.0/dev

- Create a runtime configuration providing all required parameters

![image](https://user-images.githubusercontent.com/13068832/100163414-7ccaab00-2e6a-11eb-9f45-8e9a3d426028.png)

**Comment by kevin-bates** [comment]
Hi @ptitzler - this issue is because one of the field's value's doesn't meet the constraints of that property.  In this case, its too short.

When a schema validation error is encountered, we only provide the first line of the error message - which tends to be multiple lines long of verbose details.  However, in this case, one of those details is likely the property name that is producing the issue.  What is displayed in the "too short" message, is the _value_.  In your case, it's coming from one of the cos fields.

I can reproduce this by typing a cos_password of `pwd`:
![image](https://user-images.githubusercontent.com/22599560/100246991-b04f1900-2eee-11eb-8b49-13caf56434ef.png)

The schema defines cos_password to have a minLength of 8.  cos_bucket also has a length constraint of > 3 and < 222.

This has nothing to do with the 'name' field.  This was the clue for me because 'name' is not part of the schema definition and not privy to its validation (we validate 'name' manually) and because the string "too short" doesn't exist in the Elyra code base, I figured something else was happening.  If proper values are provided, you can certainly create a long-named metadata instance.

`$ elyra-metadata install runtimes --schema_name=kfp  --api_endpoint=https://kubernetes-service.ibm.com/pipeline --api_username=username@email.com  --api_password=mypassword --cos_endpoint=http://minio-service.kubeflow:9000 --cos_username=minio --cos_password=minio123 --cos_bucket=chuckit --display_name=kfp_sfhlsjdflsdjflksdjflksjdfljslfkjsdlfjsdlkfjsldkfjlsdkjflsdjfsldkhkjshdfkjshdfkjhjkfsdhfkjdfgdfg`

`Metadata instance 'kfp_sfhlsjdflsdjflksdjflksjdfljslfkjsdlfjsdlkfjsldkfjlsdkjflsdjfsldkhkjshdfkjshdfkjhjkfsdhfkjdfgdfg' for schema 'kfp' has been written to: /Users/kbates/Library/Jupyter/metadata/runtimes/kfp_sfhlsjdflsdjflksdjflksjdfljslfkjsdlfjsdlkfjsldkfjlsdkjflsdjfsldkhkjshdfkjshdfkjhjkfsdhfkjdfgdfg.json`

So, I believe our choices are:
1. Parse out the field name of the validation error
2. Return the entire message - which likely won't be well-formatted
3. Log the multiple-line message and return the first line
4. Leave as is.

FWIW, I just enabled option 3 to show what the message looks like.

Here's the command (cos_bucket is going to be too short):
`$ elyra-metadata install runtimes --schema_name=kfp  --api_endpoint=https://kubernetes-service.ibm.com/pipeline --api_username=username@email.com  --api_password=mypassword --cos_endpoint=http://minio-service.kubeflow:9000 --cos_username=minio --cos_password=minio123 --cos_bucket=ch --display_name=kfp_sfhlsjdflsdjflksdjflksjdfljslfkjsdlfjsdlkfjsldkfjlsdkjflsdjfsldkhkjshdfkjshdfkjhjkfsdhfkjdfgdfg`

And here's the logged message that would be returned.
```
[E 2020-11-25 07:28:10,193.193] 'ch' is too short

Failed validating 'minLength' in schema['properties']['metadata']['properties']['cos_bucket']:
    {'description': 'The Cloud Object Storage bucket name',
     'maxLength': 222,
     'minLength': 3,
     'pattern': '^[a-z0-9][a-z0-9-.]*[a-z0-9]$',
     'title': 'Cloud Object Storage Bucket Name',
     'type': 'string',
     'uihints': {'category': 'Cloud Object Storage'}}

On instance['metadata']['cos_bucket']:
    'ch'
```

I don't think the formatting will show up this nicely in the dialog in the UI.  It sucks the schema validate messaging is this bad.  They should start with the property and the constraint violated.

I really don't want to parse error messages since this will very likely fail in localized installations.

Perhaps a fifth option would be to return a simple "Schema validation failed" and log the message in the log to which they are instructed to go look?

**Comment by ptitzler** [comment]
Thanks for digging into it Kevin! A couple of thoughts:
 - From a usability point of view a validation error message should identify the input field  that violates a constraint, the problematic value and the failing constraint.
 - We should document all constraints for every property if validation messages don't provide the information. Right now we are asking the user to play 10 questions in a way (:
 - Some of the constraints appear to be conflicting, as your example output above illustrates:
    `'pattern': '^[a-z0-9][a-z0-9-.]*[a-z0-9]$',` => `ab` is valid, yet violates `'minLength': 3`. Using '`^[a-z0-9][a-z0-9-.]+[a-z0-9]$'` as a pattern instead, the two constraints are no longer conflicting.
 - We should try at all cost to avoid the need for users to check the log file to identify UI input issues. 

Is there a particular reason why validation can't return a data structure that contains the critical information and leaves it up to the client (UI or CLI) to decide what pieces of information to expose**, and how?

In your example above this information might be returned to the client as:

```
 {
   'property_name': 'cos_bucket',
   'property_display_name': 'Cloud Object Storage Bucket Name',
   'property_value': 'ch',
   'violated_constraint': {               // based on observed behavior that validation aborts and doesn't check all constraints
      'name': 'minLength',
      'display_name': '...'
      'constraint_value': '3'
   } 
 }
```

** Display the parameter name `cos_bucket` in the CLI error and `Cloud Object Storage Bucket Name` in the UI since that is what the user is exposed to explicitly, via the specified parameter name and input field label, respectively.
