### ISSUE TITLE
Unable to run pipeline without github.com connection in air gapped environments

### ISSUE THREAD

**Issue by jazzsir** [elyra-ai/elyra#1164]
I can't run any pipelines without github.com connection in air gapped environments.

```
[kf@k8s-master01:/home/kf/yaml] kubeflow -nadmin logs -f lambda-x8lxn-3172984272 -c main                         
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed                      
  0     0    0     0    0     0      0      0 --:--:--  0:02:11 --:--:--     0curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection timed out
```
I tried to remove .git directory, but it's a required step.
Please let me know how to disable github connection.

**Comment by lresende** [comment]
The issue is that we load the [component execution script](https://github.com/elyra-ai/kfp-notebook/blob/8092a27b0aec854d5968943f5aa8f3109ad52b74/kfp_notebook/pipeline/_notebook_op.py#L110) from github. 

A workaround would be to deploy those files locally into the gap environment and update the link. 

A fix would be to enable overriding of those via configuration/environment variable.

Patches are welcomed, otherwise, we will look into it, but the community is a little slow during the holiday season as many are on vacation.

**Comment by jazzsir** [comment]
@lresende Thanks, I will work on this.

**Comment by ConverJens** [comment]
@jazzsir I'm in a similar situation, what is the status on this? Do you need help implementing this feature?

**Comment by jazzsir** [comment]
Sorry for late PR, please check it and let me know things to be remedied

**Comment by ConverJens** [comment]
@jazzsir  I can test it. I'm new to Elyra, what steps do I need to take to try this out?
