### ISSUE TITLE
Allow different stages of a pipeline to run on differently-sized containers

### ISSUE THREAD

**Issue by frreiss** [elyra-ai/elyra#1188]
In the pipeline in the `covid-notebooks` project (https://github.com/CODAIT/covid-notebooks/blob/master/pipelines/us_data.pipeline), one of the notebooks (`fit_us_data.ipynb`) takes considerably longer than the rest because it performs 10,000 curve-fitting operations serially, one after the other. I would like to make this notebook run faster by performing the curve-fitting operations in parallel.

This change will require having the `fit_us_data.ipynb` notebook run on a larger container with more cores. I would like for the remaining notebooks in the pipeline to continue running on smaller containers. 

Currently there is no way to specify in the pipeline editor UI that different stages of the pipeline should execute on containers with different amounts of CPU and/or memory. Containers inherit whatever is the default container size for the KFP cluster.

**Comment by akchinSTC** [comment]
@marthacryan - hey hey, since youve been touching the side pane stuff for common properties, how much work would it be to add two small fields to the node properties, one for cpu and one for memory requests? 

@lresende - this can be passed easily enough to the container op, but in a managed env like jhub, limits will need to be set by the administrator. Quickest way maybe would to be include a env var or something injected to each singleuser env prior to start so that it gets picked up during pipeline compilation, thoughts?

**Comment by lresende** [comment]
> @marthacryan - hey hey, since youve been touching the side pane stuff for common properties, how much work would it be to add two small fields to the node properties, one for cpu and one for memory requests?
> 

Might actually be three fields one for GPU? But let's make this separate from what @marthacryan is working now. 

> @lresende - this can be passed easily enough to the container op, but in a managed env like jhub, limits will need to be set by the administrator. The quickest way maybe would to be include an env var or something injected to each singleuser env prior to start so that it gets picked up during pipeline compilation, thoughts?

In the past (in the context of JEG) we have discussed sizes (e.g. Small env, Med env, Large env) we could think about that instead of the individual fields? These profiles could be pre-configured by admins

**Comment by frreiss** [comment]
Predefined sizes would be fine for my use cases. Actually, it would be sufficient if the admin could configure a list of predefined combinations of image + container size -- for example, `anaconda-small`, `anaconda-large`, `GPU-medium`, ...

**Comment by akchinSTC** [comment]
@marthacryan - we will probably need two fields, one for the container size(sm,med,lg) and one for number of gpus, since not all workloads will require gpus and it doesnt make sense to include gpu resources in with container sizing

**Comment by akchinSTC** [comment]
scratch that^^. lets stick with our original plan to plumb 3 new fields, CPU, Memory and GPU.
