### ISSUE TITLE
Compilation of Elyra-Pipelines to Tekton based Kubeflow fails

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#1222]
**Describe the issue**
The elyra pipeline editor can't be used to compile and push pipelines to tekton based kubeflow pipeline services

Please see discussion on [Stackoverflow](https://stackoverflow.com/questions/65832799/compilation-of-elyra-pipelines-to-tekton-based-kubeflow-fails)

**Comment by Tomcli** [comment]
The api itself is the same, only the payload yaml has to be a tekton resource instead of argo. All we need to do is change this line to kfp_tekton.compiler.TektonCompiler().compile(pipeline_function, pipeline_path)  and avoid any code that’s specific to Argo. (e.g. argo variables and code that changes the Argo yaml directly)
https://github.com/elyra-ai/elyra/blob/9de4c89a0e35f13dedd671ce36cb3f6286593fea/elyra/pipeline/processor_kfp.py#L74

**Comment by romeokienzler** [comment]
@lresende sounds easy, what's your thought on that?
