### ISSUE TITLE
Code Snippets Languages

### ISSUE THREAD

**Issue by jingsta** [elyra-ai/elyra#1282]
How does one add more code snippets languages to the selectable list.

Example is I have powershell and Rust I want to add as well to the list.

**Comment by lresende** [comment]
The list is dynamic with the most used examples pre-populated. When you create a new code-snippet, please type the new entry (e.g. Rust) and it should be available after that.

**Comment by jingsta** [comment]
Lol.... man i feel dumb. lol. Thanks man!

**Comment by ptitzler** [comment]
I do believe we should update https://elyra.readthedocs.io/en/latest/user_guide/code-snippets.html, because unlike https://elyra.readthedocs.io/en/latest/user_guide/runtime-conf.html#configuration-settings (for example) it doesn't provide any help that describes the properties.  I do agree that the current selection widget is ambiguous and the input field can be interpreted as a _search/filter_ condition for the default language list.

**Comment by karlaspuldaro** [comment]
@ptitzler I created #1286 to track your suggestion

**Comment by ptitzler** [comment]
Related issues, which should make it easier for users to use the metadata widgets: 
 - https://github.com/elyra-ai/elyra/issues/1291 (add tool tips)
 - https://github.com/elyra-ai/elyra/issues/838 (add link to documentation)

**Comment by ptitzler** [comment]
@jingsta If you would like to permanently add language options to the default list, feel free to update https://github.com/elyra-ai/elyra/blob/master/elyra/metadata/schemas/code-snippet.json#L40 and open a pull request.
