### ISSUE TITLE
Code Snippets properties documentation needs more info

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#1286]
As suggested in [this issue comment](https://github.com/elyra-ai/elyra/issues/1282#issuecomment-777158256), the [code snippets documentation](https://elyra.readthedocs.io/en/latest/user_guide/code-snippets.html) needs to be more clear about its metadata properties and better describe them.
![image](https://user-images.githubusercontent.com/25207344/107660274-13328f80-6c56-11eb-95a0-471c291b8ce2.png)

Metadata editor:
- [ ] Describe input fields
- [ ] Describe Language selection/create new
- [ ] Describe tags

Other:
- [ ] Describe Save as Code Snippet command

**Comment by ptitzler** [comment]
How to add a new language entry 
![add_to_options](https://user-images.githubusercontent.com/13068832/107835399-39d3f180-6d4e-11eb-8828-7a450b7eb325.gif)

**Comment by kevin-bates** [comment]
Hi Patrick, I'm assuming your comment would be used to seed some documentation for how to add a custom language.

If so, I would also suggest that something be typed into the `Code` edit control to enforce that you're _creating_ the new language entry. I think that might make for a stronger example.  It doesn't need to be "Power" valid syntax, or, if possible, select a different, non-existent, language (e.g., Julia may make for a good example since it is a "founding language of Jupyter) and type actual Julia code into the text box.

**Comment by gigibarnett** [comment]
I am part of the Jumpstart program and thought about taking a stab at this. I will read Docs: [https://elyra.readthedocs.io/](https://elyra.readthedocs.io/ ) **Getting Started & User & Developer Guides**, but is there additional information I should be aware of and/or need to get going?

**Comment by karlaspuldaro** [comment]
Hi @gigibarnett 
Looks like this was already resolved by #1528 , we probably just forgot to close this issue, oops!

What I would suggest, if you're interested in this section, is to [install Elyra](https://elyra.readthedocs.io/en/latest/getting_started/installation.html#installation) and follow the latest [code snippets documentation](https://elyra.readthedocs.io/en/latest/user_guide/code-snippets.html), see if everything there is clear, and if there's anything else that could be improved or better described, no matter how small, feel free to open a new PR.
