### ISSUE TITLE
Python editor: support static string replacement

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1290]
The Python Language Server support makes it possible to globally replace variable names. 

For arbitrary string sequences (e.g. `abc`) that are not variables, one can find them [in any JL editor] but it's not yet possible to  **find and replace**  them. It'd be great if the editor could support this common task.

**Comment by krassowski** [comment]
Do you mean this?

![elyra-search](https://user-images.githubusercontent.com/5832902/107983647-1ca55a00-6fbe-11eb-8f4c-3b319d1da129.gif)

**Comment by ptitzler** [comment]
Ah yes. That's it! Thank you @krassowski! Not sure how I missed it.

**Comment by krassowski** [comment]
Happy I could help :) But, seriously, this is a design issue as way too many users upvoted my [gif on SO](https://stackoverflow.com/a/59700577/6646912) with exactly this action (but in notebook) and countless users on GitHub, across repositories complained about lack of search and replace (months since it was added). I raised this issue here: https://github.com/jupyterlab/jupyterlab/issues/6650 and would greatly appreciate your ideas and contributions.
