### ISSUE TITLE
Elyra pipeline handler fails when submitting pipeline json payload

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1297]
**Describe the issue**
When building pipeline CLI, the handler was failing to parse the JSON payload when that was submitted as `application/json`. Changing to regular `data` works ok, so we need to make sure we support both payload mime types.

This should be enhanced around the pipeline handler
https://github.com/elyra-ai/elyra/blob/dd58862f908ab9e228cf2c77c29c76980a109c03/elyra/pipeline/handlers.py#L39

**Comment by kevin-bates** [comment]
@lresende - could you please post an example of the error message you received when using `application/json` in the request or provide steps for how to reproduce it?

**Comment by kiersten-stokes** [comment]
Just wanted to add a little extra context after discussing with Luciano last week. The goal here is to get pipeline information that is not explicitly sent as parsable JSON to work with the API.

### Reproduction Info

 1. Run a pipeline using the JupyterLab UI, and capture everything between the brackets `{ }` in the request body (`self.request.body`) received in `handlers.py` in the `post` function (line 81).  The body will be JSON-formatted in this case.

 2. Convert the request body string above to a valid python object by changing any instances of `false` to `False`, `true` to `True`, `null` to `None`, and any other required operations. (clunky, I know)

 3.  Open a python console, and get a URL-encoded string by running:
 ```
 import urllib.parse
 urllib.parse.urlencode([above object])
 ```

 4. Set up Postman* (or use another method) to query the pipeline scheduler API to submit pipelines without the use of the UI. When submitting the request, use the url-encoded string as the body data of the request. *Happy to provide specific details on Postman setup if anyone would find this helpful.

 5. Because the request body is not JSON, the request will fail, as seen below. Ideally, we want to add logic to handle the case where data sent to the API is not automatically JSON-formatted.

<img width="1145" alt="Screen Shot 2021-03-17 at 7 34 23 PM" src="https://user-images.githubusercontent.com/31816267/111556150-e0e5e780-8757-11eb-906b-fa78b1545b99.png">
