### ISSUE TITLE
Missing kernelspec on new notebooks created in VSCode

### ISSUE THREAD

**Issue by bourdakos1** [elyra-ai/elyra#1337]
**Describe the issue**
Notebooks created in VSCode don't have a kernel spec until you run them, which causes issues when trying to run them with Elyra.

**To Reproduce**
1. Create and open an `.ipynb` file in VSCode
2. Add some content to it
3. Save the notebook file
4. Open the notebook Jupyter Lab
5. Add the notebook to an Elyra Pipeline
6. Set a runtime image for the node
7. Submit notebook for local execution
8. Get error `KeyError: 'kernelspec'`

**Screenshots or log output**
<img width="1904" alt="Screen Shot 2021-02-25 at 10 38 17 AM" src="https://user-images.githubusercontent.com/4212769/109178117-8825bf00-7756-11eb-9eb8-9af6787db597.png">

**Expected behavior**
Either a better error message with steps to resolve the issue, or just magically run somehow.
(This can be fixed by opening the notebook in Jupyter Lab and re-saving the file or by running the notebook at least once in VSCode)

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 1.5.3
 - Operating system: macos
 - Installation source: from source
 - Deployment type: local installation

**Pipeline runtime environment**
If the issue is related to pipeline execution, identify the environment where the pipeline is executed
 - Local execution

**Notebook source:**
```
{
 "metadata": {
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": 3
  },
  "orig_nbformat": 2
 },
 "nbformat": 4,
 "nbformat_minor": 2,
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"hello world\")"
   ]
  }
 ]
}
```

**Comment by ptitzler** [comment]
Good catch and a new workflow scenario that hasn't been on our radar screen yet. Sounds like there are two things that need to be done to handle this:
- During pipeline validation each notebook is checked to verify that it contains a kernel spec entry (which may or may not be valid, but at least it needs to be present). I don't believe we should try to use a default if no kernel spec is defined.
- The code that failed with the key access error needs to handle the problem scenario gracefully

**Comment by kevin-bates** [comment]
> Notebooks created in VSCode don't have a kernel spec until you run them

Does VSCode prompt for a kernelspec then?  How does it determine which spec to use in a pure notebook scenario?

Do you know if VSCode-created notebooks _ever_ embed kernelspec information? Or only once they've been run?

> During pipeline validation each notebook is checked to verify that it contains a kernel spec entry (which may or may not be valid, but at least it needs to be present). I don't believe we should try to use a default if no kernel spec is defined.

I think this depends on how VSCode works and what its expectations are.  If VSCode only adds the kernelspec info after first run, this would imply that we could never support a Notebook's first run occurring during the processing of a pipeline and I'm not sure we should necessarily impose that restriction.  I'm not saying I have a solution to this, I'm just sayin'. :smile:

**Comment by bourdakos1** [comment]
There's a dropdown in the top-right corner of the notebook that lets you select a kernel, by default (for me)` Python 3.9.1 64 bit` is shown there (even when the kernelspec hasn't been set). If I click the dropdown and re-choose the same kernel, it updates the kernelspec in the notebook json

**Comment by bourdakos1** [comment]
Basically `kernelspec` isn't updated until you either manually select it or you run it (and then it uses some default)

**Comment by kevin-bates** [comment]
Are you able to determine how kernelspecs are configured and discovered in that env?

My (extremely) limited understanding is that VSCode doesn't really use the Jupyter framework for this and has essentially rolled its own server.

**Comment by bourdakos1** [comment]
yea I believe that is the case. If I run `jupyter kernalspec list` in my conda environment I only have one kernel `python3`. VSCode has a huge list of kernels, a bunch of python versions and a kernel for every conda env. The name for all of python 3 kernels are just `python3`. However, they have an additional metadata field that stores a hash for an interpreter:
```
"metadata": {
  "interpreter": {
    "hash": "ac2eaa0ea0ebeafcc7822e65e46aa9d4f966f30b695406963e145ea4a91cd4fc"
  }
}
```
All of this information is deleted when opened in jupyter lab

**Comment by kevin-bates** [comment]
Hmm - so if Jupyter's KernelSpecManager is not able to see VSCode kernels, I'm not sure what we can do.  So is this really an issue around VSCode-created notebooks?  That is, if the notebook _had been_ created by Jupyter, but opened and used in VSCode, would it still be usable in Elyra?

**Comment by kevin-bates** [comment]
Ok - per a side-bar discussion, the server will detect missing kernelspec information.  If the information is present, but the kernel is not available, we'll use the language indicator and select the first kernel found that corresponds to that language (which I believe is the case today).  If no language (or kernelspec information) is present, we'll use the default kernel name configured on the notebook server's KernelManager.  A warning message should be produced indicating this defaulting behavior has taken place.

It also sounds like VSCode "insiders" will be updating the notebook with kernelspec information on first use.   However, the server changes described above are good to have in place anyway.

Thanks @bourdakos1!

**Comment by bourdakos1** [comment]
@lresende I tried submitting another VSCode generated notebook from master branch this morning and I still see the kernel spec issue. Was this assigned to me for testing or should I try and make a PR to fix the issue?

**Comment by kevin-bates** [comment]
If we're simply trying to improve the user experience with a better message or possibly interrogating the language-info, then I can take this.  The crux of this issue is that papermill makes an assumption that the kernelspec will be in the NB metadata.  Since they allow a `kernel_name` to override that, I'm sure the idea is that, in those cases, they expect the user (vscode) to provide the kernel name.

I think the right thing to do here is add best-fit logic like we do in kfp, but extend it to include checks against the language-info (which should also apply to kfp).

I don't think we want to catch `KeyError` from papermill, but I suppose that could be a fallback should we run into issues with language-info code.

So the idea would be - since this is local processing - check the NB metadata, if a kernelspec exists, done (let default scenario happen - even if that particular kernel is not defined, the error message will be appropriate), else, look at language-info to determine language, then hit the kernelspec manager to find matching language.  We should probably check if the "default" kernel is also a language match and let that override any (if it matches the lang).  Once found, set the `kernel_name` to that when calling Papermill.

I'll go ahead and assign this to me.

**Comment by kevin-bates** [comment]
In looking into the changes, I see that Papermill has addressed the `KeyError` issue in its 2.3.3 release, replacing it with a `ValueError: No kernel name found in notebook and no override provided." error.

I just updated my master branch and was surprised that the error message wasn't richer than this given @kiersten-stokes's recent work...
![image](https://user-images.githubusercontent.com/22599560/112527477-548f8200-8d60-11eb-984b-0772cebbbe66.png)

I'm thinking we might want to include `ValueErrors` in the header as well since they tend to be reasonably lengthed (although this can be a slippery slope).  I suppose, in this else branch we could check the length of `str(ex)` and if reasonable (say < 80 characters) include it or just always include the first so-many characters (say 40) followed by an ellipses.  (FWIW, "No kernel name found in notebook and no override provided." is 59 characters, so I think ellipsing at the 80 character mark might be reasonable - if we want to do that.)

![image](https://user-images.githubusercontent.com/22599560/112528450-658cc300-8d61-11eb-871f-929a0360be3e.png)

@kiersten-stokes - do you recall what kinds of errors were producing too much "noise" to include the header when working on #1411?

<details><summary>Here's the complete stack:</summary>
<p>

```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/elyra-test/lib/python3.6/site-packages/elyra/pipeline/processor_local.py", line 178, in process
    **additional_kwargs
  File "/opt/anaconda3/envs/elyra-test/lib/python3.6/site-packages/papermill/execute.py", line 104, in execute_notebook
    kernel_name = nb_kernel_name(nb, kernel_name)
  File "/opt/anaconda3/envs/elyra-test/lib/python3.6/site-packages/papermill/utils.py", line 53, in nb_kernel_name
    raise ValueError("No kernel name found in notebook and no override provided.")
ValueError: No kernel name found in notebook and no override provided.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/elyra-test/lib/python3.6/site-packages/elyra/pipeline/processor_local.py", line 76, in process
    operation_processor.process(operation)
  File "/opt/anaconda3/envs/elyra-test/lib/python3.6/site-packages/elyra/pipeline/processor_local.py", line 187, in process
    raise RuntimeError(f'({file_name})') from ex
RuntimeError: (node1.ipynb)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/elyra-test/lib/python3.6/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/opt/anaconda3/envs/elyra-test/lib/python3.6/site-packages/elyra/pipeline/handlers.py", line 89, in post
    response = await PipelineProcessorManager.instance().process(pipeline)
  File "/opt/anaconda3/envs/elyra-test/lib/python3.6/site-packages/elyra/pipeline/processor.py", line 78, in process
    res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
  File "/opt/anaconda3/envs/elyra-test/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/anaconda3/envs/elyra-test/lib/python3.6/site-packages/elyra/pipeline/processor_local.py", line 81, in process
    raise RuntimeError(f'Error processing operation {operation.name} {str(ex)}') from ex
RuntimeError: Error processing operation node1 (node1.ipynb)
```
</p>
</details>

**Comment by kiersten-stokes** [comment]
> @kiersten-stokes - do you recall what kinds of errors were producing too much "noise" to include the header when working on #1411?

Hmm I remember having a justification for leaving it out but now I can't find it anywhere in my notes. I think it might have been because there were some very nicely formatted exceptions and some that were all over the place. But unfortunately I can't find a good example.

**Comment by kevin-bates** [comment]
No worries.   Looks like there's some refactoring needed anyway since #1418 doesn't include stuff from #1411 that it should.  I'm going to refactor the script operation classes (as suggested during #1418 review) and create a method that adds some minimal portion of the error message to the generic handling portions that weren't part of the focus on #1411.

The new error for this specific issue will appear as follows:
![Screen Shot 2021-03-25 at 2 35 42 PM](https://user-images.githubusercontent.com/22599560/112551547-67b14a80-8d7e-11eb-8678-b8365a35fd4b.png)
