### ISSUE TITLE
Python Editor output buttons are missing tooltip info

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#1399]
**Describe the issue**
Python Editor console output up/down buttons have no tooltip info

![image](https://user-images.githubusercontent.com/25207344/110499512-5271c600-80c6-11eb-855c-057cfa04c31a.png)

**To Reproduce**
1. Open a python file in Elyra
2. Add some python code (if you have an empty file)
3. Click the run button on the toolbar
4. Hover over the up/down arrow buttons in the console output and notice there's no tooltip information

**Environment information**
 - Elyra version: 2.1.0rc2
 - Operating system: MacOS
 - Browser: Chrome

**Comment by mudspringhiker** [comment]
I can also take a look at this. Thanks @karlaspuldaro!

**Comment by mudspringhiker** [comment]
@karlaspuldaro Finally solved my dev environment problem (by using my personal computer instead of my work computer).  Also able to figure out how to add the tooltip--just a matter of adding a prop ("title") to LabIcons `caretDownEmptyThinIcon` and `caretUpEmptyThinIcon`. So now, it has these (sorry it does not show my cursor in the screenshots).

<img width="838" alt="Screen Shot 2021-06-11 at 10 15 46 PM" src="https://user-images.githubusercontent.com/17956412/121763553-a8f60280-cb02-11eb-8a0e-4e56c609026c.png">
<img width="847" alt="Screen Shot 2021-06-11 at 10 15 37 PM" src="https://user-images.githubusercontent.com/17956412/121763555-aabfc600-cb02-11eb-94b5-c2d48f02ddf3.png">

**Comment by mudspringhiker** [comment]
Thanks for the help, @karlaspuldaro!

**Comment by karlaspuldaro** [comment]
@mudspringhiker That's awesome! ❤️ Glad to hear the dev env worked for you on a new machine, it might be something in your old env that still needs to be cleaned up somehow
