### ISSUE TITLE
Pipeline Editor should inherit assets (files) output from upstream stages without re-defining them

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#1422]
**Is your feature request related to a problem? Please describe.**
I'm developing a pipeline, some stages acting on a csv, some on image data, so if stage x defines metadata.csv as output, stage x+1 doesn't stage x+2 can't read metadata.csv because it is not explicitly declared so in stage x+1

**Describe the solution you'd like**
Let's continue the example with metadata.csv: If stage x defines it as output, stage x+1 not, it should be available for stage x+2

**Describe alternatives you've considered**
Otherwise on has to keep track of each and every file any upstream stage might define as output

**Comment by ptitzler** [comment]
Can you please provide an example pipeline. What you are describing should already work.

**Comment by ptitzler** [comment]
Used the following pipeline to verify that this works as expected:
 - download and extract archive
 - start JL
 - open pipeline and run on KFP
[producer_consumer.tar.gz](https://github.com/elyra-ai/elyra/files/6131040/producer_consumer.tar.gz)

**Comment by romeokienzler** [comment]
Hi @ptitzler thanks for getting back to me. I confirm that your pipeline works as designed, but mine not.

I'm defining metadata.csv as output in the filter stage here:
![image](https://user-images.githubusercontent.com/5694071/110977214-2ffbd900-8362-11eb-822c-82de7f29a344.png)


But in a downstream operator metric-aix360-lime.ipynb I can't access it:
![image](https://user-images.githubusercontent.com/5694071/110977425-72bdb100-8362-11eb-948e-b9cc73769088.png)

**Comment by romeokienzler** [comment]
@ptitzler you can try with
https://github.com/romeokienzler/component-library/tree/elyra1407
and https://github.com/romeokienzler/examples/blob/master/pipelines/claimed_covid_ct_trusted_ai/covid19-trustedai.pipeline

**Comment by ptitzler** [comment]
I was able to recreate the behavior using the original pipeline and a simplified version.

![image](https://user-images.githubusercontent.com/13068832/111002299-0c249d00-833a-11eb-979b-119db0f6afef.png)

To recreate:
- download and extract [pipelines.tar.gz](https://github.com/elyra-ai/elyra/files/6133208/pipelines.tar.gz) into a work directory
- cd into the work directory
- launch jupyterlab
- in the file browser navigate to `pipelines/claimed_covid_ct_trusted_ai/`
- open `simple-covid19-trustedai.pipeline`
- run pipeline on KFP
- the last node should fail with a 404 because `metadata.csv` was not found

**Comment by ptitzler** [comment]
A simpler version ...
[pipelines.tar.gz](https://github.com/elyra-ai/elyra/files/6133556/pipelines.tar.gz)

**Comment by ptitzler** [comment]
Should be resolved in 2.1.0rc5

**Comment by romeokienzler** [comment]
Thanks @ptitzler @lresende I confirm it is resolved in 2.1.0rc5
