### ISSUE TITLE
Runtime image property isn't properly displayed in node properties

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1442]
**Describe the issue**

![image](https://user-images.githubusercontent.com/13068832/111330034-d549d200-862c-11eb-99b3-cd1b0db525ae.png)

**To Reproduce**
1. Create a notebook
2. Create a pipeline
3. Add notebook to pipeline
4. Open node properties

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.1.0rc5 + 2.1.0/master (any browser)
 - Installation source: PyPI, from source
 - Deployment type: local installation

**Comment by ajbozarth** [comment]
This seems to have been caused by the release of canvas 10.2.0, reverting to 10.1.0 fixes the problem. 10.2.0 seem to change how labels for properties work and it breaks our custom css. @marthacryan it may make more sense to you to tackle this since you wrote our custom css for properties. If we want a quick fix I can pin the canvas version to 10.1.0

Note: the label Dom element is now a child element of the dropdown Dom element rather than being a sibling Dom element

**Comment by ptitzler** [comment]
Wouldn't it be sufficient to switch https://github.com/elyra-ai/elyra/blob/master/packages/pipeline-editor/package.json#L37 to `~10.1.0`. This would still pick up patches but not upgrade to the latest minor version.
