### ISSUE TITLE
Elyra installation in Docker container is freezing

### ISSUE THREAD

**Issue by ticlazau** [elyra-ai/elyra#1486]
Hello,

I have seen the docker build of Elyra from https://hub.docker.com/r/elyra/elyra

I try to build my own container based on Ubuntu but when RUN pip3 install elyra, it gets stack in:

```
=> [ 2/43] RUN pip3 install elyra                                                             7973.2s
 => => #  C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/sur
 => => # veys/backtracking
 => => # INFO: pip is looking at multiple versions of pycodestyle to determine which version is compat
 => => # ible with other requirements. This could take a while.
 => => # INFO: pip is looking at multiple versions of pyasn1 to determine which version is compatible
 => => # with other requirements. This could take a while.
```

Can you share the Dockerfile was used to build the https://hub.docker.com/r/elyra/elyra ?

Rgds,
Florin

**Comment by ptitzler** [comment]
Hi @ticlazau,

The easiest way to build the container image is to use the `container-image` task in the [Makefile](https://github.com/elyra-ai/elyra/blob/master/Makefile#L151). The `Dockerfile` is located in this directory: https://github.com/elyra-ai/elyra/tree/master/etc/docker/elyra.

The problem you are running into is a known issue caused by the new-ish pip resolver. As a workaround we are passing  `--use-deprecated=legacy-resolver` to the install process, e.g. `pip install elyra --use-deprecated=legacy-resolver && jupyterlab build`

**Comment by lresende** [comment]
> The problem you are running into is a known issue caused by the new-ish pip resolver. As a workaround we are passing `--use-deprecated=legacy-resolver` to the install process, e.g. `pip install elyra --use-deprecated=legacy-resolver && jupyterlab build`

You would need to update to the latest pip to be able to use this `pip install --upgrade pip`

**Comment by ptitzler** [comment]
See note in https://elyra.readthedocs.io/en/latest/getting_started/installation.html#pip for problem background information

**Comment by ticlazau** [comment]
Thank you all!
