### ISSUE TITLE
Provide example Dockerfile that builds an Elyra container image from a PyPI release

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1490]
The official Elyra container image is built from the master branch (see https://github.com/elyra-ai/elyra/blob/master/etc/docker/elyra/Dockerfile#L42-L43), which makes sense from a development point of view. However, a user might want to build a custom image and use the published Elyra artifacts from PyPI. We should provide an annotated version of a Dockerfile that does just that, because there is no value in forcing the user to build from source code if  the user has no intention of modifying the Elyra source code.

**Comment by lresende** [comment]
@ptitzler I don't think that having a docker file where you pretty much install elyra from pipy is very helpful, maybe just as a sample in the documentation might be ok, but otherwise, it's a `default docker file plus the `install elyra command` from Elyra readme.

Having said that, I do believe that we could enhance our current dockerfile, and detect that the version is a release or dev from the master branch, and in the case of a release just do the pip install. This should decrease the image size considerably.

**Comment by ptitzler** [comment]
This should be addressed by https://github.com/elyra-ai/elyra/pull/1536 and updated documentation in https://github.com/elyra-ai/elyra/tree/master/etc/docker/elyra
