### ISSUE TITLE
Proposal to track yarn.lock

### ISSUE THREAD

**Issue by bourdakos1** [elyra-ai/elyra#1544]
Currently, we do not commit `yarn.lock` files. This is a highly recommended practice by `yarn` itself, see [Lockfiles should be committed on all projects](https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/). From time to time we experience build issues stemming from bugs in small version changes of dependencies. This results in wasted dev hours trying to track down exactly which packages are causing the issue, for example (https://github.com/elyra-ai/elyra/pull/1541).

I believe that the majority of these issues arise from temporary bugs in large build tools (babel, webpack, etc..), completely halting our development until they are resolved. Additionally, new contributors to Elyra could get frustrated when trying to make a contribution, but met with a failing build. Keeping a `yarn.lock` should solve this problem and guarantee a stable build for that version of the `yarn.lock`. Without a `yarn.lock` our builds can start failing, unexpectedly, at any point in time (even without any code changes from us).

A common concern for keeping a `yarn.lock` is that it will hide these bugs, showing themselves when an end user tries to install Elyra. This is very true, but only true for **runtime** dependencies (which I believe is a much rarer occurrence). Additionally, runtime dependencies normally don't result in complete system failures, but smaller UI bugs. It is also important to note that with and without the `yarn.lock`, a problematic version bump in a runtime dependency could be released the second after we release Elyra, causing issues for end users, but unseen by us when releasing. This can be combated with stricter pining of any problematic dependencies and having a cron job GitHub action that runs our integration tests on a version of Elyra that was built with the lockfile, but uses the latest allowed versions of the runtime dependencies.

**Comment by lresende** [comment]
Could you please also document best practices to bring it up to date, in particular during the release process.

**Comment by bourdakos1** [comment]
Normally, it will only ever be updated when you add/upgrade/remove dependencies. I don't think it is a best practice to force it to update.

**Comment by lresende** [comment]
So, let's say you have jupyterlab-xxxx:^3.0.0 and there is a new lab release which updates a transient dependency that has a security fix. 

When we release Elyra, how do we make sure the lock file is pointing to the latest lab release that has the security fix?

**Comment by lresende** [comment]
Btw, lab has a script to update all the dependencies (or a subset of them) and its used before a release.

**Comment by bourdakos1** [comment]
If you want to guarantee that end users will have the security fix, say `jupyterlab-xxxx@^3.0.1` you would need to run `yarn upgrade` this will update the package.json to have `jupyterlab-xxxx@^3.0.1` instead of `jupyterlab-xxxx@^3.0.0`

**Comment by lresende** [comment]
But this is different from what we have today, as we always rebuild the lock file with latest dependencies and it should be documented. 

To me, the benefit of not checking in the lock file is basically this, we, developers, find the issue and deal with the  as soon as they become an issue, but the users will be safe as the lock is part of the release.

Not having the lock, it seems that will need to force an update, and then handle multiple issues that might have been created since last update, and not necessarily getting rid of them.


The detailed documentation is basically aimed to help RMs that might not be experts on yarn/webpack to be able to do the right thing.

**Comment by bourdakos1** [comment]
> But this is different from what we have today, as we always rebuild the lock file with latest dependencies and it should be documented.

No, our lockfile does not impact the end users dependencies

> To me, the benefit of not checking in the lock file is basically this, we, developers, find the issue and deal with the as soon as they become an issue, but the users will be safe as the lock is part of the release.

As mentioned above, we the majority of the time we aren't catching user facing issues, we are just breaking our build. Additionally, these issues can easily show up _after_ we publish. The only way to completely prevent issues on the user end is if we completely bundle all of our runtime dependencies, but we can't really do this because we have peer dependencies with Jupyter. Our lock doesn't effect the users at all. When a user installs Elyra for the first time, it installs as if the lockfile never existed. Most of the time the users will have their own lockfiles, so they won't get any updates until they upgrade elyra.

**Comment by lresende** [comment]
Now you made me much more confused. So, if we add the lock, we will be using a set of locked dependencies that might all work ok, instead of using the latest dependencies that would be what a user sees when they install Elyra? This will make our life easy, and hide us from issues that we could have fixed to make users life easier?

**Comment by kevin-bates** [comment]
I'm just a crusty old server developer (and barely a python developer at that), but if I'm understanding this stuff, a persistent lock file would also serve as a stake in the ground indicating exactly what versions we qualified against.  Since it would be good to resolve possible dependency-related issues prior to release, does it make sense to upgrade the lock contents when cutting, say, the first _pre-release_?  This would then give us some time to ferret out and track down dependency issues such that they could be resolved, persisted in the updated lock, and allow us to re-qualify during the pre-release cycles.  The "released" lock file then still serves as a stake stating "we know Elyra works against these versions".

**Comment by lresende** [comment]
Yes @kevin-bates, that's what it looks like. I just want to make sure this don't become something like the canvas updates, where if we update frequently we just have to fix a few css issues, compared to in the past, where we skipped several releases and it took a lot more time to get things back working again. If we update several dependencies just when we are close to the release, it might take us longer to be green again. Having said all that, I am willing to try it, in the worst case we can revert back to current behavior.

**Comment by bourdakos1** [comment]
> Now you made me much more confused. So, if we add the lock, we will be using a set of locked dependencies that might all work ok,

yes, we would be using a locked set of dependencies, that if worked okay when installed, will always work okay for developers of Elyra

> instead of using the latest dependencies that would be what a user sees when they install Elyra? 

Even without locking our dependencies, the "latest" versions at development time might not match the "latest" versions when the user actually installs Elyra

> This will make our life easy,

Yes, it will make our lives and contributors lives easier

> and hide us from issues that we could have fixed to make users life easier?

Not necessarily, as mentioned above, the majority of these issues are only _build_ time issues. Runtime dependency issues happen much much less frequently. 

> I just want to make sure this don't become something like the canvas updates, where if we update frequently we just have to fix a few css issues

I think this is a separate issue from the lockfile? Do you mean when we don't have a lockfile we are forced to keep up-to-date more often? I think the answer to this is to have a release checklist where we bump any packages we want to keep up-to-date before releasing. Or is the concern that canvas updates css frequently and would cause see bugs on the user end? If this is the case we should lock canvas down to the patch and try to update it for every release.

As kevin mentioned, the lockfile will give us a set of dependencies that we know elyra works with, which can be extremely helpful for debugging any issues that do pop up.
