### ISSUE TITLE
Runtime Metadata - Should we have a Kubernetes section?

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1576]
**Describe the issue**
In Runtime Metadata, should we actually separate the `COS Secret` into a `Kubernetes` section or collocate it together with the `COS` section where it is really related to? 

See image below:
![image](https://user-images.githubusercontent.com/382917/114960674-5f4bad00-9e1c-11eb-9967-638b9c5d575f.png)

**Comment by kevin-bates** [comment]
I thought this came up during https://github.com/elyra-ai/elyra/pull/1529#discussion_r608886396?  

I can see both sides of the issue but think it's fine.  Perhaps the title could be updated with `Kubernetes`?  (I think a bigger issue is having to enter the same creds twice and differently.)

I'm assuming the set of k8s entries is going to grow (volume mounts, config maps?) and I think we'd want to have such a section (if we were to remove the section now).  Then, since this _is_ a Kubernetes object, I think it would need to move back into the Kubernetes section.   I suppose one could make an argument for moving kfp's user-namespace property into this section as well.

@lresende, I take it you don't agree? :smile:
