### ISSUE TITLE
Add support for Kubeflow 1.3.x+ 

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1583]
**Is your feature request related to a problem? Please describe.**
Elyra should support the latest release of Kubeflow: https://github.com/kubeflow/kubeflow/blob/master/ROADMAP.md#kubeflow-13-features-target-release-march-2021

**Describe the solution you'd like**

- [x] Validate that pipelines run as expected on KFP
- [x] Validate that pipelines run as expected on KFP/OpenShift
- [x] Determine whether/which documentation updates are required
- [x] Validate that the `elyra/kf-notebook` image still works as expected as a Kubeflow Notebook server
- [x] Bump `kfp` dependency to `1.4.0` and `kfp-tekton` `0.7.0` OR

**Comment by ptitzler** [comment]
> Bump kfp dependency to 1.4.0 and kfp-tekton 0.7.0

https://github.com/elyra-ai/elyra/pull/1622

**Comment by ptitzler** [comment]
> Determine whether/which documentation updates are required

https://github.com/elyra-ai/elyra/pull/1635

**Comment by ptitzler** [comment]
> Determine whether/which documentation updates are required

https://github.com/elyra-ai/elyra/pull/1641

**Comment by DavidSpek** [comment]
Just thought I'd let you know the latest version of `kfp` is 1.6.2, and the latest `kfp-server-api` is 1.5.0. The requirements for `kubernetes` should also be bumped to include version 12.0.1 to avoid conflicts with the kfserving package. I also noticed `jupyterlab-git` is being downgraded fro, 0.30.1 to 0.30.0 and `nbconvert` from 6.0.7 to 5.6.1 along with a few other packages.

I can highly recommend setting up [Renovate](https://github.com/marketplace/renovate) for the repository so that it can automatically create PRs to update the requirements. Kubeflow Pipelines is already using it, and the notebooks working group will follow shortly once the repo situation is sorted.

**Comment by ptitzler** [comment]
Deferring `kfp` upgrade (`>1.4.0`) until a version of `kfp-tekton` is published that supports version `1.6.x` or above. `kfp-tekton 0.8.0` requires version `1.5.0`, which is not officially published - but `1.6.x` is.

**Comment by akchinSTC** [comment]
since kf 1.3 skipped the 1.5.0 release of the SDK, do we need this last checkbox? I think a bump to 1.4.1 is warranted though since kf 1.3 is tagged to it right?

**Comment by ptitzler** [comment]
> since kf 1.3 skipped the 1.5.0 release of the SDK, do we need this last checkbox? 

I removed it.

> I think a bump to 1.4.1 is warranted though since kf 1.3 is tagged to it right?
There's no 1.4.1 https://pypi.org/project/kfp/#history. We are waiting for the `kfp-tekton` folks to support `kfp` 1.6+

**Comment by akchinSTC** [comment]
RE 1.4.1, my mistake that was a rc that never made it to release.
