### ISSUE TITLE
Add support for volumes to streamline data exchange 

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1586]
**Is your feature request related to a problem? Please describe.**
As a pipeline user, I would like to have the ability to optionally define a data  volume that is available when a node is processed. Example workflow:
- user defines a data volume in the Kubernetes cluster
- user adds data volume to Elyra runtime configuration
- user creates notebooks | scripts that operate on the files stored in this volume
- pipelines that are executed with this configuration can now store/access data without the need for the data to be uploaded to/downloaded from COS

Users could also mount the volume in a KF notebook server running in the same Kubernetes cluster and consume the output of a pipeline run interactively. Applications running in the cluster could also access this data  programatically.

**Describe the solution you'd like**
- Runtime configuration schema is extended to include optionally a data volume property
- The volume metadata is attached to the container, making the file system available at runtime.

**Comment by lresende** [comment]
Same or similar to #578

**Comment by tomdurrant** [comment]
I would love to see this feature

**Comment by thesuperzapper** [comment]
@ptitzler @lresende @tomdurrant have made a proposal in https://github.com/elyra-ai/elyra/issues/2528 to implement a "bounding box" approach for mounting volumes to multiple steps in a pipeline:

![image](https://user-images.githubusercontent.com/5735406/156528184-8d11482d-e05e-48f9-91b8-bbe27fcb1173.png)

**Comment by thesuperzapper** [comment]
@ptitzler @lresende I really think we should prioritize volume mounting in KFP for the next release, because without it:
 1. using large datasets with Elyra is impossible (you will probably exceed the Node's emptyDir size limit)
 2. there is no way to carry local files between steps 
      - (NOTE: this applies to "KFP component" steps, not "Notebook" steps which can use the COS store with "output files")

----

Obviously, adding a UI as I proposed in https://github.com/elyra-ai/elyra/issues/1586#issuecomment-1057807096 will take a while, but I think we can get a "global" volume mount feature in relatively quickly by either:
1.  doing what is proposed in this issue, and extending the "runtime" config with volume mounts 
     - (NOTE: I am against this idea, as it makes pipelines NOT portable between all KUBEFLOW_PIPELINES runtimes)
2. adding a new section to the "pipeline properties" menu which configures "volumes" to be mounted to ALL steps

What are your thoughts on adding a "volumes" section to the "pipeline properties" menu?

**Comment by kevin-bates** [comment]
I think I agree with you but wanted to get some additional information.
> it makes pipelines NOT portable between all KUBEFLOW_PIPELINES runtimes

Just checking terminology.  By _KUBEFLOW_PIPELINES runtimes_ do you mean runtime metadata instances where some instances may have volumes specified while others not?  Thus, the given pipeline would fail (and likely in a non-detected manner until its sent to KFP) when submitted with a runtime configuration that doesn't include the necessary volumes.

Can you enumerate what attributes would need to be persisted to specify a volume?  This may help with things.  If credentials of any sort are required, then it seems we break a _pipeline's_ portability by specifying the complete values in the pipeline.

Or perhaps a hybrid approach where the pipeline (and node) properties _reference_ a named volume and the submit validation ensures that those referenced volumes exist in whichever runtime configuration is selected.
