### ISSUE TITLE
elyra vs elyra-server package

### ISSUE THREAD

**Issue by mhlr** [elyra-ai/elyra#1587]
Both conda & pip have both elyra & elyra-server packages. On conda they seem independent, neither tries to install the other. What is the difference? How do they relate? Which should be installed when? Should both be installed?

**Comment by akchinSTC** [comment]
> If you install elyra all dependencies should be pulled in.
✅ 

> elyra-server is common code that the individual extensions depend on and there should not be a need to install this package explicitly
✅ 

The following "elyra extension" packages each require the `elyra-server` package for installation. These are for folks who want to use parts of elyra but don't need the whole suite.
```
elyra-pipeline-editor extension
elyra-python-editor-extension
elyra-r-editor-extension
elyra-code-snippet-extension
```

**Comment by ptitzler** [comment]
For illustrative purposes I confirmed  that a conda install of  `elyra-python-editor-extension` pulls in `elyra-server` as expected:
```
$conda install -c conda-forge elyra-python-editor-extension && jupyter lab build
 ...
$ pip list | grep elyra
elyra-python-editor-extension 2.2.2
elyra-server                  2.2.2
```

The [existing conda installation instructions](https://elyra.readthedocs.io/en/latest/getting_started/installation.html#conda) should therefore be sufficient because no additional installation is required.

**Comment by ptitzler** [comment]
Since I am not a maintainer of the packages on PyPI/conda-forge I am unable to update the descriptions and unassigning myself from this issue.

**Comment by lresende** [comment]
@akchinSTC can easily add you to conda
