### ISSUE TITLE
Add pipeline properties

### ISSUE THREAD

**Issue by marthacryan** [elyra-ai/elyra#1699]
The pipeline editor should have the ability to add properties for an *entire pipeline* rather than just for *single nodes*.

Examples include: 
- Pipeline description
- Environment variables that apply to all nodes
- default runtime image
- ~~[not yet supported] mounted volumes~~
- ~~UI variables such as font size~~

Proposition for UI to edit these properties: add an additional tab into the right side pane, and the appearance of the editor would otherwise be similar to the node properties editor. 

Proposition for the definition of pipeline properties: same format as the node properties JSON (with adjustments as needed)

Thoughts on either design or additional properties that could be added? 

This supersedes the following issues: #602 #1421

**Comment by bourdakos1** [comment]
This sounds good to me 👍 

The only thing is that I don't think UI specific items like font size should be included in these properties

**Comment by ptitzler** [comment]
- default runtime image
- [not yet supported] mounted volumes

**Comment by kevin-bates** [comment]
Thanks for opening this @marthacryan - I agree this is something we've needed.

One of the items we've also talked about previously is a _project_ or _workspace_ scoping mechanism.  I'm not saying we need to explode this to include that, but I think having a string-valued property to reflect this idea might be useful and could be retrofitted to such a model.  This has also been suggested [here (via `my_storage`)](https://github.com/elyra-ai/elyra/discussions/1686#discussioncomment-778807) and I'm thinking the server could utilize this property's value (if present) to introduce that additional level that would then lead to more organizational uses.

**Comment by bourdakos1** [comment]
@kevin-bates for project/workspace settings, would this be something personal? or intended for sharing?

Will we eventually want tiers of settings?
- system wide global settings (applies to every pipeline on the system, not really shareable)
- workspace settings (applies to every pipeline in the workspace, can be optionally shared)
- pipeline settings (baked into the pipeline file itself)

Would all of these scopes of settings have the same settings available? I guess things like pipeline metadata (title, description) would only be available in the baked in settings

Maybe we should only allow metadata to be baked into the pipeline file and leave default properties to global/workspace settings to avoid confusion?

**Comment by kevin-bates** [comment]
I haven't given much thought to a tier above project/workspace (e.g., system-wide settings).  Ideally, the _owner_ of the project/workspace would be up to how the user/admin wishes to configure things from a sharing perspective.  I think the comment that I referenced previously (regarding `my_storage`) makes a lot of sense and we should provide some aspect of that.

I agree that settings beyond/above pipeline settings (i.e., project/workspace) should probably come from another location.  That is why I made my _explode this to include that_ comment since designing a persistence model for that is a whole other set of tasks.  However, I do think we could introduce a semantically equivalent property into the pipeline settings which has such a connotation since we'd need some sort of referential relationship to connect the "tiers".  Since pipeline-to-workspace is many-to-one, it makes sense to have the pipeline reference the workspace.

If are hesitant about this _partial introduction_ of project/workspace, we could simply introduce a pipeline property specific to this use-case: `storage_root` or something like that, such that, when set, the server injects this value between the bucket name and the elyra-run-id value.

**Comment by marthacryan** [comment]
Readonly property ideas:
- Name
- Pipeline type

**Comment by ptitzler** [comment]
I guess these  are questions for all properties that override node properties.

From a UI perspective, [how] would setting the runtime image in the _pipeline properties_ be reflected in the node properties display? 

If a global value is configured, would the value be _visually_ pre-selected in the node properties?

**Comment by bourdakos1** [comment]
@ptitzler I wouldn't think they would show in the setting editor, but would show the resolved properties when hovering over the node? and we could add some kind of indicator of where the setting is coming from

**Comment by bourdakos1** [comment]
Yea, definitely agree with the `use pipeline default` idea for the runtime image

For the environment variables, we also need to make it clear that the pipeline level env_vars will only override the node env_vars at the key level, right?

For example:
```
pipeline properties:
ONE=111
THREE=3

node properties:
ONE=1
TWO=2

will result in:
ONE=111
TWO=2
THREE=3


NOT:
ONE=111
THREE=3
```

I think this gives more weight to @kevin-bates argument to switch to a key/value pair instead of a string array. This way env_vars won't be a special case

**Comment by kevin-bates** [comment]
Hmm - I would have said the result would be:

ONE=1
TWO=2
THREE=3

Since ONE was already defined on the node.

**Comment by ptitzler** [comment]
Yes, I'm with 1,2,3.

**Comment by bourdakos1** [comment]
oh yea, sorry I did that completely backwards haha

**Comment by ptitzler** [comment]
Irrespective of how env variables are rendered (`A=a` or two input boxes), if a user specifies an environment variable but assigns no value ("`A=`"), what should happen?

**Comment by kevin-bates** [comment]
My thought: 
If 'A' is defined as a pipeline property, it will override 'A=' on the node.  (Pipeline property envs should require values.)
If there is no override and 'A=' is submitted to the server, it will be _excluded_ from the set of envs available to the runtime.

Since we're all in agreement relative to the override behavior,  I've gone ahead and updated the "scenario comment" so that the previous comments (following the scenario) make sense - otherwise, folks reading this will still be confused.  I hope that's okay.
