### ISSUE TITLE
install doc (et al): replace all mentions of `pip` with `pip3`

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1709]
**Is your feature request related to a problem? Please describe.**
The `pip` command isn't necessarily pointing to a python 3 binary. To avoid any issues, we should update the documentation to use `pip3` instead of `pip` in example commands:
- `README.md`
- `developer_guide/development_workflow.md`
- `getting_started/installation.md`
- `recipes/creating-a-custom-runtime-image.md`

**Describe the solution you'd like**

`s/pip/pip3/g`

**Comment by mudspringhiker** [comment]
I can take this one. :-)

**Comment by mudspringhiker** [comment]
hi @ptitzler, for `developer_guide/development_workflow.md`, since the active conda environment is already pointing to Python 3, do we still need to change the `pip` command to `pip3`?

![Screen Shot 2021-06-01 at 12 42 57 PM](https://user-images.githubusercontent.com/17956412/120367843-f8ecf200-c2d6-11eb-9805-3c6f367933e6.png)

**Comment by mudspringhiker** [comment]
Done.
