### ISSUE TITLE
Argo vs Tekton

### ISSUE THREAD

**Issue by blublinsky** [elyra-ai/elyra#1725]
**Describe the issue**
It looks like Kubeflow pipelines have different installs for Argo and Tekton. Elyra run command allows to configure me either without considering this. May be put this in documentation and improve error handling to explicitly say this 

**To Reproduce**
1. Install kubeflow pipelines with Argo
2. Configure execution as Tekton
3. See error

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
HTTP response body: {"error_message":"Error creating pipeline version: Create pipeline version failed: Failed to get parameters from the workflow: Invalid input error: Unsupported argo version. Expected: argoproj.io/v1alpha1. Received: tekton.dev/v1beta1","error_details":"Error creating pipeline version: Create pipeline version failed: Failed to get parameters from the workflow: Invalid input error: Unsupported argo version. Expected: argoproj.io/v1alpha1. Received: tekton.dev/v1beta1"}
</pre>
</details>

**Expected behavior**
You can kinda guess from the error, but it wold be nice to see something like:
Your pipeline is installed with Argo. If you want to use Tekton, reinstall it following https://github.com/kubeflow/kfp-tekton/blob/master/guides/kfp_tekton_install.md#standalone-kubeflow-pipelines-with-tekton-backend-deployment
**Deployment information**
Describe what you've deployed and how:
 - Elyra version: latest
 - Operating system: any
 - Installation source: any
 - Deployment type: any Kubeflow pipelines install

**Comment by ptitzler** [comment]
Unfortunately there is no straightforward way for KF clients to determine which workflow engine is installed. Therefore we've added instructions on [how to do this manually to the runtime configuration topic](https://elyra.readthedocs.io/en/latest/user_guide/runtime-conf.html#kubeflow-pipelines-engine-engine)

As far as handling the error more gracefully during pipeline execution, we could probably parse the generic error message that KF returns, but that would be more of a band aid since the message wording could change at any time (and break this).
