### ISSUE TITLE
File Browser always displays generic pipeline icon

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1849]
**Describe the issue**

1. Create a typed pipeline
1. Review the file entry icon in the file browser
   ![image](https://user-images.githubusercontent.com/13068832/123700736-b525d380-d815-11eb-93fd-5b2172d70ed0.png)

Would it be possible to display the appropriate icon for typed (kfp/aa) pipelines without incurring a performance hit? Since we are using the currently displayed icon to indicate generic pipelines the current display is misleading.

**Comment by ajbozarth** [comment]
I don't believe this would be possible without changing how we handle typed pipelines. The icon in the file browser is associated with file extensions, so unless we use unique extensions for each pipeline type then we are unable to do this in jupyterlab. If you want to discuss using unique extensions to solve this (among other issues) then feel free to leave this open, otherwise we should close this as can not fix

**Comment by kevin-bates** [comment]
Seems like we could easily set a "type" indicator in the pipeline metadata of the pipeline file and just use that - is that right?
The existing pipelines that don't reference this new field could display the generic icon but we could also have the validation service detect the type and return that in its response such that the next save of the pipeline updates its 'type' field (rather than bump the version and handle this via migration).

**Comment by ajbozarth** [comment]
The icon shown in the file browser is determined by a fileType entry in the docRegistry. A fileType associates a list of extensions with an icon and name. Then an extension factory is associated with a list of fileType to determine which extension that file can be opened "in." Based on this limitation, a single file extension can only be associated with a single icon, without any input of the content of that file.

**Comment by kevin-bates** [comment]
Thanks Alex.  I didn't realize that this area was not privy to application-level functionality and so constrained.  I was also thinking that this determination was more associated with working with the file, but now (after your two responses :smile:) see that this is only about the display within the file list  - I should have read things more carefully
