### ISSUE TITLE
Pipeline persists 'invalidNodeError'

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1915]
**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
1. Create a [generic] pipeline
2. Add a component that requires at least one input
3. Observe validation error (expected)
4. Fix issue + save pipeline
5. Open `.pipeline` file and search for `invalidNodeError`.

```
"invalidNodeError": "property \"Filename\" is required\nproperty \"Runtime Image\" is required"
```

This is an issue because the pipeline is no longer invalid.

**Comment by ptitzler** [comment]
General question: should the error be persisted at all even if it is still valid? 
- afaik there is no downstream consumer that utilizes the property
- the pipeline editor/cli validates the pipeline when the file is loaded

**Comment by bourdakos1** [comment]
yea we have an issue and PR (that will need to be redone) open on the pipeline-editor project for this: 
- https://github.com/elyra-ai/pipeline-editor/issues/64
- https://github.com/elyra-ai/pipeline-editor/pull/79

The property can be safely deleted by the user, because it is recreated/deleted on the fly
