### ISSUE TITLE
Install elyra-pipeline-editor-extension without downgrading jupyterlab-git and nbconvert?

### ISSUE THREAD

**Issue by krassowski** [elyra-ai/elyra#1959]
**Describe the issue**

I tried to install `elyra-pipeline-editor-extension` from PyPI in my environment, already having `jupyterlab-git` in version 0.31 installed, nbconvert `6.0.7`, and `jinja2` 3.x, however `elyra-server` seems to have pinned requirements resulting in downgrade of those packages. The downgrade of `jupyterlab-git` and `nbconvert` is an inconvenience. I can imagine that `nbconvert` might be used somewhere, but is `jupyterlab-git` needed for pipeline-editor alone (maybe it is, I don't know)?

**To Reproduce**

```
pip install -U jupyterlab-git
pip install elyra-pipeline-editor-extension
```

See the latter downgrade git extension.

**Expected behavior**
I would like to be able to use the latest version of `jupyterlab-git` always. It would be perfect if the recent `nbcovert` would be supported too.

**Deployment information**
 - Elyra version: 2.2.4
 - Operating system: Ubuntu
 - Installation source: PyPI
 - Deployment type: local installation

PS. heads up: planning to cut a new release of LSP this week.

**Comment by lresende** [comment]
Thanks for the feedback @krassowski. I believe this was a moment in time were close to 2.2.4 we were seeing some issues due to quick updates on dependencies. We have most of this fixed in master for our next release which should be coming up in about a week or so. The question is, could you wait for our 3.0 release? Otherwise, we could come up with a quick patch release to solve this.

**Comment by krassowski** [comment]
Sure, I can wait!
