### ISSUE TITLE
Error executing notebook using "run notebook using papermill" kfp component

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1967]
**Describe the issue**
Error executing notebook using "run notebook using papermill" kfp component

![image](https://user-images.githubusercontent.com/382917/127157010-3ebc0b75-75d9-4122-8184-dfb9b8c11326.png)

![image](https://user-images.githubusercontent.com/382917/127156899-0440558f-bde1-40c6-bc94-dd99bfb6d4a6.png)

**Comment by ptitzler** [comment]
perhaps caused by the packages "list", which is not a JSON array?

**Comment by lresende** [comment]
@ptitzler looking at the logs it seems that the `packages_to_install` seem to be processed properly independent of that being a json array or not. 

After using a pipeline + notebook both in the root directory of the jupyterlab workspace then I was able to get it to run. Also, I had to use a helloworld notebook example as other more complex ones were giving me some parsing issues as well. 

The strange thing is that it works when using the `generic notebook component`. Could it be related to papermill/notebook dependencies on the image being used?

**Comment by ptitzler** [comment]
I see. The component uses a bunch of regular expressions to "extract" package names from the provided string. Which notebook did not work for you?

**Comment by lresende** [comment]
This works:
[helloworld.ipynb.zip](https://github.com/elyra-ai/elyra/files/6886978/helloworld.ipynb.zip)

This (and a few more complex ones) does not:
[python-linregr-least-squares-fit.ipynb.zip](https://github.com/elyra-ai/elyra/files/6886980/python-linregr-least-squares-fit.ipynb.zip)

**Comment by kiersten-stokes** [comment]
After looking into this issue, I think it's almost three separate parts.

1. As Patrick mentioned, this component is finicky and somewhat cryptic in the description of its properties and how values must be entered. We'll definitely want to document that. Also related is that a notebook that needs to read a file or otherwise process input will not succeed until we support data exchange (e.g. `consumer.ipynb`)
2. There is, however, a bug with how we process a property of type `list`. The pipeline JSON will contain, for a `list` property value, something like `"['elem1', 'elem2']"`, which will have to be converted using a `literal_eval()` to its true list format, e.g. `['elem1', 'elem2']`. This is what we do with dictionary objects already. I've opened the following issue to address this: #1977
3. We aren't currently handling relative paths properly for components with a property of type `file`. For generic notebook and script execution, the relative paths are calculated on the frontend before being sent to the backend for processing. We will want to do the same for any file-based property in the runtime-specific components as well.

**Comment by bourdakos1** [comment]
> There is, however, a bug with how we process a property of type list. The pipeline JSON will contain, for a list property value, something like "['elem1', 'elem2']", which will have to be converted using a literal_eval() to its true list format, e.g. ['elem1', 'elem2']. This is what we do with dictionary objects already. I've opened the following issue to address this: List-type properties for KFP runtime-specific components are not evaluated correctly #1977

If the property is a list you can use the array component to get a JSON array back instead of a string
