### ISSUE TITLE
Investigate local copy of operator and remote operator alignment in Apache Airflow

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#2008]
**Describe the issue**
When defining an operator locally for Airflow, the operator arguments, HAVE to be aligned and the same as the operator being used in the deployment. So any "customizations" will need to fit within the confines of the source operator class definition in the airflow deployment or be included in the DAG itself. 
This presents issues when the user doesn't have the correct argument requirements of the operator on the deployment resulting in a failed run. 
Looking for input on the best way to address this

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: [3.0.0]

**Comment by ptitzler** [comment]
> This presents issues when the user doesn't have the correct argument requirements of the operator 

With the release of the [Airflow catalog connectors](https://elyra.readthedocs.io/en/latest/user_guide/pipeline-components.html#apache-airflow-package-catalog) users can "import" operators that are installed in their runtime environment. As long as users "import" the correct version of the Airflow package or provider package using these connectors there should be no discrepancy between the operator signature that the pipeline editor uses and the actual signature in the target environment.
Please re-open with clarification if this does not sufficiently address the root cause of this issue.
