### ISSUE TITLE
Metadata Editor and CLI should block whitespace only tags

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#2019]
**Describe the issue**
Metadata Editor allows whitespace only strings as a valid tag
![image](https://user-images.githubusercontent.com/25207344/128399261-c6f1d7c9-9328-4b87-913b-bae4159b44d4.png)

Similarly, when [creating a metadata using CLI ](https://elyra.readthedocs.io/en/latest/user_guide/code-snippets.html#id1), tags can are also accepted as whitespace only.

Apparently leading/trailing whitespaces are already cleaned up in the UI.

**To Reproduce**
Steps to reproduce the behavior in the UI:
1. Create new or edit a metadata (code snippets, runtime, runtime image)
2. Add a tag containing only white spaces
3. Save & close
4. Check the metadata widget tag filter

Steps to reproduce the behavior in CLI:
1. Create new metadata (eg. code-snippet) and add a whitespace or empty string tag
```
elyra-metadata install code-snippets \
	--display_name="Preview DataFrame" \
	--description="Preview Pandas DataFrame" \
	--tags="['Python', 'Pandas', '  ', '']" \
	--language="Python" \
	--code="['df.head(5)']"
```
2. Check the json file just created containing whitespace/empty string tags

**Expected behavior**
UI - The editor should discard/flag whitespace only tags.
CLI - Metadata service should validate whitespace/empty string tags.

**Context information**
 - Elyra version: 3.0.0
 - Operating system: macos
 - Browser: Chrome

**Comment by samali0996** [comment]
I'm interested in working on this issue!

**Comment by JoshuaAlter** [comment]
Im also interested!

**Comment by kevin-bates** [comment]
Hello @samali0996 and @JoshuaAlter - thank you for your interest.  I just saw this issue and would like to point out that the majority of this issue should be addressed via JSON schema and not in the `CLI` tooling itself since the CLI is completely schema-driven.  I suspect the same might be true for the front-end, but I'm not familiar with that (cc: @marthacryan).

I just don't want folks spending time trying to implement this in a manner that we've made an architectural decision not to do and that may seem counter-intuitive as to how one might expect to approach this kind of change.  I have a schema snippet that would resolve this, but given the interest in helping, I'd be happy to let others have a go at it and will be happy to assist in any manner.

When working with JSON schema, I find the following tool invaluable: https://www.jsonschemavalidator.net/

You can dump the applicable schema into the left-hand pane and enter the instance data in the right and it performs schema validation on the fly.

**Comment by marthacryan** [comment]
Hi @samali0996 and @JoshuaAlter - there's going to be a huge refactor of the metadata editor coming up that would end up removing the work you'd be doing to fix this so it's probably best to choose a different issue. Thanks!
