### ISSUE TITLE
Provide abstraction layer for manipulating pipeline definition (json) files in Elyra source code

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2067]
**Is your feature request related to a problem? Please describe.**
Currently client code (in the broader sense), e.g. `elyra-pipeline`, has to manually traverse the json structures in `.pipeline` files, which may change over time. 

There are a several drawbacks to not having an abstraction for the pipeline definition file:
- Logic is duplicated in multiple places
- Maintenance is hard as code is duplicated
- Susceptibility to bugs as corner cases logic needs to be considered by multiple consumers
- etc

**Describe the solution you'd like**

To avoid duplication of this kind of code and reduce the maintenance effort, Elyra should provide class to properly retrieve fields from the pipeline definition json structure. 

Example:

Instead of:

```
for pipeline in pipeline_definition["pipelines"]:
    if pipeline['id'] == primary_pipeline_key:
        primary_pipeline = pipeline

primary_pipeline["app_data"]["version"]
```

Have something like:

```
pipeline_definition.get_field("version")
```
or
```
pipeline_definition.version
```

In the case above, the logic would have to handle things like finding the primary pipeline, validating the `app_data` structure is available, validate `field name` is available and retrieve its value.

Possible operations to abstract:
- Discover primary pipeline
- isEmpty
- get pipeline field
- get node (name/id) field
- etc

Possible consumers:
- Pipeline CLI
- Pipeline Validation service

Note that, this is to be used on preliminary areas that the existing [Pipeline Parser](https://github.com/elyra-ai/elyra/blob/31c3816acbfe41737ef5a2f0627c90419175f0a6/elyra/pipeline/parser.py#L30) and [Pipeline value object](https://github.com/elyra-ai/elyra/blob/31c3816acbfe41737ef5a2f0627c90419175f0a6/elyra/pipeline/pipeline.py#L305) can't be used. So, not a lot of logic and assumptions should be in this abstraction layer to avoid duplication with the Pipeline parser/value object.

**Comment by kevin-bates** [comment]
One approach for this may be to use [`SimpleNamespace`](https://docs.python.org/3/library/types.html#types.SimpleNamespace).  To apply `SimpleNamespace` recursively (for embedded dictionaries) I found this SO link: https://stackoverflow.com/questions/50490856/creating-a-namespace-with-a-dict-of-dicts

```python

# From StackOverflow: https://stackoverflow.com/questions/50490856/creating-a-namespace-with-a-dict-of-dicts
def dict_to_sns(d: dict) -> SimpleNamespace:
    return SimpleNamespace(**d)

def pipeline_to_object(pipeline: dict) -> SimpleNamespace:
    # Convert to string so we can re-load using hook to convert dictionaries to SimpleNamespace instances
    pipeline_str = json.dumps(pipeline)
    pipeline_sn = json.loads(pipeline_str, object_hook=dict_to_sns)
    return pipeline_sn
```

For example, given the pipeline https://github.com/elyra-ai/examples/blob/master/pipelines/kubeflow_pipelines_component_examples/run_notebook_component/run_notebook_using_papermill.pipeline and saved to file `run_notebook_using_papermill.pipeline` run 

```python
with open(pipeline_abs_path) as f:
    pipeline_definition = json.load(f)
```
to get a pipeline_definition based on dictionaries - which is the form used within the server. This could then be converted to "object form" using `pipeline_to_object`:
```python
pd = pipeline_to_object(pipeline_definition)
```
This will convert all dictionaries to SimpleNamespaces, enabling navigation sans dictionary keys:
<img width="906" alt="Screen Shot 2021-08-20 at 11 58 31 AM" src="https://user-images.githubusercontent.com/22599560/130282255-cbb6b4d2-8c16-48d6-8153-a5d8410bc93f.png">

However, this approach doesn't give any kind of IntelliSense capabilities, so one would need to know the structure in order to access lower-level "keys".  I believe if IntelliSense functionality was required, you'd have to build a full python object that models the structure and requires updates whenever changes are made.  This approach would probably leave some areas dictionaries that are never accessed within the server (which isn't necessarily a bad thing).

At any rate, food for thought.

**Comment by lresende** [comment]
Interesting.. 

But, won't you have the same issue if you SimpleNamespace and try to access a children's property where the parent is missing? 

E.g. `primary_pipeline["app_data"]["version"]` --> `primary_pipeline.app_data.version` -> but app_data is missing?

**Comment by kevin-bates** [comment]
Yes - that would be true.  Wouldn't that condition exist no matter what approach was taken?  I guess I was assuming a pipeline (dict) would only be converted to an object following successful validation.  (Perhaps it's the validation that renders the object-valued pipeline?) 

I don't have any issues with other approaches although I would guess that a tightly-coupled approach (i.e., one in which all dictionary keys are represented as python methods or properties and that representation occurs for each embedded dictionary - which would require other class definitions, etc.) is going to be difficult to maintain.

Rereading this issue, it sounds like it is requesting a more abstract approach that even the validation service uses (which seems odd to me) where structures like `app_data` and (probably to some extent) `ui_data` are hidden - so the SimpleNamespace is not sufficient. I'm curious what the expected representation of a node would be in this case.  Or is the idea that **all** accessors (including those for node-based properties) are on the "wrapping" object and all node-based properties must take both a pipeline id and a node id (since a pipeline definition can have multiple pipelines, each with multiple nodes)?  That is, there is only one object that represents the entire pipeline definition (including their nodes).

We do already have in [`Pipeline`](https://github.com/elyra-ai/elyra/blob/35696cedf69a73b5f53dad1385ab9795dd83cbfe/elyra/pipeline/pipeline.py#L305) and [`Operator`](https://github.com/elyra-ai/elyra/blob/35696cedf69a73b5f53dad1385ab9795dd83cbfe/elyra/pipeline/pipeline.py#L25) (for nodes).  However,  I suspect we're going to end up with another set of similar classes because `Pipeline` and `Operator` are too far down the "execution" path and not adjacent to the raw pipeline definition (i.e., we build these instances too late in the game) - which is unfortunate.

**Comment by lresende** [comment]
> Yes - that would be true. Wouldn't that condition exist no matter what approach was taken? I guess I was assuming a pipeline (dict) would only be converted to an object following successful validation. (Perhaps it's the validation that renders the object-valued pipeline?)

Yes, this would be a quick/simple helper before validating/parsing. After this, the existing parser and value objects can be used. 

> Rereading this issue, it sounds like it is requesting a more abstract approach that even the validation service uses (which seems odd to me) where structures like app_data and (probably to some extent) ui_data are hidden

Yes, it would probably also be useful for the validation service to eliminate codes like the one below
```
 # Get Node Label
                    if node['app_data'].get('ui_data'):  # If present, always the source of truth
                        node_label = node['app_data']['ui_data'].get('label')
```

**Comment by kevin-bates** [comment]
>> Yes - that would be true. Wouldn't that condition exist no matter what approach was taken? I guess I was assuming a pipeline (dict) would only be converted to an object following successful validation. (Perhaps it's the validation that renders the object-valued pipeline?)

> Yes, this would be a quick/simple helper before validating/parsing. After this, the existing parser and value objects can be used.

Hmm - we're saying opposite things but at least I understand you're talking about a facade pattern (so the `SimpleNamespace` approach should be discarded).  

I thought the idea was that this facade object would be used _following_ validation.  IMO, validation must use the raw dictionary since its entire purpose is to validate the _structure_ of the pipeline.  But if this object is meant to be used with non-validated pipeline definitions, validation would/should still need to decipher areas of the pipeline definition that are potentially _masked_ by this facade for it to complete its task. Is the idea that if the pipeline is invalid, nothing else will use the facade since processing will essentially stop and, therefore, any uses of this facade by areas outside of validation will be operating on valid pipelines?  I suppose that's reasonable, provided that validation isn't _wrongly influenced_ by something the facade is masking.

The Parser uses its [own set of helpers](https://github.com/elyra-ai/elyra/blob/master/elyra/pipeline/parser.py#L113-L214), which I suppose would be replaced by this facade object (and potentially used within the object).

This might be helpful to whoever implements this:
- With this approach, how do I access the _ith_ node of a pipeline (supernodes and multiple pipelines should probably be considered also), and what is returned?  
- How do I access the _ith_ node's `component_parameters`, and what is returned?
