### ISSUE TITLE
Pipeline Editor doesn't pick up last change to ui_data.label value

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2072]
**Describe the issue**

- [ ] Publish pipeline editor package with the closed PR to include in Elyra release

Noticed that this happens periodically (but not always)

![image](https://user-images.githubusercontent.com/13068832/130590519-401ee73b-1c68-404f-8ac0-0fe402bb8d90.png)

Content of raw `.pipeline` file notice truncation in `ui_data.label`:

```
            "label": "labeled-notebook-node",
            "ui_data": {
              "label": "labeled-notebook-nod",
              "image": 
```

**To Reproduce**

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
Paste the log output here.
</pre>
</details>

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.0/master

**Comment by marthacryan** [comment]
Just checked and looks like what's happening is that it's not picking up the last change that was made to the label, so if you go and move that node (or just make any unrelated change to the pipeline) it should update the field to be correct. I'm not entirely sure why this is happening but I wonder if it's related to what's referenced on this line: https://github.com/elyra-ai/pipeline-editor/blob/fe91779cfa26e1d191fe58453373ab51379afb34/packages/pipeline-editor/src/PipelineController/index.ts#L344. 

That said, this bug isn't actually affecting how the label is displayed because the label is also being stored in a different field

**Comment by akchinSTC** [comment]
@ajbozarth - needs review =)

**Comment by ptitzler** [comment]
Should remain open until the updated pipeline editor package is available and picked up by an Elyra build.
