### ISSUE TITLE
`Tags` metadata property not working properly for Component Registries

### ISSUE THREAD

**Issue by kiersten-stokes** [elyra-ai/elyra#2120]
**Describe the issue**
Now that the component registries have been migrated to be part of the metadata service, we are considering adding the `Tags` property similar to that which is used for code snippets and runtime images. When adding the `Tags` field to the schema for the `component-registries` schemaspace, the implementation of the tag feature isn't fully functioning on the frontend. Added tags disappear from the "tag viewer" in the `Pipeline Components` lefthand panel when attempting to click on them or when reloading the page.

This only occurs for the `component-registries` schemaspace. `Tags` in other schemaspaces are working as expected.

```json
"tags": {
  "title": "Tags",
  "description": "Tags for categorizing component registries",
  "type": "array",
  "uihints": {
    "field_type": "tags"
  }
},
```

**To Reproduce**
1. Add the above json snippet to the `metadata.properties` stanza in the `component-registry.json` schema in `elyra/metadata/schemas`
2. Rebuild and launch
3. Open a component registry and add a tag, then save & close
4. Go to the tag viewer in the `Pipeline Components` lefthand panel and try to click on a tag that appears or reload the pag
5.  All tags will disappear

**Deployment information**
Issue only occurs if adding the `Tags` field to the schema, but will appear on current master if that is the case.

**Comment by ptitzler** [comment]
[Side comment] Component catalog instances define the `category` property, which associate the catalog's components with the specified identifier(s):
 
![image](https://user-images.githubusercontent.com/13068832/152019208-90a510b3-d3ac-48e0-b3f6-ed3ad00d6140.png)

This grouping is visualized in the VPE's palette. If we were to support tags for component catalog instances, would we potentially create a usability issue because there are now two sorts of "tags"?
