### ISSUE TITLE
Validation tests fail due to possible race condition

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#2129]
**Describe the issue**
Three test_validation.py tests fail - primarily due to an assertion failure against the length of the issues list.  These do not occur when the test is run by itself, but if the test_handlers.py tests are run prior (within the same pytest invocation), then the len(issues) assertion is triggered. 

**To Reproduce**
1. Run `pytest elyra/pipeline/tests/test_handlers.py elyra/pipeline/tests/test_validation.py` from the elyra repo root.

**Screenshots or log output**
```
FAILED elyra/pipeline/tests/test_validation.py::test_invalid_runtime_node_kubeflow - assert 2 == 1
FAILED elyra/pipeline/tests/test_validation.py::test_invalid_runtime_node_kubeflow_with_supernode - assert 3 == 1
FAILED elyra/pipeline/tests/test_validation.py::test_missing_node_property_for_kubeflow_pipeline - KeyError: 'current_parameters'
```

**Expected behavior**
Tests should succeed and pass

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: master
 - Installation source: source
 - Deployment type: local
 - Operating system: macos

**Comment by kevin-bates** [comment]
This turns out to be more of an issue with:
1. Running the pipeline handlers tests prior to validation
2. Fixtures coming from jupyter server
3. Possible relation to caching and/or test destruction/termination

Since the pipeline handlers test needs to use the `fp_fetch` fixture and that fixture is dependent on a number of jupyter server fixtures, it (rightly) uses a temporary set of directories in which to access runtime data - including metadata instances.  However, the component registries will not exist in these environments since nothing populates these temporary directories with factory data.  As a result, the handler tests were influencing which components were available for downstream tests - and only producing the three generic components.

When the validation tests are invoked independently, they look for their factory component registries in the pip-installed location.  (Hmm, I suspect if you were to uninstall elyra and try to run directly from the repo, you'd get the validation tests to fail in a similar manner until elyra is installed.)

By creating a `setup_factory_data` fixture which copies the `etc/config/metadata` tree to the temporary directory that corresponds to JUPYTER_ENV_PATH (i.e., the system python env directory), both the handlers and validations run fine.

It's still unclear to me why this issue isn't showing up on CI.  It might be on a faster (or slower?) machine where less (or more) latency is present, so there might be something else worth looking into.

PR pending.
