### ISSUE TITLE
Enable async cache updates for component registry

### ISSUE THREAD

**Issue by kiersten-stokes** [elyra-ai/elyra#2162]
**Is your feature request related to a problem? Please describe.**
Currently the component cache is prompted to update 1. on cache expiry (5 minutes by default) and 2. any time a registry metadata instance is modified. The cache update in the former situation includes parsing of every component of every registry for that runtime type. As the number and size of the registries grow, this will become an issue.

**Describe the solution you'd like**
~~Use a watchdog handler so that the cache updates don't penalize the user operation that triggers the need for the update.~~ After investigating, it looks like a Watchdog cannot be used because it would conflict with the existing watchdog for Metadata linked below.

An alternative approach involves decoupling the component parser from the runtime processor. This would mean creating a registry cache updater thread that waits for update requests to be dropped into its queue by the metadata post-update hooks. This cache updater would be a Singleton class, modifying the existing `ComponentCatalog` class.

The cache updater should also make it possible to only update the components in the component registry instance that is being modified. This necessitates changing the structure of the component cache dictionary from a dictionary of `Component` instances indexed by their ids to a include the runtime type at the top level, followed by catalog name, followed by the dictionaries of `Component` instances indexed by their ids one level down.

This avoids the creation of a MetadataManager instance every time we need to figure out the catalog instances for a given runtime. It also avoids the need to get a processor from the `PipelineProcessorRegistry` when catalog metadata instances are touched.

This could allow us to get rid of the cache TTL, as the cache should always be up to date.

**Additional context**
~~See [here](https://github.com/elyra-ai/elyra/blob/master/elyra/metadata/storage.py#L149) for an example of an existing watchdog handler.~~

**Comment by kevin-bates** [comment]
@kiersten-stokes - thanks for opening this issue.

> The cache update includes parsing of every component of every registry for that runtime processor

When we do this, we should "plumb" a way to only update the cache entries relative to the updated registry rather than all registries for a given processor.  Perhaps this is as simple (at the API level) as conveying the component-registry metadata instance name to the `update_cache()` method and going from there.  This parameter could be optional, indicating a complete reload (across all component-registry instances) is warranted, rather than the specific registry's entries.

By the way, we're already penalizing every user request that happens to touch the registry after the 60-second TTL.  By using a watchdog, I suspect we could get rid of the TTL since I believe that exists in lieu of a watchdog mechanism.
