### ISSUE TITLE
Duration time showed wrongly for Python notebook after execution in pipeline

### ISSUE THREAD

**Issue by DatumWorld** [elyra-ai/elyra#2387]
**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
1. some code cells like bellow, and add the notebook to generic pipeline editor.
![image](https://user-images.githubusercontent.com/24842100/149056485-dc18bfe7-68b7-4073-b338-0c4363ba309a.png)
![image](https://user-images.githubusercontent.com/24842100/149056674-2d639944-d8a0-428e-a4fe-7fa93d4aed95.png)
2. Just run the pipeline, after its finish,reopen the Python notebook , the duration time show as in the above picture. 
3. If only run the Python notebook, the  duration time show like that  in the following  picture
![image](https://user-images.githubusercontent.com/24842100/149057319-a1b0c526-0f3f-4e50-aeaa-bf1e9aeddb11.png)
4. It shows right  duration time in R notebook.  
5. Is this bug or something I ignore?

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
Paste the log output here.
</pre>
</details>

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.4.0 
 - Operating system: windows 10 / 2019
 - Installation source: pip  in conda envs
 - Deployment type: local installation

**Pipeline runtime environment**
If the issue is related to pipeline execution, identify the environment where the pipeline is executed
 Local execution
 
**Runtime configuration settings**
As default

**Comment by kevin-bates** [comment]
Hi @DatumWorld - Some additional information that might help others and myself - please correct me if I'm wrong.

1. This functionality requires the `ExecuteTime` extension.  For lab, I believe that's https://github.com/deshaw/jupyterlab-execute-time
2. After installing the extension you need to enable the UI to display it via this comment from the [README](https://github.com/deshaw/jupyterlab-execute-time)
> Note: for this to show anything, you need to enable cell timing in the notebook via Settings->Advanced Settings Editor->Notebook: {"recordTiming": true}

@DatumWorld - please confirm this is what you're doing to enable this functionality.

Since notebook "nodes" are executed via Papermill and it looks like Papermill has its own means of capturing timings, [it sounds like this would require some additions to papermill](https://github.com/nteract/papermill/issues/133#issuecomment-546425852) in order to capture the proper metadata produced by `recordTiming=true`, but I'm not positive about that.  (See referenced issue)

**Comment by DatumWorld** [comment]
> Hi @DatumWorld - Some additional information that might help others and myself - please correct me if I'm wrong.
> 
> 1. This functionality requires the `ExecuteTime` extension.  For lab, I believe that's https://github.com/deshaw/jupyterlab-execute-time
> 2. After installing the extension you need to enable the UI to display it via this comment from the [README](https://github.com/deshaw/jupyterlab-execute-time)
> 
> > Note: for this to show anything, you need to enable cell timing in the notebook via Settings->Advanced Settings Editor->Notebook: {"recordTiming": true}
> 
> @DatumWorld - please confirm this is what you're doing to enable this functionality.
> 
> Since notebook "nodes" are executed via Papermill and it looks like Papermill has its own means of capturing timings, [it sounds like this would require some additions to papermill](https://github.com/nteract/papermill/issues/133#issuecomment-546425852) in order to capture the proper metadata produced by `recordTiming=true`, but I'm not positive about that. (See referenced issue)

Yes. Exactly.

**Comment by kevin-bates** [comment]
Closing.  To obtain appropriate timings in this scenario, `nbclient >= 0.5.11` is required (latest is `0.5.13`).
