### ISSUE TITLE
how to add jupyterlab_execute_time to the Dockerfile?

### ISSUE THREAD

**Issue by markqiu** [elyra-ai/elyra#2417]
I'm adding jupyterlab_execute_time by add a line in the end of the Dockerfile, but not work.

conda install jupyterlab_execute_time.

after installation, elyra extensions disappeared.

Any idea?

**Comment by kevin-bates** [comment]
A couple of things.

Please provide any output that is produced from your `docker build` along with your `Dockerfile` (or at least the minimally viable content to reproduce the issue).

I recently installed the extension to look into #2387, although not using docker.  The [jupyterlab-execute-time](https://github.com/deshaw/jupyterlab-execute-time) repo seems to prefer `pip install` over `conda install` and you should make sure you're using the `conda-forge` channel as the `defaults` channel will often lag months behind `conda-forge` (e.g., `conda install -c conda-forge jupyterlab_execute_time`).

Also note that you will encounter the issue described in #2387 until a new version (> 0.5.10) of `nbclient` is available since that will be the [carrier for the fix](https://github.com/jupyter/nbclient/pull/195) to #2387.

Have you confirmed the image works correctly with Elyra _prior_ to adding the execute-time extension?

**Comment by markqiu** [comment]
I solved it by adding the install line before the make install_all line. Like this:
`bash
cd /tmp/elyra
conda install jupyterlab_execute_time -y
make install-all
`
