### ISSUE TITLE
Can't add runtimes

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#2439]
**Describe the issue**
After saving a runtime configuration, it doesn't appear in the list

**To Reproduce**
1. Add a new runtime
2. Click on save
3. It won't appear in the list

**Screenshots or log output**

https://user-images.githubusercontent.com/5694071/152362735-51457738-51d2-48b2-8a39-7d1abc6dda9c.mp4
Interesting part starts at 1:35, but before some UX improvements on the error message would help as well.

**Expected behavior**
Runtime available in the list after saving

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.5.2 
 - Operating system: RHEL 8.5
 - Installation source: pypi
 - Deployment type: local installation

**Pipeline runtime environment**
If the issue is related to pipeline execution, identify the environment where the pipeline is executed
 - Kubeflow Pipelines (provide version number, whether multi-user auth enabled)

 
**Runtime configuration settings**
Can't save this configuration, therefore not providing

**Comment by kevin-bates** [comment]
The runtime configuration schema has a couple of properties with `minLength` constraints - [`cos_bucket` at 3](https://github.com/elyra-ai/elyra/blob/e57e3767602ab6d77f9dce1a3f92bf325bbdf6f3/elyra/metadata/schemas/airflow.json#L130), which you clearly met, and [`cos_password` at 8](https://github.com/elyra-ai/elyra/blob/e57e3767602ab6d77f9dce1a3f92bf325bbdf6f3/elyra/metadata/schemas/airflow.json#L172), which was the violated constraint.  

Unfortunately, the schema validator doesn't name the property that is violating the schema (we have no control over what it displays on violations).  Since it would be a better UX to enforce these kinds of constraints on data entry (where the property _is_ known and doesn't require a transaction request), I think this level of validation should be added to the front end. I suspect this will be the case anyway following the Lab 3.3 release when we can leverage the work @marthacryan has done in the settings editor.

**Comment by ptitzler** [comment]
I thought we had added the length constraints to the documentation when we first encountered this last year (or two years ago)? Apparently we have not, but should: https://elyra.readthedocs.io/en/latest/user_guide/runtime-conf.html

**Comment by ptitzler** [comment]
There is currently a UI limitation in place that we are planning to address in one of the next releases.

**Comment by romeokienzler** [comment]
@ptitzler @akchinSTC cn u pse up-prioritize? it is very odd behaviour, very confusing, see video...

https://user-images.githubusercontent.com/5694071/161233226-167c2d7e-1e5c-41be-822a-1d0c0f303ae1.mp4

**Comment by ptitzler** [comment]
> the problem is that the password is prefilled by my browser 

Can you please try again using version 3.7 and let us know which browser you are using? I am unable to recreate the auto-fill behavior.

**Comment by karlaspuldaro** [comment]
Related to issue #1147

**Comment by romeokienzler** [comment]
@kevin-bates 


>    You used a different name value (kindlocal3 vs. kindlocal)
>    You cleared the password field - which was a point of discussion above

yes I had to use a different name because otherwise (the backend?) wouldn't accept it since it is already stored, although an error was displayed when attempted to store "kindlocal" - in addition to telling me "kindlocal" wasn't stored it also didn't show up in the list of runtime configuration on the left hand side

**Comment by kevin-bates** [comment]
Hi @romeokienzler. 

Yeah, this is due to a couple of issues.  The backend uses the `name` field (`kindlocal` in this case) as the "primary key" for storing the instance data.  This, coupled with the fact that the editor never exposes this field (only exposing `display_name`), leads to this poor UX and user confusion.

We're contemplating using a UUID as a "primary key", both in terms of completely resolving this issue, but also in preparation for more enterprise-capable storage types (like SQL and NoSQL DBs).  This discussion is happening on https://github.com/elyra-ai/elyra/issues/2622.  I would love to hear your opinion on this as well.  Thanks.

**Comment by romeokienzler** [comment]
Thanks so much @kevin-bates will do
