### ISSUE TITLE
Elyra R editor vs JupyterLab R editor

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2463]
I've noticed that a new R editor tile is displayed in the launcher:

![image](https://user-images.githubusercontent.com/13068832/153085719-1f9bc54d-ba25-4089-993e-1634becaaa45.png)

Quo Vadis?

**Comment by ptitzler** [comment]
Somewhat related, there are now features in the JupyterLab editor that Elyra is not yet taking advantage of, e.g. https://github.com/elyra-ai/elyra/issues/2001

**Comment by karlaspuldaro** [comment]
JupyterLab file editor looks at available kernels to display extra options for creating specific new file types, currently supported for Python, Julia and R kernels - see [src code ](https://github.com/jupyterlab/jupyterlab/blob/fc73254325aaf445678c411d53e736d3027f81a2/packages/fileeditor-extension/src/index.ts#L228)

**Comment by ajbozarth** [comment]
I did some playing in the code to see if I could remove the default tiles from the Other section but it was not trivial. In order to do so we would need to completely replace the `LauncherModel` (not extend it like we do with `Launcher` widget) in order to access the private variable `_items` which stores the list of panels items in the launcher. If this is something we want to do it would not be that difficult to code, but we would need to make sure we catch any changes to those classes we're replacing from now on.

This could be a potential stop-gap until https://github.com/jupyterlab/jupyterlab/issues/12190 replaces the current launcher with one more flexible.

Adding to the 3.8 sprint for now, we can push it out at sprint planning if it's decided it's not a priority.

**Comment by akchinSTC** [comment]
make the JL editors extensions and this will allow us to disable them
