### ISSUE TITLE
Development installation fails with ResolvePackageNotFound: python=3.1

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#2788]
**Describe the issue**
Given the [documentation](https://elyra.readthedocs.io/en/latest/developer_guide/development-workflow.html) installation nodejs fails

**To Reproduce**
1. Follow these [steps](Setting up your development environment)
2. See error

> conda install -y -c conda-forge/label/main nodejs
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> 
> ResolvePackageNotFound: 
>   - python=3.1
> 

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
Paste the log output here.
</pre>
</details>

**Expected behavior**
Installation completes without error

**Deployment information**
conda 4.10.3

Linux li-c7445bcc-23db-11b2-a85c-f854e76b2a39.ibm.com 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 8 21:51:17 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by romeokienzler** [comment]
@ptitzler 

> conda create -n elyra_dev python=3.9
solved it for me - if u r ok I'll create a PR

**Comment by ptitzler** [comment]
> > conda create -n elyra_dev python=3.9
> 
> solved it for me - if u r ok I'll create a PR

In general there is no need to ask!
That said, I'm not sure there is something broken but something seems odd in your environment:
 - as far as I know there is no Python 3.1 version, as confirmed by https://endoflife.date/python
 - recent conda versions should only install Python  versions > 3.6
 - what's the output of `conda search python` before you explicitly install python?

We should definitely update https://github.com/elyra-ai/elyra/blob/main/docs/source/getting_started/installation.md and https://github.com/elyra-ai/elyra/blob/main/docs/source/developer_guide/development-workflow.md to indicate that Python must be version 3.7 or later. (We missed this when we removed support for version 3.6 earlier this year!)


> also a
> 
> > conda install jupyter jupyterlab
> 
> is needed b4
> 
> > make clean install
> 
> works

This is an unfortunate change that was introduced by @ajbozarth when he added support for using local jupyterlab builds. As a workaround I am performing a `make install-server` before `make install`, since the former will install the appropriate version of jupyterlab and the included tooling that is needed to build the UI. We should probably take a look at whether there is a way to detect whether jupyterlab is installed - and if it is not do so to make `make install` work without the need for any prerequisite setup steps. (If there's a technical reason why this cannot be done, we should perhaps have two make targets - one that installs everything and one that requires a previous jupyterlab installation.)

**Comment by ajbozarth** [comment]
> We should probably take a look at whether there is a way to detect whether jupyterlab is installed - and if it is not do so to make make install work without the need for any prerequisite setup steps. (If there's a technical reason why this cannot be done, we should perhaps have two make targets - one that installs everything and one that requires a previous jupyterlab installation.)

@ptitzler After reading this (and having been some time since I made the change) I realized a simple solution to this problem and opened up https://github.com/elyra-ai/elyra/pull/2790 addressing it

**Comment by ptitzler** [comment]
@romeokienzler can you please indicate 
 - whether or not you have one of the versions installed that Kevin identified as potential root causes
 - whether the default Python version in your env is 3.10
 - whether you plan to update the documentation to indicate that Python 3.7+ is supported (if you won't have the time, I'll create a PR so we can deliver this in the upcoming release) 
 
Thank you!

**Comment by richlysakowski** [comment]
> @ptitzler
> 
> > conda create -n elyra_dev python=3.9
> 
> solved it for me - if u r ok I'll create a PR
> 
> also a
> 
> > conda install jupyter jupyterlab
> 
> is needed b4
> 
> > make clean install
> 
> works

Is "make clean install" a command that will work in the Windows Command Console ?

**Comment by richlysakowski** [comment]
We MUST have full support for ALL-LOCAL installations for Elyra, with NO CLOUD DEPENDENCIES.  

If any cloud platform dependencies are required, then change the name to Cloud-Elyra and stop fooling people and wasting their time. 

Please cleanly separate the cloud-dependent modules from cloud-independent modules.   

Give the users choice and don't force them to find out which parts are cloud-dependent and which are cloud-independent.  

Please respect your user community requirements.  

Thank you.

**Comment by ptitzler** [comment]
I updated the issue title for clarity and pushed #2809, which updates the documentation to indicate what supported prerequisite software versions are. Together with @ajbozarth's #2790 this should address all issues that were raised by the issue's author.

**Comment by romeokienzler** [comment]
Thanks @ptitzler #2809 does the job
