### ISSUE TITLE
Programmatically exit a notebook early when match some condition

### ISSUE THREAD

**Issue by eromoe** [elyra-ai/elyra#2881]
**Is your feature request related to a problem? Please describe.**

Programmatically exit a notebook early . 

**Describe the solution you'd like**

I have below code use to skip a notebook node: 

```
class StopExecution(Exception):
    def _render_traceback_(self):
        pass

def exit_notebook(): raise StopExecution

if vstore.exists(Config.model_name):
    exit_notebook()
```

But would got error when run in pipeline : `Failed validating 'type' in notebook['properties']['traceback']:` 

**Describe alternatives you've considered**

I don't have a clear solution now.
Since elyra doesn't provide a way to avoid redundant execution, I tried to make it myself, but failed by `avoid redundant execution.` 
Do you have a way to walk around ?

**Comment by ptitzler** [comment]
In general this works as expected. Generic (notebook/script) nodes execute notebooks using the papermill package, which will _stop execution_ if any exception is raised.

![image](https://user-images.githubusercontent.com/13068832/184580654-43ef8266-964f-4b7a-abce-03cd18dda4a4.png)

yields on Kubeflow Pipelines

![image](https://user-images.githubusercontent.com/13068832/184581139-59efae16-6a3c-4bcc-894d-9ae8fac592ba.png)


What cannot be accomplished using this approach is to _skip execution of an entire notebook_ (node) and continue with the next pipeline node(s).


That said:
 - Which version of Elyra are you using?
 - The only reference to the error message you've provided (`Failed validating 'type'`) I can find in the source code is in a [test for custom components](https://github.com/elyra-ai/elyra/blob/main/elyra/tests/pipeline/kfp/test_component_parser_kfp.py#L493). Are you using by any chance the [`Run notebook using papermill` example component](https://github.com/elyra-ai/examples/blob/main/component-catalog-connectors/kfp-example-components-connector/kfp_examples_connector/resources/run_notebook_using_papermill.yaml) or a customized version of it?
 - Can you provide the complete error output/stack trace. I'm suspecting there's potentially a problem with how you've configured the pipeline because based on the symptom pipeline validation fails, not pipeline execution.

**Comment by eromoe** [comment]
@ptitzler 

elyra info: 
```
elyra                              3.10.1
elyra-examples-kfp-catalog         0.1.0
```

Error message from elyra alert: 
```
Traceback (most recent call last):
  File "C:\Users\ufo\anaconda3\lib\site-packages\elyra\pipeline\local\processor_local.py", line 234, in process
    papermill.execute_notebook(filepath, filepath, **additional_kwargs)
  File "C:\Users\ufo\anaconda3\lib\site-packages\papermill\execute.py", line 107, in execute_notebook
    nb = papermill_engines.execute_notebook_with_engine(
  File "C:\Users\ufo\anaconda3\lib\site-packages\papermill\engines.py", line 49, in execute_notebook_with_engine
    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
  File "C:\Users\ufo\anaconda3\lib\site-packages\papermill\engines.py", line 359, in execute_notebook
    cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
  File "C:\Users\ufo\anaconda3\lib\site-packages\elyra\pipeline\elyra_engine.py", line 83, in execute_managed_notebook
    return PapermillNotebookClient(nb_man, **final_kwargs).execute(**kernel_kwargs)
  File "C:\Users\ufo\anaconda3\lib\site-packages\papermill\clientwrap.py", line 45, in execute
    self.papermill_execute_cells()
  File "C:\Users\ufo\anaconda3\lib\site-packages\papermill\clientwrap.py", line 72, in papermill_execute_cells
    self.execute_cell(cell, index)
  File "C:\Users\ufo\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\ufo\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\ufo\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\ufo\anaconda3\lib\site-packages\nbclient\client.py", line 841, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "C:\Users\ufo\anaconda3\lib\site-packages\nbclient\client.py", line 627, in _async_poll_for_reply
    await asyncio.wait_for(task_poll_output_msg, self.iopub_timeout)
  File "C:\Users\ufo\anaconda3\lib\asyncio\tasks.py", line 494, in wait_for
    return fut.result()
  File "C:\Users\ufo\anaconda3\lib\site-packages\nbclient\client.py", line 660, in _async_poll_output_msg
    self.process_message(msg, cell, cell_index)
  File "C:\Users\ufo\anaconda3\lib\site-packages\papermill\clientwrap.py", line 106, in process_message
    output = super().process_message(*arg, **kwargs)
  File "C:\Users\ufo\anaconda3\lib\site-packages\nbclient\client.py", line 926, in process_message
    return self.output(cell.outputs, msg, display_id, cell_index)
  File "C:\Users\ufo\anaconda3\lib\site-packages\nbclient\client.py", line 947, in output
    out = output_from_msg(msg)
  File "C:\Users\ufo\anaconda3\lib\site-packages\nbformat\v4\nbbase.py", line 109, in output_from_msg
    return new_output(
  File "C:\Users\ufo\anaconda3\lib\site-packages\nbformat\v4\nbbase.py", line 68, in new_output
    validate(output, output_type)
  File "C:\Users\ufo\anaconda3\lib\site-packages\nbformat\v4\nbbase.py", line 40, in validate
    return validate_orig(node, ref=ref, version=nbformat)
  File "C:\Users\ufo\anaconda3\lib\site-packages\nbformat\validator.py", line 302, in validate
    raise error
nbformat.validator.NotebookValidationError: None is not of type 'array'

Failed validating 'type' in notebook['properties']['traceback']:

On instance['traceback']:
None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ufo\anaconda3\lib\site-packages\elyra\pipeline\local\processor_local.py", line 100, in process
    operation_processor.process(operation, elyra_run_name)
  File "C:\Users\ufo\anaconda3\lib\site-packages\elyra\pipeline\local\processor_local.py", line 243, in process
    self.log_and_raise(file_name, ex)
  File "C:\Users\ufo\anaconda3\lib\site-packages\elyra\pipeline\local\processor_local.py", line 186, in log_and_raise
    raise RuntimeError(f"({file_name}): {truncated_msg}") from ex
RuntimeError: (1.1.0 clean_data.ipynb): None is not of type 'array'

Failed validating 'type' in...

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ufo\anaconda3\lib\site-packages\tornado\web.py", line 1704, in _execute
    result = await result
  File "C:\Users\ufo\anaconda3\lib\site-packages\elyra\pipeline\handlers.py", line 156, in post
    response = await PipelineProcessorManager.instance().process(pipeline)
  File "C:\Users\ufo\anaconda3\lib\site-packages\elyra\pipeline\processor.py", line 148, in process
    res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
  File "C:\Users\ufo\anaconda3\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\ufo\anaconda3\lib\site-packages\elyra\pipeline\local\processor_local.py", line 108, in process
    raise RuntimeError(f"Error processing operation {operation.name} {str(ex)}") from ex
RuntimeError: Error processing operation 1 (1.1.0 clean_data.ipynb): None is not of type 'array'

Failed validating 'type' in...


```

**Comment by ptitzler** [comment]
> I don't know about `elyra-examples-kfp-catalog` , is it safe to remove ?

Yes, absolutely. This optional package is installed  by default, when you specify [`pip install elyra[all]`](https://elyra.readthedocs.io/en/stable/getting_started/installation.html#packaging). Since you are using the local runtime it's functionality does not apply. 

> Error message from elyra alert:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\ufo\anaconda3\lib\site-packages\elyra\pipeline\local\processor_local.py", line 234, in process
>     papermill.execute_notebook(filepath, filepath, **additional_kwargs)
>   File "C:\Users\ufo\anaconda3\lib\site-packages\papermill\execute.py", line 107, in execute_notebook
>     nb = papermill_engines.execute_notebook_with_engine(
>   File "C:\Users\ufo\anaconda3\lib\site-packages\papermill\engines.py", line 49, in execute_notebook_with_engine
>     return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
>   ...
>   File "C:\Users\ufo\anaconda3\lib\site-packages\nbformat\v4\nbbase.py", line 68, in new_output
>     validate(output, output_type)
>   File "C:\Users\ufo\anaconda3\lib\site-packages\nbformat\v4\nbbase.py", line 40, in validate
>     return validate_orig(node, ref=ref, version=nbformat)
>   File "C:\Users\ufo\anaconda3\lib\site-packages\nbformat\validator.py", line 302, in validate
>     raise error
> nbformat.validator.NotebookValidationError: None is not of type 'array'
> 
> Failed validating 'type' in notebook['properties']['traceback']:
> ```

The stacktrace clarifies the following:
 - the local runtime is used, which doesn't support custom components (hence my earlier `The only reference to the error message you've...`  question does not apply)
 - the problem is caused by the `1.1.0 clean_data.ipynb` Jupyter notebook

Two follow-up questions:
- When you open the notebook (after it was executed), does it contain any error messages? (Papermill inserts them)?
- Does the notebook work as-is when you run it in JupyterLab (`Run` > `Run all cells`)?

**Comment by eromoe** [comment]
It is because I add below code to  `1.1.0 clean_data.ipynb` . 

```
class StopExecution(Exception):
    def _render_traceback_(self):
        pass

def exit_notebook(): raise StopExecution

if vstore.exists(Config.model_name):
    exit_notebook()
```

It is used to avoid redundant execution, that is why I come up this feature request . I think elyra should support some kind of custom Exception or a mechanism .

**Comment by kevin-bates** [comment]
Understood.  The failure you're encountering is during the validation of the "output" notebook that Papermill produces as the result of running the "input" notebook's cells.  We suspect that your `StopExecution` code may be producing a mal-formatted notebook.  This is why @ptitzler asked...

>- When you open the notebook (after it was executed), does it contain any error messages? (Papermill inserts them)?
>- Does the notebook work as-is when you run it in JupyterLab (Run > Run all cells)?

Regarding the second question, I would amend it as:

_- Does the notebook work as-is when you run it in JupyterLab (Run > Run all cells) **while triggering the `StopExecution` code?**_

I suspect that it too should produce a notebook file that fails validation.

**Comment by eromoe** [comment]
> When you open the notebook (after it was executed), does it contain any error messages? (Papermill inserts them)?
Yeah, I confirm it failed when executed by `papermill` .

> - Does the notebook work as-is when you run it in JupyterLab (Run > Run all cells) while triggering the StopExecution code?

`Run > Run all cells` works perfect as below ,  you can try that code too.
![image](https://user-images.githubusercontent.com/3938751/184789527-66738c0f-e1eb-450b-bc6a-7d7503b83ac5.png)

**Comment by kevin-bates** [comment]
Could you please share a simple notebook that reproduces the issue, along with a dependencies list?

When I try to perform your import statements, I find that I need to install `env`, but then that lays down what appears to be Python 2 code!
![image](https://user-images.githubusercontent.com/22599560/184946717-efdbe5d8-c404-4ea1-b4de-fbbeff310349.png)

I'm not familiar with `vstore`, nor can I find anything about it.  Is `env.vstore` and local package for you?

**Comment by eromoe** [comment]
@kevin-bates

That's my code , just use to check  if an output file exists , 
You only need test `StopExecution` ,  you can just replace with a `True`  or omit it like below .  

```python
class StopExecution(Exception):
    def _render_traceback_(self):
        pass

def exit_notebook(): raise StopExecution

if True: 
    exit_notebook()
```

**Comment by ptitzler** [comment]
Confirmed using these assets:

[recreate.tar.gz](https://github.com/elyra-ai/elyra/files/9380669/recreate.tar.gz)

**Comment by ptitzler** [comment]
This works just fine if you don't try to override `_render_traceback_` the way you did. Not sure what you were trying to accomplish because the notebook's output provides a clear indication where execution stopped:


![image](https://user-images.githubusercontent.com/13068832/185586273-654d169f-8355-44ea-8e30-7280514ad9d9.png)

**Comment by ptitzler** [comment]
If your ultimate goal is to skip execution of some cells without causing papermill to return an error you might be able to accomplish that using 

```
import sys
sys.exit(0)
```

If this code is somewhere in the first notebook  and triggered then the second notebook will still run.

![image](https://user-images.githubusercontent.com/13068832/185611728-2166eb66-e241-4d34-a0ab-1a829e3b97cb.png)

I've tested this using local execution and Kubeflow Pipelines.

You can combine this with the following code to assure that this only happens when you run the notebook in a pipeline and not when you run it interactively:

```
if os.environ.get("ELYRA_RUNTIME_ENV") is not None:
    sys.exit(0)
```

The proprietary `ELYRA_RUNTIME_ENV` environment variable is only defined when Elyra executes a notebook or script.

You do need to be aware of that stopping the interpreter might have unintended consequences.

**Comment by eromoe** [comment]
WOW,  thank you solve my problem, you are so smart ! This definitely should be added to best practice in document .
