### ISSUE TITLE
How do I build Elyra container image from tip of branch?

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#2920]
**Describe the issue**
How do I build Elyra container image from tip of branch?

**To Reproduce**

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
Paste the log output here.
</pre>
</details>

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: [e.g. 1.5.3]
 - Installation source: [e.g. PyPI, conda, from source, official container image, custom container image]
 - Deployment type: [e.g. local installation, Docker, Kubernetes, Kubeflow [notebook server] , Open Data Hub]
 - Operating system: [e.g. macos, linux]

NOT A CONTRIBUTION

**Comment by kevin-bates** [comment]
If elyra has already been built (i.e., the wheel file exists), then `make elyra-image` just works.  However, if elyra has not been previously built, `make elyra-image` fails due to the missing assets:
```bash
$ make elyra-image
cp etc/docker/elyra/Dockerfile build/docker/Dockerfile
cp etc/docker/elyra/start-elyra.sh build/docker/start-elyra.sh
cp etc/docker/elyra/requirements.txt build/docker/requirements.txt
cp dist/elyra-$(grep __version__ elyra/_version.py | cut -d"\"" -f2)-py3-none-any.whl build/docker/
cp: dist/elyra-3.12.0.dev0-py3-none-any.whl: No such file or directory
gmake: *** [Makefile:261: elyra-image] Error 1
```

as a result, it seems the `elyra-image` target needs a "dependency adjustment" and I would argue this issue should be re-opened (with a better problem description).

@lresende - is that essentially what you ran into when opening this issue in the first place?
