### ISSUE TITLE
Look into removing material ui packages

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#2948]
Users running in hosted environments with slower network latencies are experiencing Elyra startup delays that may be due to the lack of material ui packaging optimization.  We should understand where these costs are occurring and only packaging what is absolutely necessary for the proper functioning of Elyra.

**Comment by ajbozarth** [comment]
We currently still use Material UI in three places:
1. Toast notifications in pipeline-editor
2. Theme Provider in ui-components
3. The Metadata Header UI in metadata-common

As for removing these:
1. Toast notifications are being added to core in 4.0, we can either wait or directly use the library they are merging into core (I believe it's not new code)
2. We already wanted to remove StyleProvider, so we can see how much we leverage ThemeProvider vs just generically wrap it ourselves
3. This will be the hardest since all the header functionality uses material ui and we will need to rewrite it

**Comment by ptitzler** [comment]
> We currently still use Material UI in three places:
>
> 1. Toast notifications in pipeline-editor
> 2. Theme Provider in ui-components
> 3. The Metadata Header UI in metadata-common

We've discussed this in today's [dev meeting](https://elyra.readthedocs.io/en/latest/getting_started/getting-help.html#join-the-daily-development-meetings):
- Item 1 does not contribute to the reported performance issue. Thus there is no urgent need to address this right away and work can be held until JupyterLab 4.0 becomes available.
- Work for item 2 will be tracked in https://github.com/elyra-ai/elyra/issues/2951
- Work for item 3 will be tracked in https://github.com/elyra-ai/elyra/issues/2952

**Comment by ptitzler** [comment]
@jschaeck please subscribe to those issues
