### ISSUE TITLE
[Question] How to setup a runtime configuration?

### ISSUE THREAD

**Issue by augustovictor** [elyra-ai/elyra#2963]
Could not find any specific doc on what value to put under `Kubeflow Pipelines API Endpoint` when defining a Runtime Configuration.

So far I have kubeflow running on eks (aws).

What I'm trying to accomplish is a simple elyra's pipeline executed on kubeflow pipelines.

However I cannot figure out what value to put on `Kubeflow Pipelines API Endpoint`.

![image](https://user-images.githubusercontent.com/938051/194943655-899f7645-1262-47da-9b98-84832377a0a7.png)

### Further info
- Elyra's image used for jupyter server configuration: `elyra/kf-notebook:3.9.0`

### What i've tried so far
Getting the ip of `ml-pipeline-ui` service in k8s and setting `Kubeflow Pipelines API Endpoint` with it.

![image](https://user-images.githubusercontent.com/938051/194945834-4b696c7d-57a2-470d-868b-c677b9da4a30.png)

Sorry if I missed some obvious steps...

**Comment by ptitzler** [comment]
Where is your JupyterLab/Elyra running? In the cluster where Kubeflow is running on on a separate machine, e.g. your laptop?

**Comment by augustovictor** [comment]
> Where is your JupyterLab/Elyra running? In the cluster where Kubeflow is running on on a separate machine, e.g. your laptop?

@ptitzler In the kubeflow cluster

**Comment by ptitzler** [comment]
Thank you! In that case you need to use the [`KUBERNETES_SERVICE_ACCOUNT_TOKEN` authentication type ](https://elyra.readthedocs.io/en/latest/user_guide/runtime-conf.html#kubeflow-authentication-type-auth-type) and configure your environment as described in section 'Full Kubeflow (from inside cluster)' [of this doc](https://elyra.readthedocs.io/en/latest/user_guide/runtime-conf.html#kubeflow-authentication-type-auth-type).

As `API_ENDPOINT` specify `http://ml-pipeline-ui.<namespace>:<port>/pipeline`, replacing `<namespace>` with the namespace where Kubeflow is deployed (likely `kubeflow` [1]) and `<port>` with the `ml-pipeline-ui` service's port (likely 80).

[1] to confirm the namespace you can run `kubectl get services ml-pipeline-ui -n kubeflow`. If this does not return a match try other namespaces.

Note that the links in the Elyra UI, e.g. 

![image](https://user-images.githubusercontent.com/13068832/195106015-430d74d9-8451-417a-907f-ab42e2c037d7.png)

won't work because your browser is running on a machine that won't be able to resolve the host name, since it's an in-cluster URL. If you do want that to work you'll need to expose the service to the public and also specify the [Public Kubeflow Pipelines API endpoint](https://elyra.readthedocs.io/en/latest/user_guide/runtime-conf.html#public-kubeflow-pipelines-api-endpoint-public-api-endpoint) in your runtime configuration.



One more clarification please. Are you running JupyterLab/Elyra as a Kubeflow Notebook server?

**Comment by augustovictor** [comment]
Yup. I'm running JupterLab/Elyra as a Kubeflow Notebook server.
I'll try what you've suggested then I get back to you. Thanks =D

**Comment by augustovictor** [comment]
@ptitzler I got part of it to work

First Applied PodDefault;
Then criated a new jupyterlab server and selected `Allow access to kubeflow pipelines` in the `Configurations` section.
When it started I created a pipeline runtime config with the following values:
![image](https://user-images.githubusercontent.com/938051/196413753-57dd48b9-1fef-4907-bd11-bd9a05d4344a.png)


Then got this message:
![image](https://user-images.githubusercontent.com/938051/196413990-9e097af5-3f86-4e36-b2f4-facf68c2d1fd.png)

The logs in my notebook pod (`k -n kubeflow-user-example-com logs victor-elyra-0 -f`) says:
```
ERROR:root:Failed to get healthz info attempt 5 of 5.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/kfp/_client.py", line 411, in get_kfp_healthz
    response = self._healthz_api.get_healthz()
  File "/opt/conda/lib/python3.8/site-packages/kfp_server_api/api/healthz_service_api.py", line 63, in get_healthz
    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501
  File "/opt/conda/lib/python3.8/site-packages/kfp_server_api/api/healthz_service_api.py", line 134, in get_healthz_with_http_info
    return self.api_client.call_api(
  File "/opt/conda/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/opt/conda/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 188, in __call_api
    raise e
  File "/opt/conda/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/opt/conda/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 389, in request
    return self.rest_client.GET(url,
  File "/opt/conda/lib/python3.8/site-packages/kfp_server_api/rest.py", line 230, in GET
    return self.request("GET", url,
  File "/opt/conda/lib/python3.8/site-packages/kfp_server_api/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'content-length': '19', 'content-type': 'text/plain', 'date': 'Tue, 18 Oct 2022 11:09:29 GMT', 'server': 'envoy', 'x-envoy-upstream-service-time': '1'})
HTTP response body: RBAC: access denied
```
---
Then i tried adding a roleBinding between the ServiceAccount `default-editor` under my user's namespace, and `ml-pipeline-ui` (as described [aggregate-to-kubeflow-pipelines-edit](https://github.com/kubeflow/pipelines/blob/efb96135033fc6e6e55078d33814c45a98566e68/manifests/kustomize/base/installs/multi-user/view-edit-cluster-roles.yaml#L36-L99))
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-namespace-2-kubeflow-edit
  ## this RoleBinding is in `namespace-1`, because it grants access to `namespace-1`
  namespace: kubeflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-edit
subjects:
  - kind: ServiceAccount
    name: default-editor
    ## the ServiceAccount lives in `namespace-2`
    namespace: kubeflow-user-example-com
```

However the error still persists.
What am I missing?

Thanks

**Comment by ptitzler** [comment]
@thesuperzapper do you have any insights to share that might help in this case? I don't think this is an Elyra specific configuration issue.

**Comment by ozen** [comment]
@augustovictor  it seems there is a mix-up in the namespaces. In the RoleBinding manifest you shared, the namespace in the subjects is `kubeflow-user-example-com`, but it's `kubeflow` in `metadata.namespace` and in the elyra runtime config.

**Comment by ozen** [comment]
@augustovictor I had a similar issue that was solved by changing the api endpoint url: #3092

**Comment by ptitzler** [comment]
See previous comment. Please re-open if this is still an issue.

**Comment by gioargyr** [comment]
Hello all,

I am at the same point that @augustovictor was:
`Failed to initialize `kfp.Client()` against: 'http://ml-pipeline-ui.kubeflow:80/pipeline' `
The reason for this error is:
`TimeoutError: Failed getting healthz endpoint after 5 attempts.`

Do you have a specific solution for that?
fyi: _changing the api endpoint url_ didn't help.
