### ISSUE TITLE
Pipeline editor: display semantically de-duplicated entries for enums

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2966]
**Is your feature request related to a problem? Please describe.**

When a pipeline default value is defined for an enum (such as 'runtime image', or as shown below for the 'disable node caching' property), the node property rendering includes a (semantic) duplicate value that the user can choose from:

![](https://user-images.githubusercontent.com/13068832/194897552-8e624ab8-c742-47e0-be04-03d036acc76f.png)

**Describe the solution you'd like**
Ideally no duplicates are displayed. For the above example this means the select list would only display two entries: `True (pipeline default)` and `False`. If the configured pipeline default value was `False` only `True` and `False (pipeline default)` would be rendered as selectable node property options

**Additional context**
Raised in https://github.com/elyra-ai/elyra/pull/2961

**Comment by ajbozarth** [comment]
This idea doesn't handle every user edge case. In the current implementation (using the true/false example) there would be three different options:
1. use the default value (whatever it currently is), this is persisted as "no value"
2. set the value to True
3. set the value to False.

If we made this change we would end up only supporting two of the above cases depending on how we persist their choice. If the drop down had the values `True (pipeline default)` and `False`, the value of `False` would be False, but what would the value of `True (pipeline default)` be? Would it be True? In that case if the user changed the default to False this node would no longer be using the pipeline default since it would still have the value True. If it's value is "no value" (ie use the pipeline default) then there would be no way for the user to set the value to True so it would keep that value even if the default changed.

Since these three case are important and distinct I believe the better way to solve this confusion is to change the label text when the pipeline default is chosen, rather than displaying `<enum value> (pipeline default)` I suggest we rearrange it to focus on the "pipeline default" text. As shared in our scrum I suggest switching it to one of the following:

- `Pipeline Default: <enum value>`
- `Pipeline Default: [<enum value>]`
- `Pipeline Default: (<enum value>)`
- `Use pipeline default: <enum value>`
- `Use pipeline default: [<enum value>]`
- `Use pipeline default: (<enum value>)`

These options switch the focus from the value pipeline default is currently set to, to the fact that the user is choosing to use the pipeline default, which happens to be the displayed value.

**Comment by kevin-bates** [comment]
Great catch @ajbozarth!  

I agree that it seems like this can be addressed with a label change.  Of the 6 suggestions, my preference would be: `Use pipeline default: [<enum value>]`.  I like how it conveys an instruction via _Use_ and feel the square brackets do a better job of conveying an "option" (in that this value _could_ change) than either nothing or parenthesis.  That said, I'll leave the UX portion of this up to the experts.
