### ISSUE TITLE
Include/capture cell output during papermill execution

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#356]
During notebook execution with papermill, no output is shown unless a cell errors out, however it could be beneficial to make output available during longer running cells, so the user doesnt have to guess if a cell is stuck or not making progress. Some ideas include creating checkbox or something to the each node in pipeline editor to denote that we want to see all output during node execution in the kfp runtime logs.

**Comment by lresende** [comment]
execute_notebook has an option to do this: `log_output`, and we can just update the `kfp-notebook` bootstrap script to handle that. 

```
def execute_notebook(
        cls,
        nb,
        kernel_name,
        output_path=None,
        progress_bar=True,
        log_output=False,
        autosave_cell_every=30,
        **kwargs
    ):
```

**Comment by akchinSTC** [comment]
yep, question is do we want to make it default behavior or something we can turn on/off ...if so how granular should we make it....eg on a per notebook/node basis?

**Comment by kevin-bates** [comment]
I think this is the kind of thing that is useful to be configurable and the node level (per notebook) seems ideal.  If this is exposed in the properties dialog, then I'd say a default of 'off' is appropriate.

One concern, when logging is on, is whether this may lead to resource issues since there's potential for gigabytes of data (mostly probably unwarranted).  Is this stuff being streamed somewhere or where does this output live during the execution?

**Comment by akchinSTC** [comment]
+1 to the configurable at the node level in our properties dialog box.

In our dev cluster we're simply letting the pod use a hostpath volume to persist the logs after execution that is on the host system File System, but anything in production probably will be using more robust volume types. (ceph, azure, gce)
I can see your concern in that this could be abused/misused by users, maybe adding a warning? e.g.

- [ ] Show Notebook Execution Output ( Warning: May increase log size )

**Comment by kevin-bates** [comment]
Yeah, I agree about the other storage types.  I guess I'm not as concerned about misuse as I am about not realizing the amount of spam that can happen over several hours.  Hopefully, most experiments won't be too verbose.

I think we can address the warning in the docs to conserve real estate and simplify things.  It may also consume memory depending on how the output is captured.  Is this something kfp-notebook does?

How do we go about showing the results?  Is the execution output captured regardless and this is more about displaying that captured output?

I'm thinking we could drop the 'Notebook' from the option (also to conserve space) since this is the kind of thing that would likely apply to other node types beyond notebooks (when available).

**Comment by 19690ao** [comment]
Hey, I'm interested in working on this issue

**Comment by ptitzler** [comment]
This issue might be outdated and its merit/goal should be re-evaluated. For Kubeflow the log file now includes something like this because debug is enabled by default

```
[D 20:55:37.931] msg_type: status
[D 20:55:37.932] content: {'execution_state': 'busy'}
[D 20:55:37.933] msg_type: execute_input
[D 20:55:37.933] content: {'code': "print('hello')", 'execution_count': 10}
[D 20:55:37.936] msg_type: stream
[D 20:55:37.936] content: {'name': 'stdout', 'text': 'hello\n'}
[D 20:55:37.938] msg_type: status
[D 20:55:37.938] content: {'execution_state': 'idle'}

Executing:  83%|████████▎ | 10/12 [00:01<00:00, 11.07cell/s][D 20:55:37.969] Executing cell:
print('hello')
[D 20:55:37.975] msg_type: status
[D 20:55:37.975] content: {'execution_state': 'busy'}
[D 20:55:37.976] msg_type: execute_input
[D 20:55:37.976] content: {'code': "print('hello')", 'execution_count': 11}
[D 20:55:37.977] msg_type: stream
[D 20:55:37.977] content: {'name': 'stdout', 'text': 'hello\n'}
[D 20:55:37.979] msg_type: status
[D 20:55:37.979] content: {'execution_state': 'idle'}
[D 20:55:38.019] Executing cell:
print('hello')
[D 20:55:38.030] msg_type: status
[D 20:55:38.030] content: {'execution_state': 'busy'}
[D 20:55:38.031] msg_type: execute_input
[D 20:55:38.031] content: {'code': "print('hello')", 'execution_count': 12}
[D 20:55:38.033] msg_type: stream
[D 20:55:38.033] content: {'name': 'stdout', 'text': 'hello\n'}
[D 20:55:38.034] msg_type: status
[D 20:55:38.035] content: {'execution_state': 'idle'}

Executing: 100%|██████████| 12/12 [00:01<00:00,  6.67cell/s]
```

**Comment by akchinSTC** [comment]
Closing this issue since the papermill output is now seen in debug(default) output in kfp.
