### ISSUE TITLE
Look into updating build to support watch

### ISSUE THREAD

**Issue by ajbozarth** [elyra-ai/elyra#375]
Currently we need to do a full make clean install to get a consistent experience during development. We want to look into what it would take to update our makefile to instead support `jupyter lab --watch` which would allow us to edit our front end packages and see the changes without a full rebuild.

**Comment by karlaspuldaro** [comment]
Just thought I'd share what's been working for me so far since watch mode is inconsistent, is to build tsc then build jupyterlab, already more efficient than running make clean install so often. The steps are:

Go to the src of typescrypt files, ie:
`cd ~/github/elyra/packages/application`

Build tsc and jupyterlab
`tsc -b -v`
`jupyter lab build`

Run jupyterlab
`jupyter lab --debug`

**Comment by lresende** [comment]
On external extensions (in this case JupyterLab git), this is what is working for me:

-make all your builds and links (note, the extension needs to be linked instead of installing)
-start JupyterLab - `jupyter lab --watch`
-watch your extension - `tsc -w`

I usually then only need to reload the browser to get a new version of UI artifacts (e.g. js)

**Comment by ajbozarth** [comment]
I opened #502 adding watch support (with some minor caveats) after some discussions offline with @karlaspuldaro and @lresende 

With the PR you can utilize watch with the following steps:
1. Initial build with `make clean install`
2. Watch for changes with `make watch`
3. Run Lab with `jupyter lab --watch`

The caveats:
- Steps 2 and 3 above tail and need their own terminal tab/window (make sure the conda env is the same)
- Changes to utils in application that are called within other packages will not be picked up by `jupyter lab --watch` and require stopping and starting to pick up.
- When running `jupyter lab --watch` the start up of lab takes about 2-3x longer.
