### ISSUE TITLE
Reuse ExpandableComponent in SubmissionHandler

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#403]
`ExpandableComponent` is a reusable react component created for code snippets display, that takes a display name and a react element with extra info that is displayed upon expand button click event. 
It is currently located in `packages/code-snippets/`
A similar usage would be in SubmissionHandler `showDialog()`
We should move ExpandableComponent to packages/application or to some util folder, and also integrate it to SubmissionHandler.

**Comment by vabarbosa** [comment]
related work: https://github.com/elyra-ai/elyra/pull/546

**Comment by ajbozarth** [comment]
Taking my name off this so others can pick it up, I don't know when I'd get to it.

The goal for this issue is to try and merge `ExpandableComponent` and `ExpandableErrorDialog` or at least have one leverage the other in some way. The two classes current duplicate quite a bit of code. Both are located within `ui-componets` so any refactor would have minimal impact to the UI/UX

**Comment by vabarbosa** [comment]
i can look into this

**Comment by ajbozarth** [comment]
thanks @vabarbosa feel free to ping me with any questions. My expectation was to make `ExpandableErrorDialog` just extend `ExpandableComponent` in some way
