### ISSUE TITLE
Add ability to export defined pipelines as other different readable serialized formats

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#407]
Currently we compile the pipeline using the kfp sdk into a tar file and upload to the kfp runtime. We want to add the ability to export a defined pipeline as a format other a tar (e.g. argo yaml, python etc.)

**Comment by akchinSTC** [comment]
Working branch here: 
https://github.com/akchinSTC/elyra-1/tree/ISSUE-407

@ajbozarth - Think you mentioned the quickest way was to include a dialog box with a drop down with exporting file type options. Did we want to include this in the top toolbar of the pipeline UI or as a right click option? I just need two parameters from you coming from the pipeline, a boolean value on whether to export or not, and if so, what type of file

**Comment by ajbozarth** [comment]
So in the pipeline UI, the buttons at the top are actually part of canvas, and not part of the lab ui (like the ones in python editor). So the easiest way to add a UI for this leveraging what we already know (and not having to learn more about canvas) would be to add a new button which opens up a jupyterlab dialog (popup) that contains a dropdown for the export options. This would be similar in coding to the run button which opens a dialog with a dropdown to choose a runtime.

If you want to take a stab at the UI you can, otherwise you can have @marthacryan @karlaspuldaro or I code it once we're done with our current work (may or may not make this sprint). I have a detailed implementation in my head that I could explain verbally in detail to whoever handles it.
