### ISSUE TITLE
Clarify usage of `cos_secure` for kfp runtime metadata

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#417]
- [ ] Add `cos_secure` to kfp schema
- [ ] Validate usage (e.g. `cos_secure` with `http` endpoint)
- [ ] Add tests around `cos_secure` usage

**Comment by kevin-bates** [comment]
Looks like all that the `secure` (boolean-valued) parameter does when creating a `minio` client is help determine if the endpoint (which does not include the scheme (e.g., `http`)) should use a scheme of `http` (when `secure == False`) or `https` (when `secure == True`).

Since the runtimes metadata schema specifies the `cos_endpoint` as a URI (and we include the scheme), why not just have our integration with creating the `minio` client just interrogate the scheme of the `cos_endpoint` and set the `secure` boolean parameter accordingly?  Otherwise, it can be confusing by having a `cos_endpoint` of `http://foo.com/...` with a `cos_secure` value of `True`, or vice versa (with a `cos_endpoint` scheme of `https://foo.com/...` and `cos_secure` = `False`).

[For example](https://github.com/elyra-ai/elyra/blob/master/elyra/util/cos.py#L29-L36):
```python
     self.endpoint = urlparse(config.metadata['cos_endpoint'])
     self.access_key = config.metadata['cos_username']
     self.secret_key = config.metadata['cos_password']
     self.secure = self.endpoint.scheme == 'https'
     self.bucket = config.metadata['cos_bucket']
```

**Comment by lresende** [comment]
The `secure` field is here mostly to historical reasons as the COS SDKs don't require a schema and we had to identify if the endpoint in use was secure or not. Your proposal seems right on based on our current usage of schemas and proper validation from the metadata/schema.
