### ISSUE TITLE
Implement more dynamic pipeline editor configuration 

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#454]
Currently, the pipeline editor has static JSON configuration files. We should enable
more dynamic configuration files via REST APIs. 

Files today:
https://github.com/elyra-ai/elyra/blob/master/packages/pipeline-editor/src/palette.json
https://github.com/elyra-ai/elyra/blob/master/packages/pipeline-editor/src/properties.json

**Comment by ajbozarth** [comment]
Discussion point from my review of #650 

> As for moving properties.json to an api call, I don't agree with this. properties.json is not a fully functional template or schema. It is just a partially filled out instance of a Common Properties arg. As such I don't believe it is something that should be hosted by the backend. I am open to arguments against my option here, I just don't see it as a valid case at this time.

**Comment by lresende** [comment]
As part of #500, we want to start enabling new components to the canvas in a more dynamic way, and this would enable us to produce the canvas configurations programmatically on the server. Do you have other suggestions?

**Comment by ajbozarth** [comment]
After reading #500 I think I follow your train of though. But #650 would just a be part 1 in this case and we would follow it by moving the functionality of `initPropertiesInfo()` to the backend then? Because that function is what give me pause here. With out running that function,`properties.json` is an incomplete config.

I can understand moving configs like` pallete.json` to backend api's but as of now properties.json is intrinsically tied to multiple functions in `PipelineEditorWidget`: `initPropertiesInfo()`, `openPropertiesDialog()`, and `applyPropertyChanges()` are all hard coded to that one file. If we plan to move that file to the backend to be generic, then all those functions should be updated as well to handle any generic common properties config.

**Comment by lresende** [comment]
Yes, this is phase 1. I also think you have a better understanding of the configuration requirements from canvas and we could definitely make these changes in multiple steps if you think it would make more sense. 

Going back to the overall idea here, imagine we have a KFP component like this:

```
name: 'Train Spark Model - IBM Cloud'
description: |
  Train a Spark Model using IBM Cloud Spark Service
metadata:
  annotations: {platform: 'IBM Cloud Spark Service'}
inputs:
  - {name: bucket_name,      description: 'Required. Object storage bucket name'}
  - {name: data_filename,    description: 'Required. Name of the data binary'}
  - {name: model_filename,   description: 'Required. Name of the training model file'}
  - {name: spark_entrypoint, description: 'Required. Entrypoint command for training the spark model'}
outputs:
  - {name: model_filepath,           description: 'Spark Model binary filepath'}
  - {name: train_data_filepath,      description: 'Spark training data filepath'}
implementation:
  container:
    image: docker.io/aipipeline/train_spark:latest
    command: ['python']
    args: [
      -u, train_spark.py,
      --bucket_name, {inputValue: bucket_name},
      --data_filename, {inputValue: data_filename},
      --model_filename, {inputValue: model_filename},
      --spark_entrypoint, {inputValue: spark_entrypoint}
    ]
    fileOutputs:
      model_filepath: /tmp/model_filepath
      train_data_filepath: /tmp/train_data_filepath
```


The idea is that we would produce a `palette.json` that would then have two operations `Notebook` and `Train Spark Model` available, and we would also introspect the metadata for this component and harvest inputs, etc to generate a valid properties.js. 

The current issue just wants to move the static files to be generated on the backend.

A second step might actually be to generate the properties.json with the runtime-images pre-populated as the backend already have that information. 

A third step might be to identify if we are going to use provide properties to all available components versus a on-demand request when we are about to show the properties dialog.

**Comment by ajbozarth** [comment]
Ok I'm following now. In that case I would like to purpose we wait until step two to move the properties.json to the backend. (Adding the endpoint in step 1 is fine). I'd prefer we don't have our api serve a partial config and include the move of the json and the move of the runtime-images population in a single step 2 PR. We could then also include updates to openPropertiesDialog(), and applyPropertyChanges() to be generic in either that PR or a third pr.

Also to be clear, the idea is that our current properties would become just the default properties for a notebook node and we may have different properties for different nodes or the pipeline as a whole (like airflow vs kfp specific)? In that case I would have feedback on the api itself in the open PR (since it only creates two specific endpoints for those two specific files)

**Comment by lresende** [comment]
> Also to be clear, the idea is that our current properties would become just the default properties for a notebook node and we may have different properties for different nodes or the pipeline as a whole (like airflow vs kfp specific)? In that case, I would have feedback on the API itself in the open PR (since it only creates two specific endpoints for those two specific files)

Yes, I believe on phase 3 here, when some of the other items on #500 start becoming available, we would have a better idea of a more final API. Having said that, we will need to have a discussion if we provide a fully backed properties payload when accessing the endpoint, or if we modify the API to enable per component request (e.g. `/properties/component`), but then how do we deal with node tooltips that are now using this.

**Comment by ajbozarth** [comment]
Based on our discussion here I would say we should have some discussion around this at our next dev meeting and hold off on merging any PRs related to it until then (I'd say it shouldn't be in 1.0 anyway). We should also try to get @fresende on that call for his input as the PR creator.

**Comment by kevin-bates** [comment]
> at our next dev meeting

Do you mean scrum or dev meeting?  Next Thursday is way too late.  This should be discussed sometime Monday (6/22) and would like a window of at least 60 minutes, so Monday afternoon is more likely.

**Comment by ajbozarth** [comment]
I did mean the dev meeting, and why is there a rush on this. If the API is not meant to be final we don't want it in 1.0 anyway.

**Comment by kevin-bates** [comment]
I was hoping to get to it prior to next Thursday - but I have other things I can work on outside of this repo. I thought we could at least try to get on the same page.  We might find that things should be done differently or come up with other ideas.  But I can wait - no worries here.  

Personally, I don't think the community call is the right place for this as I believe it needs way more time and thought and should be a dedicated meeting.
