### ISSUE TITLE
Add ability to create metadata instances via REST API

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#483]
We should expose the ability to create metadata instances via the REST API.  Whether all namespaces support this is something we should probably discuss.  However, for namespaces like `code-snippets`, it makes sense to allow users to create, replace, and delete(?) in such instances.

The endpoint to create an instance would be: `/api/metadata/<namespace>/<resource>` where the body consists of a single JSON entity that is the resource.  For example, the following could be the JSON-body used to create a code-snippet named `powers_of_2` in namespace `code-snippets`:

Request:
```
PUT HTTP://localhost:8888/api/metadata/code-snippets/powers_of_2
```
Request body:
```json
{
  "display_name": "Powers of 2",
  "metadata": {
    "language": "Python",
    "code": [
      "import time\n",
      "i = 2\n",
      "while i > 0:\n",
      "    i *= i\n",
      "    print(i)\n",
      "    time.sleep(0.5)"
    ]
  },
  "schema_name": "code-snippet"
}
```
We use `PUT`since it both creates and replaces resources and specifies that the resource name (e.g., `powers_of_2`) be part of the URI (which seems more natural to me). 

Should we also support `DELETE`?  If so, we should restrict the scope of where instances can be deleted.  Both `PUT` and `DELETE` should only write to local runtime directories.  

This topic probably warrants further discussion.

**Comment by vabarbosa** [comment]
+1
---
i think all CRUD (create, read, update, delete) operations should be available via REST APIs (post, get, put, delete) for all namespaces. whether or not these get surfaced to the user through some UI component/action would depend on the namespace.

for example, with `code-snippets` users should be able to fully manage their code snippets via the UI so the complete set of REST APIs would be beneficial.

for a namespace where users do not need to create, update, or delete, the REST APIs should still be in place. an admin may want to manage the namespaces as part of some workflow (via some other tool or extension) and access to the REST APIs could possibly help simplify the workflow.

i expect there will be scenarios where an admin does not want REST API access to some namespaces. rather than implementing a full ACL, in these cases, perhaps the [Meta-behavior proposal](https://github.com/elyra-ai/elyra/issues/518) (if i understand it correctly) could come into play. something like `schema_deny: ["update", "delete"]`.

in any case, regardless of how it is decided the REST API be managed or controlled, there should be the ability to manage some metadata instances via REST API.

**Comment by kevin-bates** [comment]
Thanks for the response to this @vabarbosa.  Yes, that is **exactly** the kind of behavior that could be provided via meta-behaviors, and, in fact, I was going to add this very use case as a comment to that proposal. 

Also, based on the defaulting example in that proposal, I'm thinking the CRUD requests should probably operate on arrays - or expose that option.  The reason for this is that down the road, the backing store will not be a filesystem - well, at least we need the option to support other stores, and there are cases, like defaulting, where users will want the CRUD op to be a transaction, and it would be good to _enable_ that kind of behavior by allowing multiple operations within a single request.

**Comment by kevin-bates** [comment]
We're moving forward with this and currently just honoring a hierarchy of folders with the "most local" directory being where new instances will be added.  This hierarchy is based on a _variation_ of the output of `juptyer_core.paths.jupyter_path()`.  This method returns a 3-4 item array like the following...
Index 0: directory based on user's home directory
Index 1: directory based on current python env (sys.prefix)
Index 2,3: directory typically storing shared data: /usr/local/share/jupyter, /usr/share/jupyter.

Since we now install some instances (runtime-images) are part of the installation, these instances should be "last-resort" or lowest-priority.  However, those instances are relative to the Index 1 entry.  With shared instances being considered as lower-priority.

We will go ahead and define our own order of items such that the python env entry is last in the list.  This enables the ability for "factory data" to be treated as lowest-priority.

We'll need to address how to properly created 'shared' instances via tools - and not just copying files to appropriate locations at some point.
