### ISSUE TITLE
Merge Notebook Scheduler and Pipeline editor extensions

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#494]
We are looking into expanding the number of buttons available on Elyra to enable submitting KFP Argo YAML and KFP script DSL and we will probably have other additions that are in the intersection of these two extensions. 

Merging them would:
- Avoid the split of pipeline code into the application package
- Make it easier to share code
- Simplify/Speedup build/packaging

Some of the drawbacks would be:
- ?

**Comment by ajbozarth** [comment]
I am interesting in working on this.

I have a few opinions on this:

- The merge makes sense if you start thinking of the "the button" (notebook-scheduler) as just a pipeline submission button to add to notebooks, like how the git button is included with the git extension.
- This would allow the movement of all pipeline specific utils out of application.
- Would we want to introduce subdirectories in `src` separating the two functionalities and utils?
- As for drawbacks, there is the issue of back compatibility, this update might warrant a 1.0 release due to the change.

**Comment by lresende** [comment]
> * The merge makes sense if you start thinking of the "the button" (notebook-scheduler) as just a pipeline submission button to add to notebooks, like how the git button is included with the git extension.
> 

Exactly, with the additions of the other buttons, this is more and more looking as just drivers to submit  one or more`items` to the pipeline.

> * This would allow the movement of all pipeline specific utils out of the application.
> 

Definetly a plus.


> * Would we want to introduce subdirectories in `src` separating the two functionalities and utils?

Not necessarily, most likely we need to introduce one extra widget (submitSingleItem) type of thing, that would then be shared by all `single item`submissions?

> 
> * As for drawbacks, there is the issue of back compatibility, this update might warrant a 1.0 release due to the change.

What is your concern here? The only thing I could think of is the pre-existence of the notebook-scheduler extension, but we could document how to remove or enhance our install code to remove that if there?

**Comment by ajbozarth** [comment]
Moving this into the current milestone since I will be starting work on it tomorrow.

Based on a conversation with @lresende we will be doing this in multiple steps, the first of which will be implemented prior to continuing my work on #232 / #271 / #400 / #403

Step 1: Move the files in `notebook-scheduler` into `pipeline-editor` as is and include functionality found in the index.ts of `notebook-scheduler` in the index.ts of `pipeline-editor`

Step 1.5: Handle utility refactor to address #232 / #271 / #400 / #403

Step 2: Refactor `pipeline-editor` to remove duplicate code moved from `notebook-scheduler`  in step 1 and consolidate and modularize the duplicate code into "utils".

Note: Step 2 could be broken down into smaller sub-steps.

**Comment by lresende** [comment]
Closing this as the "merge" of the packages has been completed. 
Please create new issues for any remaining tasks.
