### ISSUE TITLE
Enable running KFP Argo yaml  directly from editor

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#495]
Now that we have the ability to export a pipeline into KFP Argo YAML, we should enable running directly from the editor. 

- [ ] How to identify a YAML as a KFP Argo YAML?
- [X] merge the Notebook Scheduler and Pipeline Editor extensions (see #494)

**Comment by karlaspuldaro** [comment]
I'd be interested in helping out on this issue

**Comment by lresende** [comment]
Now that the `notebook scheduler` has been merged into the pipeline project, it should be much easier to enable the button or multiple buttons to run these files

**Comment by karlaspuldaro** [comment]
> How to identify a YAML as a KFP Argo YAML?
	
- file ext `.yaml`
- file content includes 
```
    "apiVersion": argoproj.io/v1alpha1
    "kind": Workflow
```

> How to identify a python script as a KFP DSL?

- file ext `.py`
- file content includes `@dsl.pipeline decorator`, which converts python functions to a pipeline component


In order to run these files from the editor, we can start from the steps below:

1. Implement `SubmitBatchJob` (_discuss naming_) button extension for file editors, similar to existing `SubmitNotebook` button extension for notebooks only
2. Refactor common functionalities in SubmitNotebook extension to be shared with SubmitBatchJob, for pipeline submission info required from client side
3. Extend `pipeline-template.json` to recognize argo yaml and kfp dsl files
    - add `op` field for executing different types of node
    - update `description` field to other file types
4. Check if pipeline processor_kfp will need adjustments

**Comment by akchinSTC** [comment]
Edited title, since KFP DSL generation will be deprecated and removed soon from Elyra. So only will need to identify KFP YAML for running.

**Comment by lresende** [comment]
Based on the comment above, I would just close this.
