### ISSUE TITLE
Some invalid instances of valid schemas do not display in the output of `elyra-metadata list` CLI

### ISSUE THREAD

**Issue by vabarbosa** [elyra-ai/elyra#538]
When I run the `elyra-metadata list` command I get the following output:

```
elyra va$ elyra-metadata list code-snippets
[E 2020-05-15 14:57:33,386.386] Schema validation failed for metadata 'project-snippet' in namespace 'code-snippets' with error: 'display_name' is a required property.
Available metadata instances for code-snippets (includes invalid):
Schema         Instance        Resource                                                              
------         --------        --------                                                              
code-snippet   common-imports  /Users/va/Library/Jupyter/metadata/code-snippets/common-imports.json  
code-snippet   create temp     /Users/va/Library/Jupyter/metadata/code-snippets/create temp.json     
code-snippet   is_even         /Users/va/Library/Jupyter/metadata/code-snippets/is_even.json         
code-snippet   js-test         /Users/va/Library/Jupyter/metadata/code-snippets/js-test.json  
```

The `project-snippet` instance fails the validation check (with error: `'display_name' is a required property`) and the instance does not get listed in the table. I was expecting for it to be in the table but include the `**INVALID** (ValidationError)` disclaimer (as seen in #524).

**Comment by kevin-bates** [comment]
Thanks for catching this.  It turns that that the lack of a `display_name` was also causing the creation of the Metadata instance itself to fail - which occurs after validation.  That subsequent failure was preventing the invalid instance from being added to the result set (when include-invalid = True).  This has been fixed in my work for #483 which should be ready shortly.
