### ISSUE TITLE
Submitting pipeline with large dependencies disable other JupyterLab actions

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#576]
The COVID notebook scenario has some large dependencies that are used in multiple nodes, and thus submitting a pipeline for execution takes a long time. In this case, the dialog box indicating a successful submission to kfp is taking too long, and in the meantime, other actions that need to invoke any Jupyter Server APIs are not working (e.g. open notebooks, save pipeline, etc).

**Comment by ajbozarth** [comment]
As requested by @lresende I'm taking a look at this. I may not figure it out before my week vacation next week though, if others want to take a shot at it while I'm gone.

A more detailed understanding of this "bug" is:

When a user submits a pipeline (run or export) it displays a "warning" dialog to tell the user the submission may take some time (once it's submitted it shows a "results" dialog). The problem is the warning dialog is dismissible and if dismissed behavior until the results dialog displays is "odd." Some examples are:
- The run and export buttons don't work, their dialogs will only open after the result dialog is show and dismissed.
- any attempt to save (any file) wont succeed until the results are shown (using the save button or the file menu).
- other pipeline and notebook feature still work, such as running a notebook or editing a pipeline (including the clear button)
- any calls to the elyra api (such as opening the code-snippet side bar) wont go through until the results are displayed.

**Comment by ajbozarth** [comment]
I ended up tracking down the root cause for this pretty fast. All the functionality that doesn't work during the submission has one thing in common: they make a call to the api. This seems to mean that while our submission is calling the api no other calls can go through and any feature that leverages a call will "hang" on that call until the submission api call finishes.

For solutions to this problem I have a couple ideas (not mutually exclusive):
- we add more details to the warning dialog that specifically call out how some feature may not work while the submission is ongoing
- we make it so the user can't dismiss the dialog as easily. We could do this my leveraging similar changes to #684 that will allow us to disable a dialog button so the user would only be able to clear it by clicking outside the dialog or the esc key (both of which dynamically close dialogs are are difficult to impossible to disable. 
- we look into "speeding up" the submission in some way so the time the api is blocked is minimized.

We should discuss this at our next scrum/dev meeting

**Comment by kevin-bates** [comment]
Thanks for the last two comments @ajbozarth - this raised an alarm immediately for me (and affirmed in your subsequent response):
> any calls to the elyra api (such as opening the code-snippet side bar) wont go through until the results are displayed.

We need to make sure that stack (pipeline submission and export) is async-enabled.  This is the same issue the jupyter framework _had_ with starting kernels.

However, async-enablement won't resolve the issue for things taking a long time for submission - the time will still be the same - just that the UI will have more liberties to do other things - like fetch metadata or submit another job, etc.

**Comment by ajbozarth** [comment]
Front end test case to see if a server fix address the issue:

1. Make some small change to the pipeline (move a node) so it has unsaved changes. Note that the `X` on the tab will be replaced with a dot representing unsaved changes.

2. Submit a pipeline and dismiss the warning dialog

3. Try saving (either using the save button or via the file menu)

4. If the server-side solution worked then the dot on the tab should be replaced the `X` to show a successful save. If the dot is still there then the save call is still blocking on the server.
