### ISSUE TITLE
Link to container image in runtime image configuration

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#581]

**Comment by ptitzler** [comment]
Background information: As a user I can choose which Docker image will be used to run a notebook, when a pipeline is executed. However, without knowing what (e.g. packages) is preinstalled in the default images one can choose from, one cannot determine beforehand whether a notebook will run successfully or fail due to a missing dependency. To avoid trial-and-error approaches, we should provide users with access to information that helps him/her make an informed decision. This information includes the Docker image name which is ideally associated with a direct link that provides more information about the image.

**Comment by lresende** [comment]
Could you provide more details on where we would need to provide more information? 
When I hover the specific node, I already see the image info, but I guess this would be some other place?

![image](https://user-images.githubusercontent.com/382917/111020493-2b8fea00-837b-11eb-81c0-6dcb98502cfc.png)

**Comment by ptitzler** [comment]
Elyra should provide a link to the container image in the specified repository in the summary view, which is currently only a JSON dump:

![image](https://user-images.githubusercontent.com/13068832/111192923-d7e9f000-8576-11eb-9557-aa8749526d9b.png)

Example: if the user enters `continuumio/anaconda3`, `https://hub.docker.com/r/continuumio/anaconda3` would be displayed as link. An implementation would need to parse the provided input to determine what the correct repository URL is, since there are many public/private repositories other than hub.docker.com.

This is similar to what Elyra already does for links in runtime configurations:

![image](https://user-images.githubusercontent.com/13068832/111193045-fc45cc80-8576-11eb-98f1-a267a30bdde4.png)

**Comment by kevin-bates** [comment]
I like the idea but this loses the tag information - which, in many cases, is critical information.  Was the tag going to be displayed somewhere else?

Did you mean to say:

_if the user selects `continuumio/anaconda3:2020.07`,  the link would reference `https://hub.docker.com/r/continuumio/anaconda3`_?

**Comment by ptitzler** [comment]
Yes! Motivation:
 -  the generated URL might be invalid
 - the URL is likely very long requiring scrolling

Mockup for a new runtime widget, which would expose:
 - the description as a tool tip (see code snippets for reference)
 - the image spec as entered by the user (`[host/]id/image:tag`)

![image](https://user-images.githubusercontent.com/13068832/111344191-658e1400-8639-11eb-8cdf-b0c178c9a02b.png)
