### ISSUE TITLE
elyra-metadata missing when trying to install Elyra under Windows 10 + Anaconda 2020.02

### ISSUE THREAD

**Issue by Fr4nz83** [elyra-ai/elyra#598]
I was trying to install Elyra under Windows 10 + Anaconda 2020.02 by following the steps outlined [here](https://elyra.readthedocs.io/en/latest/getting_started/installation.html).

Unfortunately I'm unable to get past the [step](https://elyra.readthedocs.io/en/latest/user_guide/runtime-conf.html) requiring to configure a pipeline runtime -- indeed, _elyra-metadata_ seems to be just missing, and I was wondering if this is a problem related to the Windows 10 installation.

**Comment by kevin-bates** [comment]
Hi @Fr4nz83 - thanks for opening this issue.  At present, there are [known issues on Windows](https://github.com/elyra-ai/elyra/issues?q=is%3Aopen+is%3Aissue+label%3Aplatform%3Awindows) platforms and we just haven't had adequate access or time to look into these - and we apologize for that.

The `elyra-metadata` application is not part of the 0.10.x release but, rather, built into the 0.11.rc releases - so you should probably try using 0.11.rc2 - although I suspect the same kinds of Windows issues will exist.  If you wanted to try creating runtime metadata using 0.10.x, you'll need to look at the [README file for that tag](https://github.com/elyra-ai/elyra/tree/v0.10.2#configuring-runtime-metadata) - since we also didn't have formal docs at that time either (iirc).  Keep in mind, however, that the `elyra-metadata` command-line syntax is different from the 0.10.x form.

It would be fantastic if you wanted to contribute changes to address the Windows support issues!

**Comment by kevin-bates** [comment]
I'm going to close this for now.  That said, we do know of Windows issues (as previously posted) and would welcome contributions to address those.
