### ISSUE TITLE
pipelines store notebook path information that causes issues

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#659]
To recreate:
- Assume JupyterLab is launched in `/mydir`. `mydir` therefore is the working directory, which is empty. 
- Create a subdirectory in `mydir` named `mydir2` (`/mydir/mydir2`)
- Create a notebook `mynotebook` in `/mydir/mydir2`
- Create a pipeline `mypipeline` in `/mydir/mydir2`
- Add notebook `mynotebook` to the pipeline
- Save the pipeline
- Inspect the saved pipeline file. 

You'll notice that the notebook's `filename` is stored as `mydir2/mynotebook.ipynb`

```
[
        {
          "id": "424905cf-aded-438b-a357-5b9572efc847",
          "type": "execution_node",
          "op": "execute-notebook-node",
          "app_data": {
            "filename": "mydir2/mynotebook.ipynb",
          ...
```

As a result the pipeline is not portable:
- Quit JupyterLab
- Copy the pipeline file and the notebook file (which reside in the same directory) to a different directory, e.g. `/mydir3`.
- Open Jupyterlab
- Open the pipeline. It is now unusable because it references a notebook in the `mydir2` directory that does not exist.

**Comment by ptitzler** [comment]
I do believe this is potentially a  _major_ adoption issue. I just tried to use a pipeline that another user created and couldn't do it without completely rebuilding it.

**Comment by ptitzler** [comment]
The root cause of this issue is that the notebook path needs to be relative to the location of the pipeline file, not relative to the location it was stored in when it was created.

As is, it's very easy for a user to break things by simply changing the working directory:
- launch JL in `/dir/dir2`
- create a notebook and a pipeline in ` /dir/dir2`
- quit JL
- cd to `/dir`
- Launch JL in `/dir`
- in the file browser navigate to the pipeline and open it
- the notebook references (and likely other references too) are no longer valid

**Comment by kevin-bates** [comment]
Only if you stay within the same root (notebook) directory between runs does a _moved_ pipeline (within the root) still work.  This is because paths are relative to the root-dir (or notebook-dir).

For example, if you started in `/dir` and created your pipeline (and associated notebook files) in `/dir/dir2`.  Then stopped JL, move only the pipeline to `/dir/dir3`, but start JL back in `/dir`, the notebook references in the pipeline files are `dir2/foo.ipynb`, which in the pipeline file now located in `/dir/dir3` are still valid because everything is relative to `/dir`.  (Note, to test this example you really don't need to restart JL because it's starting from the same place.)

Hmm, so if we were to always create a "workspace" directory in the location where JL starts (e.g., `/dir/workspace`) and ensure the pipelines, notebooks (and resources) reside in (or below) the workspace, then I believe you'd avoid this issue since we're essentially adopting a disciplined approach.  You could then copy the "workspace" and, so long as the next user points JL's notebook-dir to the parent directory of the "workspace", things should work. 

I'm not saying this is a solution, but it could be a documented best practice should this become difficult to resolve more gracefully.
