### ISSUE TITLE
Add support for versioning instead of timestamp when submitting pipelines to KFP

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#679]
KFP didn't have the notion of pipeline version, and due to this Elyra submits a new pipeline with a timestamp appended to it's name to work around this issue.

It looks like in KFP 1.0.0 they now support pipeline versions, and we should leverage that in Elyra which wich will help remove the workarounds introduced around this area.

![image](https://user-images.githubusercontent.com/382917/85504558-1e3e8f80-b5a1-11ea-8e99-c1aa4aa6c11b.png)

**Comment by kevin-bates** [comment]
hmm - to use "versioning" - which really seems like "iteration" to me - wouldn't you need to know what "versions" have occurred previously?  The nice thing about a time-based value is that you don't need to know about past history.

Rather than calling the API for the equivalent of "create run" would we now call "upload version" instead?  And does calling 'upload version' handle the appropriate version increments - and eliminate the need of having to know the history?  (I guess you'd still need to know whether to all 'create run' or 'upload version' though.)

**Comment by lresende** [comment]
What we do today during submit is that we `always` create a `new` pipeline, and then start a `run` for that `new pipeline`. We manage pipeline name conflict with adding a `timestamp` which correspond to sort of a `homegrown version`.

What I am suggesting is, now that KFP supports `updating` a pipeline, which will create a new version of that pipeline, we use that instead of creating a `new pipeline` during submission. 

As for version, well, that is how the feature is called in KFP and was also the same on older workflow projects that I worked in the past.

**Comment by kevin-bates** [comment]
Yes - understood.  If we can ONLY call "update pipeline" - all good.  However, if we have to determine that this is the first time the pipeline has been run, then that implies a need to discover whether it pre-exists or not or have a means of tracking history.  (The former would be preferred since it would account for the case that user keeps the same pipeline but chooses a different runtime.)

Since the kfp server is multi-user, it still seems like the pipeline needs to be uniquely qualified although, in this case, only for the initial run (creation).

This also implies that the pipeline name - as presented to the user - will come from the server in the response to the POST and what is provided to the POST call is more or less a hint or prefix.

((My comment about this sounding more like 'iteration' was exactly just that, a comment.  I didn't mean to offend anyone or any product. This is a very abstract and ambiguous industry and people have different ideas as to how to "materialize" words and concepts.  I was merely providing my idea for how I "materialize" this notion of "version support".))

**Comment by lresende** [comment]
The API needed seems to be available on kfp master but not yet available in a release
