### ISSUE TITLE
Pipeline editor: dark theme uses low contrast color scheme

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#733]
Color scheme used by JupyterLab (relatively high contrast between font color and background):

![image](https://user-images.githubusercontent.com/13068832/87076651-e3f70400-c1d6-11ea-86cf-6e4901c92cf3.png)

Color scheme used by Elyra/pipeline editor (low contrast between font color and background):
![image](https://user-images.githubusercontent.com/13068832/87076494-b611bf80-c1d6-11ea-94be-090cfc6ed344.png)

**Comment by ajbozarth** [comment]
This is blocked by our updating to a newer version of canvas. The version Elyra currently uses doesn't support svgs for the toolbar so we can't edit the color dynamically. This has been address in later versions of canvas and will be an easy fix once we update the canvas version (tracked in #645).

**Comment by vabarbosa** [comment]
Icons passed to the current version of canvas being used displayed as `img` instead of `svg` and thus cannot be easily styled. An update has been added to the recent version of canvas which allows to passing of React components as icons which should allow for better and more easily styling the icons.

Per previous discussion (https://github.com/elyra-ai/elyra/pull/706#pullrequestreview-443437599), it was initially decided to leave the icons blue until the canvas version is upgraded. Upon further investigation, I was able to find workaround. Since image colors can't be changed via css I instead replace the images entirely when the theme is changed. This should suffice until canvas is upgraded.

See PR #743
