### ISSUE TITLE
Code snippet editor: heading should display a user friendly text

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#734]
Current: `Add new <schema-name-string>` 
User friendly: `Add new code snippet`

![image](https://user-images.githubusercontent.com/13068832/87077981-d3478d80-c1d8-11ea-9696-cea95f395315.png)

**Comment by kevin-bates** [comment]
I think this will require we add a `display_name` field to each schema.  However, I'm thinking the display name should start with a capital letter, e.g, `Code snippet` since that's the usual form display names take.  This would mean the UI would need to lowercase the value in this context.

Adding a display name would also help with #737.

Opinions?

**Comment by kevin-bates** [comment]
Looking closer, we won't always be able to provide the schema name in messages - so namespace will have to do in those cases.  This is true for `MetadataNotFoundError` (during named searches) since there's no instance from which we can derive the schema name.

**Comment by ptitzler** [comment]
> Looking closer, we won't always be able to provide the schema name in messages - so namespace will have to do in those cases. This is true for `MetadataNotFoundError` (during named searches) since there's no instance from which we can derive the schema name.

Understood, but where we can, we should.

I also just noticed the tab label, which should be "Add ... " instead

![image](https://user-images.githubusercontent.com/13068832/87096120-fa14bc80-c1f6-11ea-90c9-a10b3e566959.png)

And when a named snippet is being added the label loses context information ...

![image](https://user-images.githubusercontent.com/13068832/87096239-3c3dfe00-c1f7-11ea-9e00-818582c18b67.png)

which is a problem if the user has many tabs open (notice that a user cannot easily determine yet what `w`,`h`, and `y` are because there's no tooltip yet and no helpful label text (e.g. `code snippet w`)

![image](https://user-images.githubusercontent.com/13068832/87096532-e9b11180-c1f7-11ea-8b9e-535493b271ff.png)

**Comment by ajbozarth** [comment]
@ptitzler the issue in your last comment is a regression, something we changed in the final few update to the PR must've messed it up. The "title" on the tab should be "New code-snippet" not "new:code-snippet" @marthacryan do you know how this was lost during development? We should probably track it in a separate issue since it's a separate bug.
