### ISSUE TITLE
Metadata error handling (code snippet example) : display user friendly error message

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#737]
1.0.0 rc0

- Create a code snippet
- Create another code snippet with the same name
- The following error is displayed:

![image](https://user-images.githubusercontent.com/13068832/87081854-e0677b00-c1de-11ea-927d-4d5536cac7de.png)

While the error message is technically correct, it also exposes the user to details that should not be relevant. For well-defined error scenarios (like this one) the error message should be more user friendly and only state something like "A code snippet with this name already exists."

**Comment by kevin-bates** [comment]
I'm good with dropping the resource location (that can be logged in the server log).   Pretty sure adding the schema name (instead of namespace) is doable.

**Comment by ajbozarth** [comment]
This should be included in our client side validation. Will add this to our umbrella task

**Comment by kevin-bates** [comment]
@ptitzler - I think I need to push back regarding inclusion of the schema name in metadata-related messages from the server for the following reasons...
1. The schema name is not always available since it requires the instance to be determined.  Namespace, on the other hand, is always available.
2. Messages including the schema name, as you'd like to see, will ultimately lead to grammatical issues (_A code-snippet instance_ vs. _An image instance)
3. If used for _some_ exceptions, we'd have to look up the schema object to use its (new) display_name attribute, then apply proper (de)capitalization.

However, I am in favor of...
1. Removing the resource indicators.
2. Making existing text more user friendly.  Here are some examples...

Current:
_Metadata instance already exists in namespace 'code-snippets'_
_No such metadata instance found in namespace 'code-snippets'_
New:
_An instance named 'aaa' already exists in the code-snippets namespace._
_No such instance named 'aaa'  was found in the code-snippets namespace._

Since namespace is omnipresent, I think it's sufficient to imply the _type_ of metadata encountering the exception.

Is that sufficient?

**Comment by kevin-bates** [comment]
@ajbozarth - I'm curious how this would be handled on the client-side if you're only given 4xx status codes two which dissimilar errors on the server get mapped?

**Comment by ajbozarth** [comment]
The metadata editor already has the list of metadata available client side, so it could check against that list prior to submission and display its own error. The only case for it not catching such an error is if a user added new metadata via some other method while the metadata editor was open (it grabs the metadata list for the given namespace on opening). So the server should probably still update it's messaging as well.

**Comment by ptitzler** [comment]
Not knowing anything about internals I assumed that the UI caller knows it's context ("User was trying to create a code snippet") and receives a unique code in its server response (errno 17) that allows for mapping to a specific  user-friendly message without having to parse the server response.

**Comment by ajbozarth** [comment]
@ptitzler actual no, in general we just surface the server errors as is, except in certain cases where we have the server return stack traces and those are handled uniquely client side (differentiating those two does sort work as you described though). 

In this case (and anytime we talk about client side validation) we would never contact the server and instead check for specific things (in this case duplicate names) prior to making the server api call. This specific case works because upon opening a metadata editor it makes an api call to get the metadata for the given namespace (in this case code-snippets) and holds onto it until the editor is closed (note that is doesn't update it while the editor is open). We could therefore have the editor check the name against those in that list for duplicates prior to calling the server).

**Comment by kevin-bates** [comment]
Alex - I believe you're only considering already-exists exceptions based on your previous response.  This issue is more general than that and is complaining about the textual responses from the server.  If the front-end can make those better that's great, but I'm not sure how it's going to actually do that with just a couple status codes for several kinds of errors.

**Comment by ajbozarth** [comment]
> Alex - I believe you're only considering already-exists exceptions based on your previous response. This issue is more general than that and is complaining about the textual responses from the server. If the front-end can make those better that's great, but I'm not sure how it's going to actually do that with just a couple status codes for several kinds of errors.

My bad, I seem to have misunderstood the issue and didn't realize it was a general error messaging issue, in which case it'd definitely need a back end solution. (not that client side validation of certain cases like I mentioned wouldn't be good though)

**Comment by kevin-bates** [comment]
I'll go ahead and reference this issue in my pending PR that makes server-derived messages a bit friendlier (although as noted above, the instance _type_ (i.e., schema name) isn't included - only namespace).
