### ISSUE TITLE
Pipeline editor prevents multiple input links on first node added after open

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#750]
For whatever reason, I can no longer associate multiple nodes as inputs to a single node like the following:
![image](https://user-images.githubusercontent.com/22599560/87229613-4af2f500-c35e-11ea-82c2-8d7899491a96.png)
Instead, I see this...
![NoDoubleLinks](https://user-images.githubusercontent.com/22599560/87229844-71199480-c360-11ea-94f3-f96535d53c70.gif)

I'm using master with a last commit of Friday evening: a52f2704bd8d7d95968834553cc9bbd8af8a84a6

Although this is also happening on @marthacryan's prevent-circular branch while looking at #744.

@lresende also confirmed.

**Comment by kevin-bates** [comment]
@vabarbosa found that there appears to be a relationship between the cardinality of the inputs specified in the pipeline file and this issue.  I found that most all inputs have a cardinality of `min: 0, max: 1` - so this would prevent a second input.  If I manually update my pipeline file to specific `min: 0, max: -1`, I can successfully add two inputs to that node.

It also appears as though the FIRST notebook added to the pipeline gets the limitation on inputs while other nodes have NO cardinality specified for either inputs or outputs.  However, there must be some way to have other nodes with the input restriction, but I can't reproduce that at the moment.

**Comment by ajbozarth** [comment]
I did some research into this and tracked down the twofold issue here:

1. As @kevin-bates described above we set the cardinality for input as `min: 0, max: 1` where it should be `min: 0, max: -1` to allow multiple inputs (This of course assumes I'm correctly understanding the meaning of an input cardinality in canvas). This is an "easy fix" that will address the immediate problem.

2. Canvas is only setting the input and output cardinality on the first node added after opening a pipeline editor. This seems to be coming from the function `convertNodeTemplate` here: https://github.com/elyra-ai/canvas/blob/release-6.1.23/canvas_modules/common-canvas/src/object-model/object-model.js#L1129 which we call to create our nodeTemplate (Note that this function has not changed even in master, though it has moved within the file). That function includes a line that "clones" the `app_data` using `JSON.parse(JSON.stringify())` and has a comment explaining that it's important since `app_data.ui_data` is later deleted and it doesn't want to affect the template, just this instance. Yet later in the function it passes the input and output JSON to the function `convertPort` right below. This function has much of the same behavior for inout and output as `convertNodeTemplate` did for `app_data` but it's missing the "clone" step. This means that the input and output ui_data is deleted from our template after the first node (the template being recreated each time the editor is opened). Given that nodes with a cardinality set seem to behave as we want them to in Elyra, fixing this is not an immediate issue for use, but we should raise this on the canvas repo.

**Comment by kevin-bates** [comment]
Updated title to reflect what's going on.

**Comment by ajbozarth** [comment]
Note: canvas has fixed the bug on their end now so our update to latest canvas will address point 2 above

**Comment by tomlyn** [comment]
This issue has been fixed in the Elyra/canvas code.
