### ISSUE TITLE
Pipeline toolbar paste button always enabled

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#768]
As pointed out in #758 paste button is always enabled, even when setting it to `false` in `toolbarConfig`.
Paste events on common canvas should be cleared after clearing a pipeline or when opening an empty pipeline.
![image](https://user-images.githubusercontent.com/25207344/87811019-f2bf6580-c82b-11ea-8c5a-e2f59fee483c.png)

**Comment by lresende** [comment]
> As pointed out in #758 paste button is always enabled, even when setting it to false in toolbarConfig.
Is this an issue on canvas then? If so, do we have an open issue on the canvas repo?

>Paste events on common canvas should be cleared after clearing a pipeline or when opening an empty pipeline.
Now I got confused. Is this a bug on our side?

Stepping back, what is the desired behavior? When I go to a well-stablished product like Word, the paste button is always on, and for example, if I cut the whole document (similar to clear) I can paste it back. You might also be copying something from another pipeline document, and we should be able to paste it.

**Comment by vabarbosa** [comment]
i would think if you configured the parameter to `false` it should appear disabled.
in addition, if there is nothing in the clipboard i would expect it to appear disabled. 

with that said, as you mentioned, i just noticed Paste is always on (even if clipboard is empty) in programs like Word so i guess that would be acceptable behavior.

however, quickly looking at the canvas code they do set the paste state based on clipboard being empty

https://github.com/elyra-ai/canvas/blob/b596b3c9c864331385921871935564a608671caa/canvas_modules/common-canvas/src/common-canvas/common-canvas.jsx#L394-L396
```javascript
if (this.canvasController.isClipboardEmpty()) {
    pasteState = false;
}
...
if (this.state.toolbarConfig[i].action === "paste") {
     this.state.toolbarConfig[i].enable = pasteState;
}
```

in any case, i think this would be a canvas issue as it appears the paste button is never actually disabled. otherwise no point in checking/setting paste state.
