### ISSUE TITLE
Pipeline editor: pipeline should be validated when a user attempts to save it

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#801]
It appears that some (but not all) canvas operations validate the pipeline and issue a warning ("open pipeline") or refuse to perform the requested task ("export", "run)". However, if a user saves an invalid pipeline (e.g. because it is a work in progress) _no warning_ is displayed. 

It'd be nice if a warning is displayed just like it is already done when a user opens an invalid pipeline):
![image](https://user-images.githubusercontent.com/13068832/89162842-ee59b300-d574-11ea-890e-48122510a2d0.png)

**Comment by kevin-bates** [comment]
We should be careful here.  This may be viewed as a nuisance since other pieces in the eco-system do not behave this way (at least that I know of).  Also, if we wanted to add any kind of periodic checkpointing (auto-saving), then we wouldn't want this happening either (although I suppose we could determine the difference between auto-save and explicit-save).  I think leaving this associated with the actual action (run, export) is more appropriate.

**Comment by lresende** [comment]
Should we validate at save? Maybe. 
But we should definitely not cancel save if there are validation errors.
