### ISSUE TITLE
Update pipeline editor to use relative paths

### ISSUE THREAD

**Issue by ajbozarth** [elyra-ai/elyra#823]
Subtask of #822 

Currently all file paths used by the pipeline editor are relative to the jupyter lab working dir (notebook_dir). We want to change this so that the file paths for nodes in a pipeline are relative to the pipeline file, similar to how python imports work in notebooks.

As part of this update we will need to also make sure any relative paths are converted to absolute paths prior to submission to the server.

File paths would need to be validated/converted at the following steps:
- When opening
- When drag-and-drop
- When submitting the pipeline

**Comment by kevin-bates** [comment]
> make sure any relative paths are converted to absolute paths prior to submission to the server

Rather the using _absolute paths_ in this discussion, we should try to use something more like _workspace-relative_ or _working-dir-relative_.  I prefer the former of these two because _working-dir-relative_ could also be ambiguous when the `--notebook-dir` option is used - in which case the notebook server has both a working directory (where it was launched) and a notebook directory (where it looks for notebooks).  I would recommend we use the term _notebook workspace_ to mean "where the notebook server looks for files".

When the server processes files, it _does_ convert the file paths to truly _absolute paths_, so its use in the context above is also ambiguous.

**Comment by ajbozarth** [comment]
Sorry I was coming from the frontend perspective. As far as the front-end is concerned the the `notebook-dir` is root, so absolute paths are relative to it within front end code. I'm ok with different language though
