### ISSUE TITLE
elyra-metadata CLI: install ... help display seems to be incorrect?

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#837]
1.0.0

Running the command below I've noticed that the help output for the last two parameters seems to be problematic:

```
$ elyra-metadata install runtime-images --schema_name=runtime-image
'--name' is a required parameter.

Install a metadata instance into namespace 'runtime-images'.

Options
-------

--replace
	Replace existing instance
--schema_name=<string>
	The schema_name of the metadata instance to install
--name=<string>
	The name of the metadata instance to install
--display_name=<string>
	The display name of the Runtime Image; title: Display Name, minLength: 1
--image_name=<string>
	Runtime Image description; title: Image Name, minLength: 1
```

To be specific:
- `title: XXX` appears to be an internally used property that the user shouldn't be exposed to 
-  `minLength: XXX` appears to be an internally used property that the user shouldn't be exposed to
- `--image_name=<string> Runtime Image description;`  appears to be the wrong description (should be `Docker image name` ?)

**Comment by ptitzler** [comment]
Just realized that other kinds of internal metadata is exposed as well for other namespaces, e.g. `uihints`

```
$ elyra-metadata install code-snippets --schema_name=code-snippet
'--name' is a required parameter.

Install a metadata instance into namespace 'code-snippets'.

Options
-------

--replace
	Replace existing instance
--schema_name=<string>
	The schema_name of the metadata instance to install
--name=<string>
	The name of the metadata instance to install
--display_name=<string>
	The display name of the Code Snippet; title: Display Name, minLength: 1
--description=<string>
	Code snippet description; title: Description
--language=<string>
	Code snippet implementation language; title: Language, uihints: {'field_type': 'dropdown', 'default_choices': ['Python', 'Java', 'R', 'Scala', 'Markdown']}, minLength: 1
--code=<array>
	Code snippet code lines; title: Code, uihints: {'field_type': 'code'}

```

**Comment by kevin-bates** [comment]
Thanks @ptitzler - this is one of the issues with a completely schema-driven approach.  

The intent of the additional metadata (e..g, `minLength: 1`) is to inform the user creating the metadata instance of the restrictions that will be imposed on their entry.  However, since the tool was developed, we've added more metadata that doesn't necessarily apply to the actual instance data (e.g., `title` and `uihints`).  Since we don't have meta-properties about the metadata itself that says - _this_ meta-property applies to data, while _this_ meta-property doesn't, I don't think we have any choice but to **remove** the hinting altogether.

> --image_name=<string> Runtime Image description; appears to be the wrong description (should be Docker image name ?)

Yes, the [`image_name` description](https://github.com/elyra-ai/elyra/blob/master/elyra/metadata/schemas/runtime-image.json#L27) is incorrect.  Runtime-image should also have a `description` property as well.  Both will be addressed in a subsequent PR.
