### ISSUE TITLE
Enable running Notebook pipelines locally

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#842]
We should investigate how we could enable running pipelines locally, assuming the environment works and the resources are there, to simplify some workflow that doesn't need the isolation and more powerful environments.

>  improved pipeline viewer (like Elyra, but for local execution highlighting which notebooks need to be re-run after a change has occurred; and allowing to re-run entire branch with a single click; this will be more of reproducible analysis flow tool than the pipeline as meant in data science).

**Comment by kevin-bates** [comment]
Interesting.  Here are some thoughts I just jotted down (having thought about this for a while) - mostly backend focused:

- Once the pipeline (segment) has been parsed, "processing" is essentially processing each node w/o uploads/downloads from COS.  All inputs/outputs can take place locally.  (Is that a correct assumption?)

- Node execution is essentially the primary purpose of the bootstrapper used today.  (We should change bootstrapper to _node executor_ since the only bootstrapping that it does today will likely be moved to an init container - and that doesn't apply to "local mode" anyway.)

- We should allow a pipeline to run against its configured platform (KFP) and locally (sans platform) - without the user changing anything other than "where" the pipeline is submitted.

- Local mode does not require an image - so front-end validation should be "in tune" with local mode.

- We should create a new endpoint (e.g., `/elyra/pipeline/run` or `/elyra/pipeline/local_run` - some kind of verb/action term) in addition to export and process.  This facilitates the retention of the configured platform configured within the pipeline.  Local runs ignore the runtime image and the configured runtime.

- Not sure we need runtime metadata for local mode.  It would be nice to **not** have a separate instance.  If we find the need for metadata, we should see if the existing runtimes could be extended with "local mode" attributes.  This facilitates the ability to easily run against a configured runtime.

- We probably don't want to process the "segment" as part of the request since these could still take a while.  As a result, this might be a great opportunity to look into async REST - although a polling model could also work.  

- A `POST` to `/elyra/pipeline/local_run`(?) would result in the pipeline (segment) being parsed.  Parsing should probably include dependency existence checking (dependencies and notebook/python files).  Non-existence would terminate the request.  (This is something we could probably do for regular processing as well - as it would improve end-user behavior ("fail fast").)

- Once parsed, the parsed pipeline would be "enqueued" and an id (UUID) would be returned.  The REST API would return the ID.  Note: this behavior could also be used for 'process' and 'export' today - this would then give front-end applications common behavior (not necessary initially).  `GET` requests on the endpoint would take the ID to allow for status acquisition (this kind of thing _could_ be leveraged for 'process' and 'export' endpoints as well).

- When enqueued, an event would be sent, or some loop callback would be triggered.  We'd probably want a separate thread here (not sure how well they play in tornado) to simply walk each node, invoking the guts of the bootstrapper (node_executor) on each node.  The parser would need to make sure the ordering is correct (does canvas already do this for us?).

- Since no COS is required, the node_executor simply does exactly what it does today, sans the upload and download tasks.  Literally, all it needs to do is "execute" the notebook/python/??? since dependencies have already been validated and inputs/outputs are generated and relative to their specified locations.

- The UI, using the ID (UUID) returned from `/elyra/pipeline/localrun` would need to check completion.  Along the way, the node-executor could update a "run ledger" (that includes the ID in its name), indicating what node is being processed, and noting any outputs produced, etc.  On completion, it could produce a simple summary with information akin to the api-endpoint, cos-endpoint details, although more like - here are the locations of your final notebook HTML and output files.  On error, it would indicate the failed node and any exception information.

We obviously already have all the pieces to do this, its just a matter of completing the puzzle for the various scenarios.  I suspect some good refactoring would also result.

**Comment by lresende** [comment]
FYI: @frreiss @krassowski

**Comment by lresende** [comment]
> Interesting. Here are some thoughts I just jotted down (having thought about this for a while) - mostly backend focused:
> 
> * Once the pipeline (segment) has been parsed, "processing" is essentially processing each node w/o uploads/downloads from COS.  All inputs/outputs can take place locally.  (Is that a correct assumption?)

Yes, I want to have a requirement that, in order to run as a pipeline locally, all the pipeline components MUST be already able to run locally outside of the context of the pipeline.

> * Node execution is essentially the primary purpose of the bootstrapper used today.  (We should change bootstrapper to _node executor_ since the only bootstrapping that it does today will likely be moved to an init container - and that doesn't apply to "local mode" anyway.)

I am not planning to use the bootstrapper at all. 

> * We should allow a pipeline to run against its configured platform (KFP) and locally (sans platform) - without the user changing anything other than "where" the pipeline is submitted.

Agree, although as described above, we will most likely ignore all configured properties of each pipeline node when running locally. 

> * Local mode does not require an image - so front-end validation should be "in tune" with local mode.

It's a topic for discussion as I am not sure what should be the ideal solution here. I would assume that we should help the user build a valid pipeline for a given runtime, and local would be a sort of "try/dev mode"... having said that, we currently don't have a way to enable different validation schemas for different runtimes. 

> * We should create a new endpoint (e.g., `/elyra/pipeline/run` or `/elyra/pipeline/local_run` - some kind of verb/action term) in addition to export and process.  This facilitates the retention of the configured platform configured within the pipeline.  Local runs ignore the runtime image and the configured runtime.

I am currently using the same endpoint, just using a different "class" to process the local run which ignores all things specific to a remote runtime.

> * Not sure we need runtime metadata for local mode.  It would be nice to **not** have a separate instance.  If we find the need for metadata, we should see if the existing runtimes could be extended with "local mode" attributes.  This facilitates the ability to easily run against a configured runtime.

"Local" is a fake metadata that is inserted into the list of available options when running a pipeline.

> * We probably don't want to process the "segment" as part of the request since these could still take a while.  As a result, this might be a great opportunity to look into async REST - although a polling model could also work.

With your fix for async mode, we sort of have that working today, the user just needs to hit ok to the submit dialog

> * A `POST` to `/elyra/pipeline/local_run`(?) would result in the pipeline (segment) being parsed.  Parsing should probably include dependency existence checking (dependencies and notebook/python files).  Non-existence would terminate the request.  (This is something we could probably do for regular processing as well - as it would improve end-user behavior ("fail fast").)

We could check that, my original idea was to have a list of processors processing a pipeline, where one could have been "validate" and the processor manager could assemble different list/implementations with more flexibility. Today validation is implemented direct on the model objects which makes applying multiple validation schemas a little more complicated. 

> * Once parsed, the parsed pipeline would be "enqueued" and an id (UUID) would be returned.  The REST API would return the ID.  Note: this behavior could also be used for 'process' and 'export' today - this would then give front-end applications common behavior (not necessary initially).  `GET` requests on the endpoint would take the ID to allow for status acquisition (this kind of thing _could_ be leveraged for 'process' and 'export' endpoints as well).
> * When enqueued, an event would be sent, or some loop callback would be triggered.  We'd probably want a separate thread here (not sure how well they play in tornado) to simply walk each node, invoking the guts of the bootstrapper (node_executor) on each node.  The parser would need to make sure the ordering is correct (does canvas already do this for us?).


Well, this is going more towards implementing a completely new runtime and I was trying to avoid this. I view the "local mode" more like a quick way to run the notebooks locally in the appropriate order, and later on maybe with some optimizations.


> * Since no COS is required, the node_executor simply does exactly what it does today, sans the upload and download tasks.  Literally, all it needs to do is "execute" the notebook/python/??? since dependencies have already been validated and inputs/outputs are generated and relative to their specified locations.

It's very simple, we will basically replicate the same experience you have if you run the notebooks locally... so, no COS, no dependency upload/download/propagation, etc

> * The UI, using the ID (UUID) returned from `/elyra/pipeline/localrun` would need to check completion.  Along the way, the node-executor could update a "run ledger" (that includes the ID in its name), indicating what node is being processed, and noting any outputs produced, etc.  On completion, it could produce a simple summary with information akin to the api-endpoint, cos-endpoint details, although more like - here are the locations of your final notebook HTML and output files.  On error, it would indicate the failed node and any exception information.
> 

For the initial implementation, I would suggest we keep it simple and provide something like "Notebook {path/to/notebook} failed with exception" everything else the user can find on the notebook or on the log. 


> We obviously already have all the pieces to do this, its just a matter of completing the puzzle for the various scenarios. I suspect some good refactoring would also result.

Most of it, yes...
