### ISSUE TITLE
Support hybrid notebook pipelines

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#854]
Currently, if the configured kernel on the notebook is not available, we are assuming it's a python notebook and forcing the default kernel (both in the local runtime and kfp boostrap script). We should make this more flexible, and either fail if the kernel is not found, or at least try to find another kernel that is available on the environment that supports the same language.

**Comment by kevin-bates** [comment]
I think failure is the only choice here.  Even locating a kernel of a matching language isn't sufficient since _that_ kernel may run remotely or require other baggage.  The best we can do is match by name, and even that isn't a guarantee.

**Comment by ptitzler** [comment]
Behavior as of version 1.1:
- Local execution: notebook execution fails
- Kubeflow Pipelines: notebooks are always executed in a Python 3 kernel (and the kernel spec is essentially ignored)

**Comment by kevin-bates** [comment]
I agree, although it implies that users using anything other than the default `python3` kernel anyway will be required to add their kernelspec configuration to the image and bring their own image because it would be nearly impossible (well, extremely difficult) to determine and dynamically deploy locally-configured kernelspecs as part of a node's execution.

**Comment by ptitzler** [comment]
> will be required to add their kernelspec configuration to the image

We will need to add the relevant information to the prerequisites list for runtime images in https://elyra.readthedocs.io/en/latest/user_guide/runtime-image-conf.html.

**Comment by kevin-bates** [comment]
I guess I disagree per my [earlier comment](https://github.com/elyra-ai/elyra/issues/854#issuecomment-673057098).  There's a reason folks aren't using a default kernel and guessing is more effort than its worth since.  Worst case, the notebook runs but produces incorrect results because a different or misconfigured kernel is in use.

If we do proceed, I believe the suggested steps should be:
1. Be optimistic and attempt execution using the notebook-referenced kernel.
1. If execution fails, determine the language of the referenced kernel and try to locate a match.
1. If a matched language kernel is available - reattempt using that kernel.

If we can definitively determine the reason for the initial failure and equate that to a missing kernel (based on manual testing), then steps 2 and 3 can be skipped if failure is due to another reason.

**Comment by ptitzler** [comment]
How about giving the user the option to decide what to do before the run is started?  Not sure we can make a decision that will meet everybody's needs.

**Comment by lresende** [comment]
The user decision is done when he select/change the kernel in the notebook.

**Comment by kevin-bates** [comment]
> The user decision is done when he select/change the kernel in the notebook.

Hmm. This sounds contrary to going through some fallback logic and argues that just running with what's in the notebook.  Am I interpreting this correctly?  If so, I agree. :smile:

**Comment by lresende** [comment]
Fixed by #983 which picks the kernel information from the notebook metadata.
