### ISSUE TITLE
Runtime configuration wizard: existing runtime configuration information is "lost"

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#883]
Follow-up to https://github.com/elyra-ai/elyra/pull/847

I had created a runtime configuration with an earlier version of Elyra. Opening the configuration using the dev build that includes above PR the name and description in that configuration is not displayed:

![image](https://user-images.githubusercontent.com/13068832/90800099-09dcf180-e2c9-11ea-83db-67c0677b7e01.png)

**Comment by ptitzler** [comment]
The existing metadata file content (with confidential information manually changed)

```
$ cat kfp_dev_instance.json 
{
  "display_name": "KFP dev instance",
  "metadata": {
    "api_endpoint": "http:/myhost.mydomain.com:31380/pipeline",
    "cos_endpoint": "http://myhost.mydomain.com:31671",
    "cos_username": "minio",
    "cos_password": "minio999",
    "cos_bucket": "bucketname"
  },
  "schema_name": "kfp"
}
```

**Comment by ajbozarth** [comment]
So I kinda tracked down the source of this issue. After I noticed it also existed on older (previously working) commits I tried installing an older version of lab and that fixed it. So some change between lab 2.2.4 and 2.2.5 broke that specific part of elyra for some reason.

**Comment by ajbozarth** [comment]
I tracked down what I believe to be the issue. The most recent lab release (v2.2.5) updated it's `yarn.lock` and `@blueprintjs/core` was set to the latest release (v3.31.0). This cause use problems because any lab dependency version will override elyra's version (afaik that's just a side effect of how node modules are handled in lab). The new release of `@blueprintjs/core` included a fix https://github.com/palantir/blueprint/pull/4266 that added support for async to `InputGroup`, this new async support broke our async update that occurs after we fetch the metadata from the api. Though I'm unsure of why it broke, I do know that the issue was that we created that field of the form prior to the api call returning, and when updating it was using the previous value rather than the new one from the api. This can be "solved" by waiting to add them field until after the async call. I'll have a PR shortly
