### ISSUE TITLE
Python editor: support setting of environment variables

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#931]
Currently a user can only run Python scripts from the Elyra Python editor that do not have a dependency on environment variables that are not defined in the execution environment. In essence one currently has to define the environment variables before launching JL, which isn't practical, especially in light of the fact that JL might be running remotely. It should therefore be possible for users to specify environment variables, which will be set before the script is executed.

**Comment by kevin-bates** [comment]
I don't think this can be supported since by the time the script is being edited, the underlying kernel (process) has already started.  In addition, "normal" kernel start requests serviced locally don't allow for the conveyance of environment variables.  Enterprise Gateway does, but if its frontend client is a notebook server, those envs must be set prior to the start of the notebook server which provides no conveyance facility.  Only if the python editor issues the REST start requests directly, and those were targeting an EG server, would this be possible.

I believe Python allows you to set env variables on the fly (e.g., `os.environ['FooBar']='BarFoo'`), so wouldn't the user just do this in the script they're editing?

**Comment by ptitzler** [comment]
> so wouldn't the user just do this in the script they're editing?

That'd be one way to do it, although not having the ability to customize the runtime environment (via command line parameters or environment variables, which is commonly supported by IDEs) would limit the editor's usefulness. If there are technical reasons why this can't be done (or shouldn't be done) that's okay but then we should consider adding support for running Python scripts "as a batch" like we already do (even though it appears to be broken right now) for notebooks. That way one can specify environment variables and utilize parametrized scripts without having to actually modify their source code.

**Comment by kevin-bates** [comment]
> That said, unless one can persist the run configuration (and apply it later on again) a user would probably be better off creating a one-node pipeline for parametrized notebooks or Python scripts. Imagine a customizable script that requires 5+ environment variables. Having to type them in (or copy and paste them) repeatedly is just not productive.

I agree.  In addition, any reliance on remote kernels, in either case (python script or notebook), cannot be leveraged (today) once in "pipeline mode".

**Comment by lresende** [comment]
> That'd be one way to do it, although not having the ability to customize the runtime environment (via command line parameters or environment variables, which is commonly supported by IDEs) would limit the editor's usefulness.

The IDE run configuration is equivalent to the Notebook Kernel, and the [kernel configuration ](https://jupyter-client.readthedocs.io/en/stable/kernels.html#kernel-specs)enables you to set environment variables 

Other than that, as @kevin-bates stated above, it's going to be very hard to support for now.
