### ISSUE TITLE
Pipeline validation should detect nodes that are not supported

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#938]
Scenario:
 - User A creates a pipeline using Elyra x.y, which supports Python scripts
 - User B tries to run the pipeline using Elyra version < x.y, which does not support Python scripts

Note: Elyra version x.y produces a pipeline file that is the same version as the one that Elyra version < x.y supports.

Current behavior:
 - Validation does not catch the error
 - Execution fails, and might produce an error like 
   ```
   /Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/site-packages/papermill/iorw.py:98: UserWarning: The specified input file (/Users/patti/elyra_ga/workspace/load_data.py) does not end in one of ['.ipynb', '.json']
   ```

General scenarios that need to be handled is a pipeline is imported into Elyra version < x.y, which was produced by Elyra version x.y:
 - version x.y extends an operator that version < x.y also supports
 - version x.y utilizes an operator that version < x.y does not support
For both cases, version x.y and version < x.y might or might not support the same pipeline file version, e.g. 3.0.

**Comment by kevin-bates** [comment]
Hmm - good point.  Seems like some kinds of changes should warrant a version update even though they are additive.  In these cases, the "upgrade" logic would be a no-op since there's really nothing for the newer version to do because the version bump is more about older versions (of elyra) detecting new pipeline versions.  

Hmm, but this would mean these particular version increments would only happen when the "new thing" (e.g., a python node) was added to the pipeline since an older elyra can still operate on pure notebook-node pipelines just fine (until they include a new node type).

I suppose the real issue here is that the older elyra wasn't checking node types to begin with, thereby allowing incompatible node types to "slip through" - only to fail when the rubber meets the road.

**Comment by lresende** [comment]
With the introduction of #500 we will also have use cases where a specific component is not available/installed on a specific environment, and we will need to flag that these nodes are invalid.

**Comment by akchinSTC** [comment]
as it stands, the pipeline validation service will query the registry and get the component properties of a node, verify that the required fields are present and values are valid and type checked. this should satisfy the generic node type support and compatibility going forward.
