### ISSUE TITLE
Metadata backend:  Enable displaying metadata results sorted

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#959]
There are several scenarios in which a user has to choose a runtime image from a drop down list. They all have in common that the image list is not sorted by display name, which makes it hard to quickly locate the desired name.

### configure pipeline node properties

![image](https://user-images.githubusercontent.com/13068832/95138472-26b97100-071f-11eb-9a9a-3b8e5154a754.png)

### submit notebook

![image](https://user-images.githubusercontent.com/13068832/95138557-5d8f8700-071f-11eb-8ed1-0e865afe4ea5.png)

The list is sorted properly in the runtime images widget:

![image](https://user-images.githubusercontent.com/13068832/95138711-be1ec400-071f-11eb-9ff5-7b978fdd58d5.png)

Is there a way for the API to return the image list by default ordered by display name to achieve consistency across all UI widgets that require the user to select an image from a list?

**Comment by kevin-bates** [comment]
Some thoughts: For the server to return sorted result sets, there are at least two approaches we could take.

1. Let **all** metadata instances be sorted by `display_name` values - which may not be desirable across all schemas.
2. Define a [_meta-behavior_](https://github.com/elyra-ai/elyra/issues/518) in specific schemas that identify the sort key.  The existence of this behavior is optional for each schema.  When present the server's python API would sort the result set based on the identified key.  We'd need to restrict such keys to required, string-valued, properties.

Because the metadata API is scoped to namespace and a namespace can support multiple schemas, that is an issue.  We could also implicitly sort results by schema name, then, by defined sort key, but what happens if one of the "sibling" schemas doesn't define a sort key?  I suppose would just go unsorted amongst themselves. (hmm, I think we're missing the ability to fetch instances of a particular schema within a given namespace.)

If this was to be done only on the client, then it could be specific to runtime-image instances directly, although the CLI tool wouldn't get this.
_Note: the CLI tool already sorts by `schema_name`, then instance `name` (not the `display_name`)._

**Comment by ptitzler** [comment]
The second approach sounds good to me.

> Because the metadata API is scoped to namespace and a namespace can support multiple schemas, that is an issue

Not being familiar with the internals I'm not sure why. Would clients request (or require) multiple schemas to be returned at the same time? For example, if the canvas editor requests a list of runtime images, would more than a Pythonized version of 
```
{
  "display_name": "Anaconda (2020.07) with Python 3.x",
  "metadata": {
    "image_name": "continuumio/anaconda3:2020.07"
  },
  "schema_name": "runtime-image"
}
```
be returned?

**Comment by kevin-bates** [comment]
> Would clients request (or require) multiple schemas to be returned at the same time?

Yes, although it might not be diserable.  Currently all three namespaces 'Code-Snippets', 'Runtime-Images' and 'Runtimes' have a single schema: 'code-snippet', 'runtime-image' and 'kfp', respectively.  However, we will soon offer support for different runtimes where other schemas will be introduced (e.g., 'airflow').  Unfortunately, the REST API that fetches multiple instances of something, works off namespaces not schemas of a namespace.

So in using option 2, and because schemas are scoped by namespace, and the REST API only fetches instances within a namespace, you'll get instances back that span the schemas, when, ideally, you'd probably want the instances sorted within their respective schemas for display purposes.  This is why the comment about implied sorting by schema (when multi-schema namespaces are in play).  Or, we adjust the REST API to tolerate a query parameter (`?schema=xxx`) on the `GET` request that returns all instances of a given namespace: GET /elyra/metadata/runtimes?schema=kfp`

I think sorting implicitly by schema (within a namespace) and when the user isn't applying a query filter is probably a good "system controlled" feature to implement in general anyway.

**Comment by kevin-bates** [comment]
Or, we could just let the application decide how things should be presented, including their ordering.

**Comment by ptitzler** [comment]
> So in using option 2, and ...

Thank you for the explanation, Kevin, now I got it! I firmly believe that the metadata service should behave like a database and should do as much work as possible to avoid re-implementing the same functionality in each client code.

> Or, we could just let the application decide how things should be presented, including their ordering.

That's what we have today and is the reason why I opened this issue. This usability problem has been around for a while and will likely surface in other places where this type of metadata might be exposed in the future. By addressing the problem at the source (applying a meaningful default sort order) we can prevent this from happening altogether. If you prefer not to go that route I'll open two issues requesting the sort order to be changed in the two places I've mentioned earlier.

**Comment by lresende** [comment]
How about changing the title of this issue to something like `Enable displaying metadata results sorted`? Then we can use this for any related work which could be a combination of front-end and backend updates. 

Having said that, what I had in mind, and it's sort of following the way that you guys agreed where this should behave more like a database, but then support `http:// ..... &?sort=field` or have a fully `front-end` solution.

**Comment by kevin-bates** [comment]
I agree with the metadata/database analogy.  The question is whether we have _index definitions_ or not and I'm inclined to hold off adding that kind of thing until we get a better feel for things.  I think adding query parameter support on the REST API would be helpful.  Does this support need to be pushed into the Python API?  Perhaps.  If so, I'd argue that sorting should identify an ordered list of fieldnames that dictate the sort hierarchy.  In the example above, one instance would be `...&?sortby=schema_name,display_name`.  (I'm sure there's some REST API convention for specifying multi-sort fields and we should follow that.)

**Comment by ptitzler** [comment]
> How about changing the title of this issue

Done.

> The question is whether we have index definitions

In which sense? To speed up retrieval or something?

I believe, having both would be ideal:
- the schema definition optionally includes a default sort key that is applied when metadata is requested (aka group by namespace oder by default key)
- the default can be overridden by the client if desired by specifying a custom sort order

The reason why I believe  we should not ignore the first one is that the returned sort order should always be meaningful (e.g. displaying the list of runtime images by default in the order they were created in isn't beneficial to the user) and reflect the most likely sort order in which the returned data will be displayed or processed. Will there be overhead if we always sort? Yes. Is the overhead sigificant? Most likely not, considering we are not looking at gigabytes of data.

**Comment by kevin-bates** [comment]
>>The question is whether we have index definitions

>In which sense? To speed up retrieval or something?

Sorry, I should have been more specific.  I view the implementation at the schema (meta-behavior) level as something akin to an index definition.  For example, a database storage plugin would likely use the sort definitions to convey those fields should be indexed and add the index accordingly.  Likewise, the meta-behavior I describe for uniqueness would be mapped to a primary key.

> The reason why I believe we should not ignore the first one is that the returned sort order should always be meaningful (e.g. displaying the list of runtime images by default in the order they were created in isn't beneficial to the user) and reflect the most likely sort order in which the returned data will be displayed or processed.

Btw, database results are not sorted unless the _caller_ specifies they should be.  As a result, I'm not convinced the system needs to provide implicit sorting at this time.

> Will there be overhead if we always sort? Yes. Is the overhead sigificant? Most likely not, considering we are not looking at gigabytes of data.

Agreed.  Although keep in mind that one day we'll be looking at large multi-user systems handling hundreds of user requests per whatever.  In those configurations, you want to offload as much processing as you can to the client - where CPU is cheap - and it's best to push things like sorting there - where the knowledge what should actually be sorted matters most.

**Comment by ptitzler** [comment]
> database results are not sorted unless the caller specifies they should 

True, this is where my analogy breaks down. However, a database is  generic storage, whereas some metadata instances probably exist for a specific purpose. If that primary purpose is to "give the user the option to choose one-from-a-list" (like it arguable is for runtimes and runtime images), then it's not too far fetched to assume that a specific search order will be applied most of the time by the client.

That said, i'm okay if you decide to not go down that path, as long as we assure that metadata lists are displayed in a user-friendly order.
